### ISSUE TITLE
SHA256 hash mismatch on 2019.0 Beta 2 Windows x64 release

### ISSUE THREAD

**Issue by MystesofEternity** [quelea-projection/Quelea#103]
Already downloaded quelea-2019.0-beta-2-x64-windows-install.exe twice from
https://github.com/quelea-projection/Quelea/releases
And did a sha256sum
Results 2x has been 4d2b604012abaeccbb60d55a9c9462fd841c1a39ebe466f5002a9735c00d3e55
Which is a mismatch of the supposed c5c90a9aa4bc6b04c604cc7c73b0ee7f67c5c2f6b2990d09769d77e770d815e3

Could this be checked please?

**Comment by ArvidNy** [comment]
Just checked it and I can confirm the mismatch. @berry120 manages the releases, so I'm sure he'll have a look at it whenever he gets the chance.

**Comment by berry120** [comment]
Thanks for the heads up. Should now be fixed.

**Comment by MystesofEternity** [comment]
Thank you very much for your hard work (Y)
