### ISSUE TITLE
Issue with Fop cache permissions on some systems

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#109]
Apache fop uses a cache by default that may become inaccessible on some systems, causing errors like the following:

    java.io.FileNotFoundException: /home/user/.fop/fop-fonts.cache (Permission denied)

There's really no need for this cache to exist, so it should be disabled so as not to cause problems.

**Comment by JancoBob** [comment]
I went in and moved the .fop file into the trash and my pdf files are now filled with the proper content. Thanks!
