### ISSUE TITLE
Quelea song pack internals: songs packed with extension .pdf instead of .xml

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#11]
Internally in a Quelea song pack each exported song from the db is packed with extension .xml
In the case of multiple songs with the same song title, however, one song has .xml but 2nd, 3rd, ... song all have extension .pdf.  It would be handy for scripting (I'm doing quite some PowerShell scripting on QSP archives these days) to have all songs in .xml without having to make corrections for the .pdf. Importing such a QSP back into the db this does not pose a problem: all songs are imported, even those with .pdf in the qsp.

**Comment by berry120** [comment]
Should now be fixed with https://github.com/quelea-projection/Quelea/commit/e68fabf01dc6b9d1984bfee8bba64a16f00cfd68 - thanks for the report.

**Comment by DeeTigIT** [comment]
Hi Michael,
What version can I use to test the fix: the CI-release on git or the next nightly on jenkins?
Regards,
Dirk
Verzonden vanaf mijn Windows 10-telefoon

________________________________
Van: Michael Berry <notifications@github.com>
Verzonden: Tuesday, July 10, 2018 9:25:54 PM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] Quelea song pack internals: songs packed with extension .pdf instead of .xml (#11)


Closed #11<https://github.com/quelea-projection/Quelea/issues/11>.

**Comment by berry120** [comment]
You can use the CI release on Github. If you notice anything wrong with it then please let us know (just create a separate issue), as we're still ironing out the quirks.

The old Jenkins system is no longer building new releases, we'll soon turn it off completely.

**Comment by DeeTigIT** [comment]
Hello Michael,
The latest CI crossplatform installer from git: did install, but unfortunately Q doesn’t start. There’s no debug file.
Regards,
Dirk

Verzonden vanaf mijn Windows 10-telefoon

________________________________
Van: Michael Berry <notifications@github.com>
Verzonden: Thursday, July 12, 2018 5:34:22 PM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] Quelea song pack internals: songs packed with extension .pdf instead of .xml (#11)


You can use the CI release on Github. If you notice anything wrong with it then please let us know (just create a separate issue), as we're still ironing out the quirks.

The old Jenkins system is no longer building new releases, we'll soon turn it off completely.

**Comment by berry120** [comment]
Hmm. Could you try running "java -jar Quelea.jar" against the jar file and let me know if there's any output? Thanks.

**Comment by berry120** [comment]
Actually, scrap that, I think it may be fixed in the latest CI release - could you try again?

**Comment by DeeTigIT** [comment]
Hey Michael,
In the latest CI the .pdf extension is fixed voor qsp exports and open lyrics zip exports as well. With the 3rd export option (PDF zip export) I noticed that all pdf’s in the zip have size 0. In the 2018.1 stable rel this is not the case (pdf sizes in zip <> 0). Is this somehow related to the fix perhaps?
Regards,
Dirk

Verzonden vanaf mijn Windows 10-telefoon

________________________________
Van: Michael Berry <notifications@github.com>
Verzonden: Friday, July 13, 2018 12:04:43 AM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] Quelea song pack internals: songs packed with extension .pdf instead of .xml (#11)


Actually, scrap that, I think it may be fixed in the latest CI release - could you try again?

**Comment by berry120** [comment]
That's not related to this issue at all, but was related to the Gradle migration - it should now be fixed in the latest nightly. If not, can you create a separate issue to track progress on that so I don't get muddled? Thanks!

**Comment by berry120** [comment]
Yes - it's always been quite slow I think, there's not much we can do about
that without a lot more work as it's down to the library that we're using.
As long as the process itself works then it's not a regression at least!

**Comment by DeeTigIT** [comment]
I agree, thanks for the fix!

Verzonden vanaf mijn Windows 10-telefoon

________________________________
Van: Michael Berry <notifications@github.com>
Verzonden: Friday, July 13, 2018 10:52:37 PM
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] Quelea song pack internals: songs packed with extension .pdf instead of .xml (#11)

Yes - it's always been quite slow I think, there's not much we can do about
that without a lot more work as it's down to the library that we're using.
As long as the process itself works then it's not a regression at least!
