### ISSUE TITLE
Stage view is showing very small letters.

### ISSUE THREAD

**Issue by RootUserSam** [quelea-projection/Quelea#117]
When I am showing a verse or song, on the stage view, the letters are very small, not big on the projector or the live preview pane. I am not sure how to change this or if it is a bug but please let me know. I have attached pictures.
The first picture is the Stage View:
![IMG_20190413_081907](https://user-images.githubusercontent.com/49592421/56082177-6a514a00-5dca-11e9-9504-2acd43e8781a.jpg)
The second picture is the projector screen:
![IMG_20190413_081927](https://user-images.githubusercontent.com/49592421/56082188-7e954700-5dca-11e9-99f1-9b96e0af6455.jpg)
The third picture is the control screen:
![IMG_20190413_081956](https://user-images.githubusercontent.com/49592421/56082194-9240ad80-5dca-11e9-96e5-1d19edf00187.jpg)
Forgive me if they are a little blurry, I took them with my phone camera. Any help would be appreciated. Thank you.

**Comment by ArvidNy** [comment]
Could you perhaps share your quelea.properties files as well (it's located in C:\Users\YOUR_USER_NAME\.quelea)? In that case we can try to reproduce it. By the looks of it, my guess is that the setting "Maximum font size" might be set to a low number, but it's hard to say by just looking at the pictures.

**Comment by RootUserSam** [comment]
[quelea-programfiles.zip](https://github.com/quelea-projection/Quelea/files/3092242/quelea-programfiles.zip)
[quelea-users.zip](https://github.com/quelea-projection/Quelea/files/3092260/quelea-users.zip)
I have attached two. The one that ends with programfiles is from the program files folder. The one ending with users is from the users folder. Thanks.

**Comment by ArvidNy** [comment]
As I suspected, the "Maximum font size" is rather low. If you try to increase I think it should look better on the projector screen.

@berry120, if I'm not mistaking, I think that setting isn't relative to the canvas size which makes 82 look good on a smaller canvas but really small on a larger screen. Perhaps we should change it? That would make both it easier to set and make the preview correspond better to what it will look like live.

**Comment by RootUserSam** [comment]
The issue I am having is not with the projector but with the stage view. When I am showing a song on the projector, quelea shows the song line correctly on the stage view but when I try to show a verse on the projector, it shows the verse correctly on the projector but the stage view verse is very small. Here are the pictures:
![Main Screen showing verse](https://user-images.githubusercontent.com/49592421/57417276-c4221580-71b8-11e9-9f03-ad088a6412e2.jpg)
Main Screen showing verse
![Main Screen](https://user-images.githubusercontent.com/49592421/57417277-c4221580-71b8-11e9-8bdb-8d3ab2ce0d24.jpg)
Main screen showing song
![Projector showing verse](https://user-images.githubusercontent.com/49592421/57417279-c4221580-71b8-11e9-8a3a-6220c2b1a4b1.jpg)
Projector showing verse
![Settings Screen](https://user-images.githubusercontent.com/49592421/57417280-c4221580-71b8-11e9-8055-4aecb577e222.jpg)
Setting screen. As you can see the setting for the font is set to 300.
![Stage view showing same verse](https://user-images.githubusercontent.com/49592421/57417281-c4baac00-71b8-11e9-95a3-71cd2869b00e.jpg)
Stage view showing verse. Unreadable.
![Stage view showing song line](https://user-images.githubusercontent.com/49592421/57417282-c4baac00-71b8-11e9-8264-232f04b17746.jpg)
Stage view showing song line. Readable.

**Comment by ArvidNy** [comment]
Oh, I seem to have read your initial question way too fast and completely overlooked the fact that this only was true for Stage View... So sorry about that! This does seem to be a bug that I can confirm, so we should definitely look at this before the next stable release. Many thanks for the pictures, that made it very clear!
