### ISSUE TITLE
Playing Lyrics along with Song/Adding audio clip to song

### ISSUE THREAD

**Issue by shreyasgangwar** [quelea-projection/Quelea#120]
Currently, a song can only be projected with lyrics and when we add an audio file(multimedia) only song plays, without any lyrics. There's no combination with a solid image background option as well. To have this feature along with a play/ pause functionality for those leaders that like to read a verse aloud in the middle of the song.

**Comment by DeeTigIT** [comment]
Is this perhaps similar to: 
Allow audio clips to be added to songs (to be played when they're projected live.) #28

 https://github.com/quelea-projection/Quelea/issues/28

**Comment by DeeTigIT** [comment]
https://github.com/quelea-projection/Quelea/issues/28

**Comment by berry120** [comment]
Yup, I think this is a duplicate of #28 .

If not and we're missing something, let us know and I'll consider reopening 👍
