### ISSUE TITLE
Open lyrics importer does not traverse folders in zip

### ISSUE THREAD

**Issue by 07pepa** [quelea-projection/Quelea#122]
There is bug in importer of  openlyrics songs
importer does not traverse any folders  only root

Posible solutions:
ideal situation it would process files on particular level and then went deeper into nested folders

What it is breaking?
Usual problem is that some zipping tool(7zip) like to put all files in foolder named same as zip if you zip it from context menu

**Comment by berry120** [comment]
I'm not sure I'd class this as a bug - I think all our importers work this way (only look at the top level.) I see no inherent reason why we shouldn't recursively traverse over the whole zip file though.

**Comment by 07pepa** [comment]
well...  it depens how you look at it.... 

i also must fixed something that was classified as "bug"  and was basicly enhancment... ( programaticly fixable input   (string.trim())

my view
inputs should be resiliant to comonnly used alternatives... and thanks for accepting my issue

when they arent it should be clearly speccified (witch  is only done in czech  lang file)

so please bunlde a change to this string with your fix in czech file
```
openlyrics.import.line1=Vyberte umístění archivu zip který obsahuje zabalené písně openlyrics níže.
```

**Comment by berry120** [comment]
#194 should solve this (and provide other benefits) when complete, so I'll close this one off.
