### ISSUE TITLE
OpenLP importer skips 1 song detailed information attribute

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#125]
When importing a OpenLP songs.sqlite database, the 'comments' DB-field is not mapped to the Quelea 'Notes' counterpart.

![S1](https://user-images.githubusercontent.com/39883796/56940866-48b5c980-6b11-11e9-866c-3e4d3184bc7d.JPG)

![S2](https://user-images.githubusercontent.com/39883796/56940869-4ce1e700-6b11-11e9-9d11-b761ab52803b.JPG)

**Comment by berry120** [comment]
Should now be fixed in the nightly.

**Comment by DeeTigIT** [comment]
Confirmed, thanks!
