### ISSUE TITLE
Video Dropping to Black on Loop

### ISSUE THREAD

**Issue by Benykoss** [quelea-projection/Quelea#135]
Hi,
     When I use a video as a background for a song, it drops to black when the videos loops.
I have tried visiting the forum for Quelea, but it does not load anything and says it does not exist or I do not have permissions (https://groups.google.com/forum/#!forum/quelea-discuss).

I am running version 2019.0 Quelea and latest Java & VLC update on a Windows 7 machine.

Can someone help?

Thanks!!
Ben Kosswig

**Comment by DeeTigIT** [comment]
Could this be of any help:
https://quelea-projection.github.io/docs/Troubleshooting
"The video background flickers as it repeats"

**Comment by Benykoss** [comment]
I tried the above mentioned settings in VLC, still experiencing an issue.
When the video loops, it flashes black.

**Comment by Benykoss** [comment]
@DeeTigIT Do you have any other ideas what might cause this and another possible fix?

Thank you!
Ben

**Comment by DeeTigIT** [comment]
Hello Ben,

You can combine multiple videos at the same time. The same video multiple times is also possible.
Check the crossfade checkbox.
By merging the same video multiple times you create an extended video long enough so in practice it won't loop.

https://clideo.com/merge-video

Perhaps also check your original video on the presence of any ending, back part. 
If so, remove it with video editing software.

Regards,

Dirk

**Comment by DeeTigIT** [comment]
Hallo Ben,

Have you tried clideo to create a longer video that might solve your issue?

Regards,

Dirk

**Comment by DeeTigIT** [comment]
Hello Ben,

You can try the solution recently described by David in the Quelea comunity:

"I downgraded VLC to 2.2 and upgraded Quelea to 2019.1 a great combination. And no more black screen on the motion backgrounds!!!"

Ref:
https://quelea.discourse.group/t/background-video-loop-black-screen-solved/191

Thanks,

Dirk

**Comment by joncojonathan** [comment]
@Benykoss is this still a problem with the latest 2020.0 release?

https://github.com/quelea-projection/Quelea/releases/tag/v2020.0

**Comment by berry120** [comment]
This should now be fixed in the latest CI release -we've switched to GStreamer which shouldn't have this issue.
