### ISSUE TITLE
Dark application theme : title colours

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#137]
I like the new dark theme!

2 Remarks:
- Can all titles always have colours? (currently, some titles are initial white and show their colour only when selected)
- The dark blue Verse title is not that visible on my PC.

![S1](https://user-images.githubusercontent.com/39883796/57806017-87c55b00-775e-11e9-80b9-fb38ac7ef250.JPG)

**Comment by ArvidNy** [comment]
Thanks for the feedback! I agree that we should sort those things out. I probably overlooked that when I added the dark theme. I'll let you know when we've had the chance to fix it!

**Comment by ArvidNy** [comment]
This should now be sorted out. Do let me know if you try the CI release if it's working for you.

**Comment by DeeTigIT** [comment]
It's working, thanks!

![S1](https://user-images.githubusercontent.com/39883796/58509417-cc0d1e00-8196-11e9-925f-816120a2dd65.JPG)

**Comment by DeeTigIT** [comment]
[Afbeeldingsresultaat voor duim png]

Thanks!

Van: Arvid Nyström [mailto:notifications@github.com]
Verzonden: zondag 26 mei 2019 17:38
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] Dark application theme : title colours (#137)


This should now be sorted out. Do let me know if you try the CI release if it's working for you.
