### ISSUE TITLE
Remove SongSelect USR file import

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#152]
It seems as if SongSelect [no longer offers .USR files anymore](https://forums.openlp.org/discussion/3598/importing-a-song-from-songselect-ccli). They seem to only offer .TXT files, so you will need to support importing songs from a .TXT file as the default for SongSelect. However, they are able to be imported just fine through the Plain Text import options.

**Comment by berry120** [comment]
Yup, we're aware of this - it's been gone for a while unfortunately. We updated the plain text importer so it should deal with plain text files from Songselect ok instead.

The USR option will stay for this next release in case anyone still has any lingering USR files that they may wish to import, but certainly in the release afterwards (maybe 2019.2 or more likely 2020.0) we'll scrap it. At that point Songselect will have been without USR support for a good few years, so no real reason to keep it around.

I'll keep this one open for now so we don't forget.
