### ISSUE TITLE
Problems importing openyrics zip

### ISSUE THREAD

**Issue by ond1** [quelea-projection/Quelea#155]
Hi,

Firstly I would like to say Quelea is a great software package, which I like using. I hope that I can contribute to the project in some way.

I have been trying to import openlyrics zip file but it is just not doing anything. The Importing status bar just moves backwards and forwards for a very long time. I have tried on version 2019.0 and 2019.1.

Is there anyway for me to check if something is failing in the importing of the XML files? Do you have a logger or is there a way to run Quelea in debug mode to see what is going on?

**Comment by ond1** [comment]
Just to add: As a workaround I had to import the openlyrics files into OpenLP then import the songs into Quelea that way. but this is not ideal because some of the song taggings are lost.

**Comment by berry120** [comment]
Could you attach the files you're trying to import here so we can take a
look? Thanks!

**Comment by ond1** [comment]
Hi,

Here is a cut down version of the zip. For the <br/> tags we have empty
namespace. I will have to get rid of those in my XSLT 3.0 stylesheet.
The stylesheet is used to go from an internal format to openlyrics.

**Comment by ond1** [comment]
Hi,

I think I have resolved or at least found a workaround. It looks like Quelea does not handle all the elements that I had in the openLyrics XML file. Is Quelea fully conformant to the OpenLyrics schema?

I noticed Quelea created a version 0.9 XML. Is there a 0.9 schema out there? On the website https://openlyrics.org/ I only see version 0.8.

**Comment by berry120** [comment]
Sorry, this one seemed to drop off my radar. Afraid I still don't see a sample file attached however?

It should be fully conformant, if it's not then it's a bug and we need to sort it out. We won't necessarily use all the information there in importing, but it shouldn't break the importer either.

The 0.9 is a reference to the latest version here (https://github.com/openlyrics/openlyrics), but it looks like nothing much has happened with it in the last 5 years or so.

**Comment by ond1** [comment]
Hi, 

Thanks for getting back to me. I did delete the sample file attachment. But you should be able to replicate it with the following XML document:

`<song xmlns="http://openlyrics.info/namespace/2009/song"
      version="0.8"
      createdIn="Song Stream 1.0"
      modifiedIn="OpenLyricsConverter.xsl"
      modifiedDate="2015-10-15T01:44:36.679+01:00">
   <properties>
      <titles>
         <title>Song1</title>
      </titles>
      <authors>
         <author>TEST</author>
      </authors>
      <copyright>2015 EAC</copyright>
      <themes>
         <theme/>
      </themes>
   </properties>
   <lyrics>
      <verse name="v1">
         <lines>song line 1</lines>
      </verse>      
   </lyrics>
</song>
`

**Comment by berry120** [comment]
Hmm, can't seem to reproduce it with that file on the CI release. Could you try at some point and let me know if you can (or I'm doing something wrong when trying to reproduce?)

**Comment by ond1** [comment]
I think the problem occurs when there are several files in a zip. I will try to construct another zip file and post it.

**Comment by chris-j-major** [comment]
Hi @ond1 I was recently looking at the Open Lyrics importer, and so tested this on the latest version - and it successfully imported that xml file even when loaded via a zip file.

**Comment by ond1** [comment]
Thanks @chris-j-major for looking into this. I have now converted all songs from the openLyrics XML format. Happy for you to close this bug issue.
