### ISSUE TITLE
French dictionary file for check spelling

### ISSUE THREAD

**Issue by Honkey57** [quelea-projection/Quelea#156]
[fr_words.zip](https://github.com/quelea-projection/Quelea/files/3290748/fr_words.zip)

**Comment by DeeTigIT** [comment]
Hello Honkey57,

Is this zipper meant to be used by the developers in issue 151?

Translation of section titles. #151

If so, than perhaps also attach the zip file to that issue and close this issue.

Regards and blessings,

Dirk

**Comment by ArvidNy** [comment]
Looking at the file it looks like a dictionary file to be used for the lyrics spell check, so this should be a separate issue. Thanks for the addition @Honkey57, we'll add it in when we get the chance!

**Comment by Honkey57** [comment]
> Hello Honkey57,
> 
> Is this zipper meant to be used by the developers in issue 151?
> 
> Translation of section titles. #151
> 
> If so, than perhaps also attach the zip file to that issue and close this issue.
> 
> Regards and blessings,
> 
> Dirk

 Hello Dirk

This zip file is a dictionary for spell checking to add in /Quelea/dictionaries/.

  On issue 151 I asked if it was possible to translate section titles (Chorus, Verse, Bridge etc ...) in another language with a .lang file from the /Quelea/languages​/ directory.
