### ISSUE TITLE
Problem with video, the image gets lost.

### ISSUE THREAD

**Issue by s4mBH** [quelea-projection/Quelea#158]
First of all, good morning, and this text is being translated by Google (Portuguese and English)

I have a problem that is as follows, the projected image is giving some cuts (Black Screen) at some moments during the use, I would like to know what I can do to solve, or if it is already a known BUG on the platform!

**Comment by ArvidNy** [comment]
Here is one thing you could try: https://quelea-projection.github.io/docs/Troubleshooting#the-video-background-flickers-as-it-repeats

If that doesn't work, make sure that the file itself is possible to loop smoothly with another video software. As a work-around, you could also use a video editor to create a long clip of the video playing over and over again and that way avoid having to rely on VLC for the loop.

**Comment by berry120** [comment]
This should now be fixed in the latest CI release -we've switched to GStreamer which shouldn't have this issue.
