### ISSUE TITLE
Como proyectar en mas de 2 pantallas lo mismo?

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#159]
Como hacer para que quelea envie lo mismo de la principal a 2 o más pantallas?

**Comment by ArvidNy** [comment]
At the moment you can't unless you use a VGA/HDMI splitter of some sort.

**Comment by Cyb3rG0D7** [comment]
ok thanks

**Comment by ArvidNy** [comment]
But feel free to open an issue as a feature request for it if you want to. As usual, if several users request a certain feature we are likely to add it when we get the chance. Can't promise when we'll get to it, but if we have an issue for it we are more likely to remember it.
