### ISSUE TITLE
Fading on song lyric transition

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#160]
Is there a way to add a fading transition between lyric slides in a song? I know it is possible for transitioning to a black screen, logo screen, or cleared screen but I have not seen a way here to do it for song lyric slides. Perhaps this is a feature suggestion.

As a side note, other programs have this capability such as ProPresenter.

**Comment by berry120** [comment]
Not yet - I believe Arvid worked on this a while ago in a feature branch, but it's not yet something we've added to the main release. It's something that's often been requested though.

**Comment by ArvidNy** [comment]
@HeyITGuyFixIt, in case you haven't noticed this yet, this feature is now optional in the latest CI release if you want to try it out. Otherwise it'll be available in the 2020.0 release as well.

**Comment by HeyITGuyFixIt** [comment]
I've noticed it and will likely wait for the 2020.0 release.
