### ISSUE TITLE
RFC: show numerical values next to 'Notices' sliders

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#170]
If possible, show the numerical values next to the 2 'Notices' sliders.

![S1](https://user-images.githubusercontent.com/39883796/62755208-5dd8b780-ba73-11e9-8aba-3c78764b655b.jpg)

![S2](https://user-images.githubusercontent.com/39883796/62755243-7f39a380-ba73-11e9-9feb-15701b769025.jpg)

**Comment by ArvidNy** [comment]
We're planning on updating the preference dialog (see #112), so I'd say it's connected to that issue. I don't see a problem with letting the numbers show now that we're making changes to the dialog anyways. This is the current draft of what the Notices tab will look like:

![options-dialog](https://user-images.githubusercontent.com/14236185/62824312-40533d00-bb9c-11e9-83e8-7562d2def4ed.png)

**Comment by DeeTigIT** [comment]
That’s looking promising! This issue can be closed. ??

Verzonden vanaf mijn Windows 10-apparaat

Van: Arvid Nyström<mailto:notifications@github.com>
Verzonden: zaterdag 10 augustus 2019 18:26
Aan: quelea-projection/Quelea<mailto:Quelea@noreply.github.com>
CC: DeeTigIT<mailto:tiggelaar.d@gmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [quelea-projection/Quelea] RFC: show numerical values next to 'Notices' sliders (#170)


We're planning on updating the preference dialog (see #112<https://github.com/quelea-projection/Quelea/issues/112>), so I'd say it's connected to that issue. I don't see a problem with letting the numbers show now that we're making changes to the dialog anyways. This is the current draft of what the Notices tab will look like:

[options-dialog]<https://user-images.githubusercontent.com/14236185/62824312-40533d00-bb9c-11e9-83e8-7562d2def4ed.png>
