### ISSUE TITLE
2020.0: Problem with new options dialog.

### ISSUE THREAD

**Issue by Honkey57** [quelea-projection/Quelea#175]
I try the new options dialog, good job.
There is a problem, it is impossible to close the options dialog.
My PC run on win10.

**Comment by berry120** [comment]
Thanks for the report. @ArvidNy - this seems to be happening if there's an empty property in the properties file.

For instance, if you have a line with just `oo.path=`, then it causes the issue. If you delete the line, or give a value to that property, it seems fine.

**Comment by ArvidNy** [comment]
Thanks for the bug report! This should be resolved now if you want to give it another try.

**Comment by Honkey57** [comment]
> 
> 
> Thanks for the bug report! This should be resolved now if you want to give it another try.

It works very well :-)  Thanks.
