### ISSUE TITLE
Invalid discussion forum link in language files

### ISSUE THREAD

**Issue by zuglogyuli** [quelea-projection/Quelea#177]
In gb.lang file there's an import.error.message entry, which refer to http://bit.ly/1mePoeh which takes to https://groups.google.com/forum/#!forum/quelea-discuss but this group doesn't exists.
Please fix the url to a song import related discussion group in language files, or maybe to https://quelea.discourse.group/

**Comment by berry120** [comment]
Thanks! Should now be fixed in all language files.

**Comment by zuglogyuli** [comment]
Please, fix the link in the startup.error.text entry also.

**Comment by berry120** [comment]
Should now also be done.
