### ISSUE TITLE
Allow multiple song selection in database

### ISSUE THREAD

**Issue by Honkey57** [quelea-projection/Quelea#180]
Is it possible to select several songs in the database, it would be useful to be able to delete several songs.

Another one that could be nice is that the OpenLyrics import tool cuts a section into several slides for each "optional lines". As these "optional lines" are arranged by the user, the cut will not be where it should not be.

Thank you.

**Comment by berry120** [comment]
@Honkey57 We'll track multiple song selection in the database here - can you create a separate issue for the Openlyrics import, if that's still a problem, and upload a sample file so we can take a look?
