### ISSUE TITLE
Duplicated entries in language files

### ISSUE THREAD

**Issue by zuglogyuli** [quelea-projection/Quelea#181]
There are some duplicated entries in gb.lang and therefore in every language files:
111 - edit.song.button=Edit song
139 - edit.song.button=Edit song

149 - sof.button=Songs of Fellowship
188 - sof.button=Songs of Fellowship

74 - save.schedule.tooltip=Save Schedule
263 - save.schedule.tooltip=Save Schedule

75 - print.schedule.tooltip=Print Schedule
264 - print.schedule.tooltip=Print Schedule

610 - rcs.search=Search Database
615 - rcs.search=Search and Add

637 - mp.button=Mission Praise
640 - mp.button=Mission Praise

638 - add.pdf.tooltip=Add PDF
641 - add.pdf.tooltip=Add PDF

These are unnecessary duplicates, but rcs.search could be a typo and therefore a bug.
Please eliminate the duplicates and fix the rcs.search entry. Thank you!

**Comment by berry120** [comment]
@ArvidNy I think rcs.search relates to the remote control server - any idea what one here is the "correct" one?

**Comment by berry120** [comment]
For now I've gone with "Search and Add" being the correct one since that appears last in the file (so is used at the moment as it would overwrite the first.) Feel free to change if not.

**Comment by berry120** [comment]
Should now be fixed.

**Comment by ArvidNy** [comment]
Sounds good to me! Don't know the web app as well as the Android one, but I would have gone for that one too.
