### ISSUE TITLE
2020.0 CI release : Tools, Schedule Options, 'Copy song to schedule by default' inverted behaviour

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#185]
The GUI setting of 'Copy song to schedule by default' :

![S1](https://user-images.githubusercontent.com/39883796/64132357-a44dd780-cdcf-11e9-861d-cb6601bf7a44.jpg)

Results in the property file value:     default.song.db.update=true

![S2](https://user-images.githubusercontent.com/39883796/64132469-5eddda00-cdd0-11e9-9f1c-62c1b6558720.jpg)

I think this should be the other way around : false

In the illustrating schedule below:
- First song was added by 'double clicking': it isn't copied, it's linked to the db.
- Second song was added using drag-n-drop: it isn't copied, it's linked to the db.
- Third song was added using right-click and copy: this is a correct copy.

![S3](https://user-images.githubusercontent.com/39883796/64132476-6bfac900-cdd0-11e9-83bb-5f0bf5dc642a.jpg)

**Comment by ArvidNy** [comment]
Thanks for the bug report, you're correct! It's a bit confusing that we have a setting value that is opposite to what the GUI is asking for, but this should now be resolved.
