### ISSUE TITLE
2020.0 CI release : Tools, Notices sliders, trunc values to int

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#186]
The notices slider values could be truncated to int without decimals.

![S1](https://user-images.githubusercontent.com/39883796/64144264-fb759b80-ce13-11e9-874d-d64c46e2c1e3.jpg)

![S2](https://user-images.githubusercontent.com/39883796/64144269-016b7c80-ce14-11e9-8145-1dc232d25c14.jpg)

**Comment by ArvidNy** [comment]
I've changed this to only use one decimal instead, hope that's better. If not, feel free to open this issue again and we can look at making a custom setting for only displaying the integer number but storing the full double value at some point.
