### ISSUE TITLE
Linux - JRE Video stream of Quelea does not become background of Projection

### ISSUE THREAD

**Issue by MystesofEternity** [quelea-projection/Quelea#188]
Tech details: This is on a Quelea package installed through snapd on a Debian 9 based GNU/Linux distro.
The distro is using an xorg display server and an xfce desktop environment.

The problem is that the video overlay does not effectively display as the background to the text being displayed by the Projection Window. What happens is that the projection window ends up displaying text in seemingly beige color with a background color close to beige as well. Am I doing something wrong here?

In the taskbar on linux, one can see 3 things related to Quelea:
1. The Quelea UI
2. The Quelea Projection Window responsible for displaying the text. Also responsible for displaying Images if the background is an image.
3. The Video overlay responsible for displaying Videos

NOTE: It only got to my mind that I may have been causing this bug due to a certain "workaround" that I discovered when I had problems showing things up on my first run of Quelea on linux. This "workaround" involves the following steps:
1. Run quelea and get to see that the only thing that gets projected is a black screen regardless of whatever you try to project live.
2. Change the Output 2 from Display #2 to None then ensure it gets applied by click Ok on the bottom of the preferences window.
3. Same as #2 only that you will instead change the Output 2 from None back to Display #2.
4. Repeatedly click the video overlay in the taskbar until meaningful projection shows up.

So far so good, images and text display pretty nicely in Quelea but I have yet to gain real success on projecting videos. And yes VLC is installed on this distro.

**Comment by berry120** [comment]
Could you attach the debug log in case that gives us any clues?

https://quelea-projection.github.io/docs/Debug_log

**Comment by berry120** [comment]
Closing old VLC related issues off as we've switched to GStreamer.
