### ISSUE TITLE
I want this program to make "in Korean Version". very good program

### ISSUE THREAD

**Issue by mailsjb** [quelea-projection/Quelea#191]
This is a very well-made program. Thank you for using it in many countries. I would appreciate your support in Korean.

**Comment by berry120** [comment]
We'd love to have a Korean translation, but unfortunately none of the team speak Korean! If there's anyone who does, then you can find instructions for translating the program here:
https://quelea-projection.github.io/lang/

**Comment by berry120** [comment]
Closing this as we don't tend to track translation requests in GitHub issues, but still very happy to receive any new ones! See quelea.org/lang for the process.
