### ISSUE TITLE
"null" password in CI Build 555

### ISSUE THREAD

**Issue by cskeel** [quelea-projection/Quelea#192]
The pre-release 555 allows a blank password to be saved (a change from previous releases), however, when logging in from an android device using Stage Mode, a blank password is not accepted.  If a blank password was not intended, it would be a nice enhancement.  Using multiple monitors with everything automated except the password.

**Comment by berry120** [comment]
Good spot.

@ArvidNy This sounds suspiciously like it might be related to the options dialog changes allowing a blank password where we didn't before - mind taking a look at some point?

**Comment by ArvidNy** [comment]
Sure, I'll have a look. Do you think I should just disallow empty passwords or should we add that option?

**Comment by berry120** [comment]
Tempted to say we should probably stick to the way things are at the moment and disallow empty passwords - seems a bit too much control to give "passwordless" otherwise.

**Comment by ArvidNy** [comment]
I agree, that was my first thought as well.
