### ISSUE TITLE
2020.0 CI release : Import OpenLyrics, multiple xml-files

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#197]
Hello,

The OpenLyrics importer now has 2 import possibilities:
- zip
- xml-file(s)   <- new

1) When choosing xml, one can only select 1 xml-file. Selecting a set of xml-files is not possible?

2) Perhaps the information header in the import-window can also be changed somewhat, in that it mentions both zip and the new xml? 

Regards and blessings,

Dirk

2019.0:

![S1](https://user-images.githubusercontent.com/39883796/65726953-a47f8100-e0b6-11e9-842e-eb624df3d77c.jpg)

![S2](https://user-images.githubusercontent.com/39883796/65726960-a8ab9e80-e0b6-11e9-9510-412f42b918fe.jpg)

2020.0 CI:

![S3](https://user-images.githubusercontent.com/39883796/65726969-b06b4300-e0b6-11e9-9ad8-d62279c1f441.jpg)

![S4](https://user-images.githubusercontent.com/39883796/65726976-b3663380-e0b6-11e9-9d61-64536da1474a.jpg)

![S5](https://user-images.githubusercontent.com/39883796/65726983-b5c88d80-e0b6-11e9-946d-1b4614f181ef.jpg)

**Comment by berry120** [comment]
Good spot. Should now be fixed in the CI.
