### ISSUE TITLE
Import problem with OpenLyrics .zip file 

### ISSUE THREAD

**Issue by Honkey57** [quelea-projection/Quelea#199]
When I want to import openlyrics songs from a .zip file, the "import" button remains disabled after I choose the file.

**Comment by DeeTigIT** [comment]
What version of Quelea are you using?
Could you attach the .zip to this issue? (so that developers can sort things out)

**Comment by Honkey57** [comment]
Build 564.
[Chants.zip](https://github.com/quelea-projection/Quelea/files/3665987/Chants.zip)

**Comment by berry120** [comment]
@Honkey57 Seems you've closed this issue - is this because you're no longer having this problem?

**Comment by Honkey57** [comment]
I am not a specialist on Github, I clicked on the wrong button. I did not want to close the issue.

**Comment by berry120** [comment]
Ok, reopening it in that case!

**Comment by Honkey57** [comment]
Thank you :)

**Comment by berry120** [comment]
Ok, that should now be sorted in the CI release when it builds - we weren't checking for a windows based encoding (rather than UTF-8) on the zip files.
