### ISSUE TITLE
2020.0 CI release : link menu item 'Support / Discussion (ask question here)' to Quelea Community

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#204]
In the latest 2020.0 CI, the menu item 'Support / Discussion (ask question here)' still lands on the previous Quelea Google Group. Can it be redirected to the actual Quelea Community? (https://quelea.discourse.group/)

**Comment by berry120** [comment]
Good catch! This is a trivial one if you (or anyone else) want to make this PR as a contribution to [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

Here's the relevant line that needs to be changed:

https://github.com/quelea-projection/Quelea/blob/00816c032ba55fa4280e62c544468ff84ec7751e/Quelea/src/main/java/org/quelea/services/utils/QueleaProperties.java#L1404

...and it should also be referenced as a line in the next changelog:

https://github.com/quelea-projection/Quelea/blob/00816c032ba55fa4280e62c544468ff84ec7751e/Quelea/changelogs/changelog-2020.0.txt#L1

**Comment by berry120** [comment]
Fixed by #207
