### ISSUE TITLE
Allow Mobile Stage View 

### ISSUE THREAD

**Issue by cskeel** [quelea-projection/Quelea#216]

**Comment by cskeel** [comment]
I am running 12 pc’s utilizing android OS (primeOS) for band members to view lyrics and chords.  Everything is automated except the password.  It would be handy when starting the system AND for the periodic computer crash if the machine had the password stored.

**Comment by ArvidNy** [comment]
Is this no longer a request or did you close this by accident?

**Comment by cskeel** [comment]
I must have closed it by accident
