### ISSUE TITLE
Quelea on Linux - Add Images not seeing JPG files

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#217]
I am using a fresh installation of Peppermint 10 (which is based off of Ubuntu). I installed Quelea (version 2019.1, Java version 1.8.0_212) via Snap. I have a few JPG images that were created by exporting PowerPoint slides as JPG images on a Windows 10 laptop (not sure if that really matters) and I tried to use the Add Images feature in Quelea to add these images. However, when I browse to the folder that these files are located in (I have confirmed that this is the right folder multiple times) and it is not showing the images at all. The following issue shows what I am seeing:

![Screenshot_2019-11-09_09:04:26](https://user-images.githubusercontent.com/34974905/68529779-14953f80-02d0-11ea-9875-9828c8d49650.png)

I have used Quelea before on a Windows 10 computer and have not had this issue. I have another Linux computer that I use Quelea on but haven't tested the Add Images feature to see if this occurs there as well. If I remember to, I will test it tomorrow.

The debug log is not showing anything related, as far as I can tell.
[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/3827365/quelea-debuglog.txt)

I'm not sure what the problem is. Other programs that can open JPG files can open them just fine, such as xviewer and GIMP. If there is any other information that you may need, feel free to ask.

**Comment by HeyITGuyFixIt** [comment]
I noticed that when trying to open an image file with "jpg" as the file extension, instead of "JPG", actually works. So I renamed the image files I have from "*.JPG" to "*.jpg" and they are now visible to Quelea. Not sure why this is the case, but I don't think it ought to be this way.

**Comment by ArvidNy** [comment]
Good catch! It seems file names are case sensitive also when it comes to the file extensions on Linux, but not on Windows. That means you could have one file called `image.jpg` and another one called `image.JPG` on Linux. We have only added the lowercase file extension to the filter, and my guess is that no one has noticed this before since an uppercase extension is picked up anyways on Windows. We should of course add the uppercase file extension to the filter, but until then you can continue using the workaround you found by renaming the files.

**Comment by HeyITGuyFixIt** [comment]
Looking through the code, I'm not seeing where this filter you mentioned would be located. I would be willing to make a pull request for this, but I don't know which file to start with.

**Comment by ArvidNy** [comment]
Great, feel free to open a PR for this! The method that needs to be edited should be [this one](https://github.com/quelea-projection/Quelea/blob/9ea15cc5407776fa569a67364b96aa78428dfd80/Quelea/src/main/java/org/quelea/services/utils/Utils.java#L804-L813).

**Comment by berry120** [comment]
Should now be fixed as per the above PR.
