### ISSUE TITLE
 2020.0 Beta 1 release : user option 'Allow custom item themes to override global theme' broken

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#226]
In the current 2020.0 CI release, the user option 'Allow custom item themes to override global theme = true' doesn't work correct anymore, see below. 

I think this is could be regression, introduced with the new Tools, Options functionality. We had this bug in the past, namely, and it was fixed. Perhaps that fix is now (partially) overwritten by the new Tools, Options code that was merged some time ago into the CI?

If you compose a schedule with a custom item with it's own theme, then the override does work. However, if you save the schedule, start Quelea again and re-open the schedule, then the default theme is shown and the override doesn't work anymore.

This happens both for a schedule file with either:
- Embedded media : 
I've checked the schedule internals: the media, that were used in setting up the custom item theme, are mentioned in the song xml AND are present in the 'resources' subfolder.
- Linked media : 
I've checked the schedule internals: the media, that were used in setting up the custom item theme, are mentioned in the song xml.

So, although the item media are mentioned or present in the schedule, they don't override the default global theme anymore if the schedule is re-open in a new Quelea session.

We are using the 2019.0 cross platform release for production.
I've tested above with the latest 2020.0 CI cross platform.

**Comment by berry120** [comment]
This issue has been mentioned on **Quelea community**. There might be relevant details there:

https://quelea.discourse.group/t/custom-theme/336/2

**Comment by DeeTigIT** [comment]
I renamed this issue to **2020.0 Beta 1** ... because it's still present in the latest cross platform install.

In the attached schedules:
- The 1st song has it's own image: backgroundimage:beach.jpg
- The 2nd song has no theme override (so the Quelea song default should be used)
- The 3rd song has it's own video: backgroundvideo:earth and sun.mp4

After re-opening the schedule, all songs are shown with the Quelea song default theme, although the "Allow custom item themes to override global theme" option still is set.

[test - without embedded media.qsch.zip](https://github.com/quelea-projection/Quelea/files/4524848/test.-.without.embedded.media.qsch.zip)

[test - with embedded media.qsch.zip](https://github.com/quelea-projection/Quelea/files/4524849/test.-.with.embedded.media.qsch.zip)

**Comment by berry120** [comment]
Hmm, I can't seem to reproduce this, but then I don't think I could reproduce it last time either - @ArvidNy, any joy your end? I feel like you may have been able to reproduce this when I couldn't before...

**Comment by ArvidNy** [comment]
Yup, I can verify that the custom theme is removed when a schedule item is imported. Seems like the default theme is always loaded instead of reading the theme from the schedule XML: https://github.com/quelea-projection/Quelea/blob/c5f0c9e606dfe65cc104149f8aeb4ce53a4a0fac/Quelea/src/main/java/org/quelea/data/displayable/SongDisplayable.java#L1256-L1258

Shouldn't be a new bug however, this bug must have been present in previous versions of Quelea as well.

**Comment by DeeTigIT** [comment]
The issue isn't present in the 2010.0 cross platform: our church is using this for almost a year now. At saturday the the schedule is prepared including custom themes. On Sunday the schedule is re-opened and custom theme override work as expected.

Also, when re-opening the above 2020.0 Beta 1 example test schedules "test - without embedded media.qsch" and "test - with embedded media.qsch" in the 2019.0 Quelea version **they work as expected:**

[Q2010.docx](https://github.com/quelea-projection/Quelea/files/4527937/Q2010.docx)

So, the schedule made in Q 2020.0 Beta 1 is internally correct (because Q 2019.0 can interpret the custom themes correctly).

**Comment by DeeTigIT** [comment]
Hello Michael,

Will this fix be released in a coming 2020.0 Beta 2 ?

Regards and blessings,

Dirk

Van: Michael Berry [mailto:notifications@github.com]
Verzonden: maandag 22 juni 2020 15:50
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] 2020.0 Beta 1 release : user option 'Allow custom item themes to override global theme' broken (#226)


Closed #226<https://github.com/quelea-projection/Quelea/issues/226> via 0d1420d<https://github.com/quelea-projection/Quelea/commit/0d1420db28634b71ca66f15e5e35b63d69df5caa>.

**Comment by berry120** [comment]
Yes :-)

**Comment by DeeTigIT** [comment]
👍🏻

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Michael Berry <notifications@github.com>
Verzonden: Thursday, June 25, 2020 11:52:18 PM
Aan: quelea-projection/Quelea <Quelea@noreply.github.com>
CC: DeeTigIT <tiggelaar.d@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [quelea-projection/Quelea] 2020.0 Beta 1 release : user option 'Allow custom item themes to override global theme' broken (#226)


Yes :-)

**Comment by berry120** [comment]
Should be fixed in the latest beta: https://github.com/quelea-projection/Quelea/releases/tag/v2020.0-beta-2

**Comment by DeeTigIT** [comment]
Hello Michael,

I did a test with the latest 2020.0 Beta 2. Using both test schedules, as attached to this issue 226:
test - without embedded media.qsch(.zip)
test - with embedded media.qsch(.zip)

In these schedules:
- The 1st song has it's own image: backgroundimage:beach.jpg
- The 2nd song has no theme override (so the Quelea song default should be used)
- The 3rd song has it's own video: backgroundvideo:earth and sun.mp4

**test - without embedded media:**
 _'Allow custom item themes to override global theme = true'_
- The 1st song is correctly shown with it's own image: backgroundimage:beach.jpg  ==> OKAY 
- The 2nd song is correctly shown with the Quelea song default  ==> OKAY
- The 3rd song is correctly shown with it's own backgroundvideo  ==> OKAY

 _'Allow custom item themes to override global theme = false'_
- The 1st song is correctly shown with the Quelea song default  ==> OKAY 
- The 2nd song is correctly shown with the Quelea song default  ==> OKAY
- The 3rd song is correctly shown with the Quelea song default  ==> OKAY

**test - with embedded media:**
 _'Allow custom item themes to override global theme = true'_
- The 1st song is correctly shown with it's own image: backgroundimage:beach.jpg  ==> OKAY / NOT OKAY 
- The 2nd song is correctly shown with the Quelea song default  ==> OKAY
- The 3rd song is correctly shown with it's own backgroundvideo  ==> OKAY / NOT OKAY 

 _'Allow custom item themes to override global theme = false'_
- The 1st song is correctly shown with the Quelea song default  ==> OKAY 
- The 2nd song is correctly shown with the Quelea song default  ==> OKAY
- The 3rd song is correctly shown with the Quelea song default  ==> OKAY

The explanation of OKAY / NOT OKAY:
- OKAY : if beach.jpg is present in the c:\Users\<user>\.quelea\img\ folder.
- OKAY : if earth and sun.mp4 is present in the c:\Users\<user>\.quelea\vid\ folder.
- NOT OKAY : if they are not present in the img/vid folders.

**So, a schedule with embedded media is not treated properly:** 
**Instead of taking the schedule incorporated media (as they are present in the 'resources' folder of the schedule), the local user img/vid objects are used.**
(If I remember correctly: previously these incorporated media were exported to a user folder (can't remember the location, I'm afraid) and used from there.)

**Comment by DeeTigIT** [comment]
Some further observations:

**1.**
I found the Windows location used by Quelea to export to the embedded media in a schedule:
C:\Users\<userid>\AppData\Local\Temp
Whenever Quelea closes, these media files are deleted this Local/Temp.

**2.**
The 2020.0 Beta 2 uses this export location as well, just as the 2019.0 (cross platform) release does that we are currently using.

**3.**
I then did the above tests again with the 2019.0 release : the noted OKAY / NOT OKAY behaviour is also present in 2019.0 release.  (so it's not a regression)

Still, although it's not a regression, I think it would be better to correct this: 
The embedded schedule media file, as exported to the Local/Temp folder, should be used when projecting the song with this custom media, not the media file with the same name in c:\Users<user>.quelea\img\ folder or c:\Users<user>.quelea\vid\ folder. Quelea uses the wrong folder when projecting.
Consequence: embedding custom media in a schedule, transporting this schedule to a computer where the embedded media isn't present in the img/vid folders therefore doesn't work correctly now: the custom media isn't shown.

Michael, is this something you can confirm? Shall I make a new issue for this?

**Comment by berry120** [comment]
@DeeTigIT I've split this out into a new issue here - would be good to fix, but I also don't want to hold 2020.0 up over something that isn't a regression at this point, so we'll see. Definitely need to keep track of it however.
