### ISSUE TITLE
Max number of verses per slide not function properly

### ISSUE THREAD

**Issue by eddyg1** [quelea-projection/Quelea#227]
I just try CI Build 613, it seem a feature "Max number of verses per slide" not function properly. When I was tried 1 and off this feature, the Bible verse weren't shown 1 verse per slide.

In 2019.1, this feature work properly
![image](https://user-images.githubusercontent.com/58758941/70588101-461a6700-1bfe-11ea-87f1-b8bf1b840a62.png)

**Comment by DeeTigIT** [comment]
This seems indeed to be a regression bug in the CI 2020.0 release.
I can confirm what eddyg1 stated: in 2019.1 it works as expected.
Both for "Max number of verses per slide" equals 1 and 3.

![S1](https://user-images.githubusercontent.com/39883796/74181736-14e00680-4c42-11ea-8576-b19aa0ccd3ef.JPG)

![S2](https://user-images.githubusercontent.com/39883796/74181740-18738d80-4c42-11ea-8b96-e3b633dab45b.JPG)

**Comment by berry120** [comment]
Should now be fixed in the latest CI release. (Note that you may need to toggle the setting off and on again for this to start working if you've used the CI release already.)
