### ISSUE TITLE
2020.0 CI release : translations missing after importing Quelea Song Pack (.qsp)

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#236]
Songs with multiple translations in a .qsp file are not correctly imported. Seems that only 1 trans is imported for such a song. This appens in both the 2020.0 CI as well as the 2019.0 release.

Testcase: song with 2 trans (EN en NL). After exporting to a .qsp file, both trans are present in the .qsp. But upon importing the .qsp in an empy Quelea db, only the last trans NL in the song xml is actually imported. The first trans EN is gone.

![S1-EN](https://user-images.githubusercontent.com/39883796/72701494-c7dfa780-3b4f-11ea-8909-106079f768c5.JPG)

![S1-NL](https://user-images.githubusercontent.com/39883796/72701500-cd3cf200-3b4f-11ea-8c88-caa73eceebed.JPG)

![S2](https://user-images.githubusercontent.com/39883796/72701508-d1690f80-3b4f-11ea-909a-99d0c8ecac93.JPG)

![S3](https://user-images.githubusercontent.com/39883796/72701513-d75ef080-3b4f-11ea-86d9-602949334112.JPG)

[EXPORT.qsp.zip](https://github.com/quelea-projection/Quelea/files/4084601/EXPORT.qsp.zip)

![S4](https://user-images.githubusercontent.com/39883796/72701581-0bd2ac80-3b50-11ea-9b28-896cb458b439.JPG)

**Comment by berry120** [comment]
Thanks for this! We'll aim to fix before rolling out 2020.0 beta.

**Comment by berry120** [comment]
This

**Comment by berry120** [comment]
Should now be fixed in the CI release.

**Comment by DeeTigIT** [comment]
Yes, it is in 2020.0 Beta 1.
Thanks!
