### ISSUE TITLE
Can you help me to hide the clock from stage view?

### ISSUE THREAD

**Issue by suciuben** [quelea-projection/Quelea#237]
We use stage view for output the bible verses and aongs to a video stream. Can you help as to hide the clock?

**Comment by ArvidNy** [comment]
At the moment, the clock isn't an optional feature on the Stage View. We might reconsider this at some point. One way of getting past it right now would be to use a web browser with Mobile Lyrics instead of the Stage View.

**Comment by berry120** [comment]
I realise this is older so would usually mark the other as a dupe, but let's track this in #329 since it contains more detail.
