### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by MistaWizard** [quelea-projection/Quelea#238]
Greetings, I'm working on a project similar to [https://github.com/anthonyeden/ProPresenter-Lyrics-HTML](url) or [https://github.com/josephdadams/PresentationBridge](url) for Quelea. My initial goal is to make a live lyrics view that can be more easily used for lower third style lyrics in OBS. I plan to expand it to have a stage display that works like the Android app.

Here lies the issue I'm running into. I'm getting a "CORS header ‘Access-Control-Allow-Origin’ missing" error when I try to pull from the lyrics API route. For kicks and giggles I've tried both straight from the html file I'm starting with and with that html file in a Node server. Using http://localhost:1111/lyrics in a web browser behaves like it should and displays the lyrics output. I've looked at the Quelea source code but a Java developer I am not.

I will make a repository for my project this evening. Thank you guys for the hard work.

**Comment by MistaWizard** [comment]
I resolved/worked around the issue. I setup a reverse proxy in my Node server and got it working.

**Comment by berry120** [comment]
Sorry, a bit slow getting to these things at the moment. This isn't a bug in Quelea, but a limitation of how resources can be accessed online - generally speaking, an AJAX, WS request or similar can only be made to the domain it's served from. So anything served from `mydomain.com` can only make requests to `mydomain.com`, not `quelea.org` - this is for security reasons. A CORS header allows this to be bypassed by the domain in question allowing requests to be made from content served from another domain, but it's probably not something we'd look to add to Quelea.

The correct approach is the one you've used - that is to make the request server side (and a proxy is one way to do that.)

**Comment by MistaWizard** [comment]
Here's my repository if anyone is interested in a clearer view of how I worked around it. [https://github.com/MistaWizard/Quelea-On-The-Web](url) It works with Quelea running locally and remotely. It is still a work in progress but I've very nearly got it where I need to be for my initial purpose. The API has made it very easy to get it to a usable state. Thank you for the hard work making Quelea what it is today.
