### ISSUE TITLE
Error in verses

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#239]
It does not show only one verse as configured.
![bug20200](https://user-images.githubusercontent.com/35184132/74096744-a7f92f00-4ad0-11ea-8bab-a397ca75abe0.png)
![bug20201](https://user-images.githubusercontent.com/35184132/74096745-aaf41f80-4ad0-11ea-8b3d-d880b29223d4.png)
![bug20202](https://user-images.githubusercontent.com/35184132/74096748-afb8d380-4ad0-11ea-9bdb-2645ac39860a.png)

**Comment by DeeTigIT** [comment]
I think this is the same issue as:

Max number of verses per slide not function properly #227
