### ISSUE TITLE
Quelea crashes at File Open dialogs (in Linux)

### ISSUE THREAD

**Issue by eugeis** [quelea-projection/Quelea#245]
Hello,

I want to start development of Quelea, Linux Kubuntu 19.10. I am using master branch.

Quelea starts without problems (from InteliJ), but if I click to any button (any operation) which want to open a file dialog then the JVM crashes.

Same problem if I am using the installer JAR from CI, by java -jar ...

I tested with 8.0.232.fx-zulu and 11.0.5.fx-zulu.

See attached log files.

[hs_err_pid31303.log](https://github.com/quelea-projection/Quelea/files/4388549/hs_err_pid31303.log)
[hs_err_pid31872.log](https://github.com/quelea-projection/Quelea/files/4388552/hs_err_pid31872.log)
[hs_err_pid631.log](https://github.com/quelea-projection/Quelea/files/4388553/hs_err_pid631.log)
[hs_err_pid1799.log](https://github.com/quelea-projection/Quelea/files/4388545/hs_err_pid1799.log)

Any ideas?
Thanks.

**Comment by ArvidNy** [comment]
Hi Eugeis,

You might want to take a look at [this comment](https://github.com/quelea-projection/Quelea/issues/17#issuecomment-407561200). You need to add the JVM option `-DVLCJ_INITX=no` when you initiate Quelea on some Linux distributions.

Hope that works for you too!

**Comment by berry120** [comment]
Closing this one off as we haven't heard back. Feel free to reopen if it's still an issue.
