### ISSUE TITLE
Bible passage adding fails if biblename contains a slash (Remote Control)

### ISSUE THREAD

**Issue by ipikles** [quelea-projection/Quelea#249]
I cannot add bible passage with remote controller if book name contains slash ( / )

For example, this is a line from zefania xml bible file
`<XMLBIBLE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zef2005.xsd" biblename="PR33/38" status="v" version="2.0.1.19" type="x-bible" revision="0">`

However, if I change the biblename attribute to "PR33" everything works

Adding (and everything else) works just fine when using Quelea itself, only the remote controller fails to add passage.

Steps to reproduce
1. Click magnifying class icon
2. Choose "Add a bible passage"
3. You will see list of books
4. Select any book
5. You will see list of chapters, verses and so on...
6. Finally, when you click "Add" you'll see error message that adding failed

Notes:
Remote controller is in english and Quelea is in finnish. Error message is also in finnish, so I assume this might also be server related error. At least the error message is directly from the server.

As a workaround I have renamed bible so I can continue to use Remote controller

**Comment by ArvidNy** [comment]
I decided to make a simple workaround and just replace all slashes with ` - ` meaning that the Bible in your example would be called `PR33 - 38` in the remote app. This way I won't have to make any changes to the code for the remote app and I didn't have to make much changes to the Quelea server. However, if you feel like this should be handled differently, let me know and I might reconsider it.
