### ISSUE TITLE
Font Style Underline

### ISSUE THREAD

**Issue by archenians** [quelea-projection/Quelea#25]
What version of Quelea which support Underline style?
I couldn't use Underline style in song

**Comment by berry120** [comment]
Are you wanting to add underline to all the style of the song, or just part of it? If it's just part of it then the bigger issue here is we don't support partial formatting at present; all the song is rendered in the same style.

**Comment by archenians** [comment]
How can add underline to the entire song or some part of it? I had accidentally use italic to some part of song, so could i do the same with underline style?
First, show me how to give underline to the songs' lyrics

**Comment by berry120** [comment]
Underline isn't supported in any capacity at present, but it'd be helpful to know if you want to underline an entire song (which seems like an odd case to me, but there may be a case for it) or just underline / format parts of a song.

**Comment by archenians** [comment]
It will really help if i could use underline style to some part of song. Could you add the underline style to this program?
My church really need this feature so we could worship better.

**Comment by berry120** [comment]
Created https://github.com/quelea-projection/Quelea/issues/25 to deal with partial formatting in general. If we implement partial formatting, then underlining text will be an option there.
