### ISSUE TITLE
Minor usability issues in sequence editor (2020.0 beta)

### ISSUE THREAD

**Issue by ipikles** [quelea-projection/Quelea#251]
I found some minor usability issues while trying new Sequence editor.
Sequence editor is actually really great thing, something I didn't knew I needed! Thanks.

# Labels
These are my personal opinions, discard if you disagree :)

1. Edit button (pen icon) in song editor has a tooltip "Song sequence dialog"
    *  Would it would be better if tooltip shows what button does instead what is behind it?
    * Maybe "Show sequence editor"
2. You can add same section more than once, but description does not mention it. I thought it must be obvious feature and tried it out. It worked.
    * Add hint about that feature to description
    * Like: "Tip: You can add one section (e.g. chorus) more  than once!"

# Quick keys

Allow to delete selected section (in "Chosen sequence order") by pressing DELETE key. Now I have to click X-icon between section lists.

# Bugs

## Editor allows duplicates in a row
Editor allows you to add same section multiple times in a row, but strips instances to only one. For example `V1 V2 C C C V1` becomes actually `V1 V2 C V1`

Consider adding warning about it and clear sequence when it is saved
![Screenshot from 2020-05-02 13-57-20](https://user-images.githubusercontent.com/3070646/80862447-df194f80-8c7d-11ea-89f4-e4719b18092c.png)

Same is true for text input which allows quick edit.

## Sequence order quick edit should be case insensitive
If I write `v1 v2 c v1` to "Song sequence" nothing is shown.
![image](https://user-images.githubusercontent.com/3070646/80862586-dbd29380-8c7e-11ea-8e03-c53a326a763b.png)

This is because correct form is `V1 V2 C V1` and sequencer just ignores all invalid entries. I think user should be allowed to use small letters. But maybe during saving Quelea should call `toUpperCase` or something. (and maybe strip other invalid entries?)

**Comment by ArvidNy** [comment]
Thanks for the feedback! I think all of your suggestions are great and I'll have a look at implementing them soon!

**Comment by ArvidNy** [comment]
I've implemented all your suggestions now, but I chose to allow duplicate entries instead of adding a warning. Perhaps someone might find it useful, e.g. to allow the musicians to know how many times to repeat a section or so.
