### ISSUE TITLE
Looking for the ability to use a video instead of slides for songs,.

### ISSUE THREAD

**Issue by mage1116** [quelea-projection/Quelea#255]
I would like to suggest the ability to use videos instead of slides for songs. It would be nice if there was the ability to have the choice to play the video or slides when you add the song to the service. That way the videos are searchable via name or lyrics just like the songs.

**Comment by DeeTigIT** [comment]
Please check : 
https://quelea-projection.github.io/docs/General_tab#show-video-library-tab-\(requires-restart\)

Show Video Library Tab (requires restart)

The Video Library Tab will appear next to the tabs for songs, bibles, images and timers. You can then **add videos to your schedule the same way you add an image**. This option is known to make the start-up time longer on some system.

**Comment by DeeTigIT** [comment]
Just curious: did you succeed in using video for songs?

**Comment by berry120** [comment]
Closing this one off as we already have this functionality (I wondered if the OP meant something different, but assuming not as we haven't heard from them since June.)
