### ISSUE TITLE
Enable song text lines to begin with words from "section titles"

### ISSUE THREAD

**Issue by sven-dmlr** [quelea-projection/Quelea#259]
I have several cases where a song text line begins with `Tag`.
(It's just the German word for "day")

Example:
```
Bridge
Tag und Nacht unaufhörlich
bist du würdig allen Lobes
```
"Bridge" is recognised correctly as a section title, but also the next line beginning with "Tag".
-> A possibility to "escape" section title key words is needed. (e.g.  `\` or `_`)
  (That escape character when in 1st column should not be displayed of course.)

My current workaround is putting a small character (.) in front.
(In the example: ".Tag und Nacht unaufhörlich". The downside of this workaround is that everybody sees the . and thinks it is a typo...)

**Comment by berry120** [comment]
Have you tried appending "//lyrics" to the end of the line? Not a fantastic workaround, but should work...

**Comment by sven-dmlr** [comment]
Yes. It works.  Thanks a lot!
Did I miss it somewhere in the documentation - or is this just "secret developer knowledge"?
I'd love to see it in the FAQs...

btw.: great work! Keep going!

**Comment by berry120** [comment]
You didn't miss it, but we should document it, so it's now added to this page: https://quelea-projection.github.io/docs/Adding_songs_to_your_database

Thanks for flagging!
