### ISSUE TITLE
SHA256 hash mismatch on CI-RELEASE

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#271]
The CI-release from 4 hours ago seems to have incorrect hashes?

eb47149dc6bab6578b49f0eecb7aa519cc7f12441bb4df0a1ec6b0fc7bef0e9f *quelea-CI-UNSTABLE-mac.zip
752d2504c9a1ca284f24dbbe14f08bd8790c07bc0005d5826a909c67db803bba *quelea-CI-UNSTABLE-x64-windows-install.exe
013acc3f6c1f59739dffe258ff2f1d93800bc73b4cd51ff9ba5f622af4498dee *quelea-CI-UNSTABLE-crossplatform-install.jar

![S1](https://user-images.githubusercontent.com/39883796/87231578-87533f00-c3b8-11ea-9355-ca2b71ab5a4a.JPG)

**Comment by berry120** [comment]
Haven't yet taken a look at this, but it could be a good Hacktoberfest candidate if anyone wants to have a go. We should aim to have this fixe by the next release certainly, as it is a bit misleading otherwise.

**Comment by HeyITGuyFixIt** [comment]
This isn't just mismatched hashes. The description of the CI-RELEASE isn't being updated. Notice that the build number in the image above is the same as today, despite this issue being created 4 months or so ago. Then, it probably should have been build 668, and now it should be 725. Not sure yet why it isn't being updated, but this is what is happening.

**Comment by berry120** [comment]
@HeyITGuyFixIt is correct, it seems like travis silently dropped the ability for their old deployment plugin to write release descriptions, which isn't too helpful. I've migrated to their v2 plugin now (currently beta but seems stable enough) and this does officially support release descriptions, so works as intended.
