### ISSUE TITLE
Editing songs

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#272]
Is there a reason why when I edit a song in a service, those changes aren't saved to the same song in the database? This would be helpful for when I catch an error and need to quickly edit it, so I don't have to go back and edit it again in the database. At the very least, an option in the preferences to toggle this behavior would be nice.

**Comment by DeeTigIT** [comment]
Please check this wiki-item:
https://quelea-projection.github.io/docs/General_tab#copy-song-to-schedule-by_default

**Copy song to schedule by default**

Some users prefer to keep an original version of a song in the database and then edit a copy of that song for each use. This option means that all song that are added to the schedule are temporary copies that will not be stored back to the database. It means that any edits you make to a song in the schedule when this option is activated only will be stored in that schedule, whereas any edits you make to a song in the database also will stored in the database.

**Comment by HeyITGuyFixIt** [comment]
Turning off that options does the trick. Thanks!

**Comment by DeeTigIT** [comment]
@HeyITGuyFixIt 
Is it possible to close this issue? (as no changes are required here)
