### ISSUE TITLE
Poor Preview Image Resolution in Image Group

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#275]
In Image Groups, the image quality/resolution is very poor. The images come from PowerPoint slides exported to JPGs (using default slide sizes and image resolution) and added to Quelea on Linux as an Image Group. What is outputted is fine, no issues there. But the image shown for controlling what's shown has poor quality/resolution, making it difficult to see what is on the image.

Is there a way to make increase the quality of how it's shown in the Preview and Live panes? 

![Screenshot from 2020-09-26 20-11-37](https://user-images.githubusercontent.com/34974905/94352635-a071a080-0035-11eb-8116-b109ad5b6e12.png)

**Comment by HeyITGuyFixIt** [comment]
In addition to quality enhancement, could we also have the option to zoom in?

**Comment by ArvidNy** [comment]
Sounds like you might want to take a look at `Options -> General -> Interface Options -> Thumbnail size`. If you increase that value, you should be able to get a higher image quality.

As for the zoom in feature, feel free to rename this issue and request it as a new feature if you feel it should be possible to do outside of the options dialog.
