### ISSUE TITLE
RFC: add song CCLI number to Database / Export / Song list

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#280]
RFC: add song CCLI number to Database / Export / Song list

Ref:
https://github.com/quelea-projection/Quelea/issues/278

**Comment by berry120** [comment]
Yup, this should be in there ideally. A good one for a hacktoberfest contribution if someone wants to pick it up - it shouldn't be too challenging.

**Comment by joncojonathan** [comment]
Is this the church's CCLI number or the song's CCLI number @DeeTigIT ?

**Comment by berry120** [comment]
I think this will almost certainly be the song's CCLI number.

**Comment by DeeTigIT** [comment]
Michael has right: it’s the song’s CCLI number.

Van: Michael Berry [mailto:notifications@github.com]
Verzonden: vrijdag 23 oktober 2020 11:24
Aan: quelea-projection/Quelea
CC: DeeTigIT; Mention
Onderwerp: Re: [quelea-projection/Quelea] RFC: add song CCLI number to Database / Export / Song list (#280)

I think this will almost certainly be the song's CCLI number.

**Comment by berry120** [comment]
This should now be working in the CI release.
