### ISSUE TITLE
Quelea displays the "Schedule could not be opened" message on Mac when no schedule is being opened

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#285]
When running on a Mac, Quelea sometimes displays the "schedule could not be opened" message even when Quelea is just being launched via the finder (ie. no schedule is being passed.)

This is due to the Mac passing the psn ID as a parameter to Quelea, and Quelea thinks it's the name of a schedule, so tries to open it.

[We already exclude the `--userhome` option for this reason here.](https://github.com/quelea-projection/Quelea/blob/8c541db824ffb370a87e9e821c5635f0addb8c59/Quelea/src/main/java/org/quelea/windows/main/Main.java#L278) We just need to expand this condition to also check for `-psn_` in the parameter, and make sure we don't open a schedule if this is present.

This is a trivial change and would be ideal as a novice Hacktoberfest contribution.

**Comment by joncojonathan** [comment]
I'd be happy to take a look at this @berry120.

**Comment by berry120** [comment]
@joncojonathan I think this should be marked as fixed now, would that make sense? Looks like I may have forgotten to close it.

**Comment by joncojonathan** [comment]
I believe so.  We discussed it back in October and it should be fine.  I don't have a Mac though, so can't test.
