### ISSUE TITLE
Quelea is not translate in French

### ISSUE THREAD

**Issue by LAfricain** [quelea-projection/Quelea#288]
Hi, 
Quelea is not translated in French I can do it.

**Comment by berry120** [comment]
Hey, we already have a French translation here: https://github.com/quelea-projection/Quelea/blob/master/Quelea/languages/fr.lang

If there's any other translations you could contribute to though, or you want to start a new one, that would be fantastic! You can see more details on translations at quelea.org/lang

**Comment by LAfricain** [comment]
But I can't see the locale on Ubuntu 20.04. How to use it?
(Installed with snap)

**Comment by berry120** [comment]
Under tools -> options -> interface options, you should see it there under "Interface language" - if not can you take a screenshot of the options you do see?

**Comment by LAfricain** [comment]
I'm sorry! I didn't see the scroll button!

**Comment by berry120** [comment]
Hah, no worries 😂
