### ISSUE TITLE
Support OSIS XML bible format

### ISSUE THREAD

**Issue by LAfricain** [quelea-projection/Quelea#289]
I use [xiphos](https://github.com/crosswire/xiphos/) as main bible reader software. It's a frontend for sword (all in the debian repo).
I would be very interesting to use the bible installed in xiphos in Quelea. Because I have all my favorite French translation in it. Or maybe a way to use this other bibles.

**Comment by berry120** [comment]
Have you got a link to the bible format they use? I couldn't see one quickly from searching. (I feel like we had an issue opened for this a while ago, but I can't find it now.)

**Comment by LAfricain** [comment]
I think you can't read it directly, you need to use the backend [sword](http://crosswire.org/sword/index.jsp)

**Comment by berry120** [comment]
I think that may be the point we reached last time - at the moment things work on a file level, so unless there's a clear file format and file that we can drop in place to use, the best way of going about this isn't too obvious. I'll make a note of it though and see what can be done (time permitting of course.)

**Comment by LAfricain** [comment]
What kind of file? And where are this files stored ? 

On October 9, 2020 12:42:37 AM GMT+02:00, Michael Berry <notifications@github.com> wrote:
>I think that may be the point we reached last time - at the moment
>things work on a file level, so unless there's a clear file format and
>file that we can drop in place to use, the best way of going about this
>isn't too obvious. I'll make a note of it though and see what can be
>done (time permitting of course.)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/quelea-projection/Quelea/issues/289#issuecomment-705860786

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by berry120** [comment]
Currently Quelea uses bibles stored in zefania XML format, stored in the
bibles folder (in the .Quelea folder in the user home directory). Ideally
you'd just be able to export from sword to a file of some format, we'd drop
those files in the same folder and then tell Quelea to use the new format.

**Comment by LAfricain** [comment]
I just tried to copy an osis file in the .quelea/bibles folder but quelea doesn't see it.

**Comment by berry120** [comment]
It won't see it at the moment, since it doesn't support the OSIS format. (Though sorry, I missed your earlier message about sword using the OSIS file format!)

I'll re-point this issue to track supporting the OSIS format. Given that it's also XML based, it shouldn't be hard. Example file: https://raw.githubusercontent.com/bzerangue/osis-bibles/master/en/acv.xml

**Comment by LAfricain** [comment]
Very good! Thank you. We (Crosswire) try now to propose (when we don't have copyright issue) all the files in osis format on our gitlab:
https://gitlab.com/crosswire-bible-society
You have a lot of possibilities...

**Comment by berry120** [comment]
OSIS XML should now be in the CI release, ready for 2021.0. If you could give it a try and let us know of any issues you come across, that'd be fab!
