### ISSUE TITLE
Option 'Notice position' <> notice.position in quelea.properties file

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#296]
In order to get the notice running at the bottom of the projection screen, the GUI setting needed for this is 'Top'.
This should be reversed.

![S1](https://user-images.githubusercontent.com/39883796/95713169-61169700-0c66-11eb-97d5-c0b086a04249.JPG)

![S3](https://user-images.githubusercontent.com/39883796/95713177-65db4b00-0c66-11eb-853d-69c34168cead.jpg)

![S2](https://user-images.githubusercontent.com/39883796/95713185-696ed200-0c66-11eb-9248-f4d9bdc24b41.JPG)

**Comment by ArvidNy** [comment]
Thanks for letting us know, this should now be resolved.

**Comment by DeeTigIT** [comment]
Great!
