### ISSUE TITLE
Screen Monkey import missing important data

### ISSUE THREAD

**Issue by tuomas2** [quelea-projection/Quelea#300]
Screen Monkey XML format includes song sequence and other structural data about song, that is lost when importing. Also, detailed information is not stored (like <Reference> tag).

**Comment by berry120** [comment]
We can't always guarantee to preserve all data when importing from a particular program I'm afraid - it usually just depends on what sample files we were provided with when we originally wrote the importer. However, if you can attach a sample file here that demonstrates what's missing, then we can look to include that in a future release.)

**Comment by berry120** [comment]
Closing this off as it's stale with no way to fix without a sample file - happy to reopen if someone can provide one that demonstrates the issue
