### ISSUE TITLE
Bible option 'Max number of verses per slide' unexpectedly switched by Quelea

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#302]
When entering the Tools, Options screen and leaving this screen (using button 'OK' or closing the window) the bible option 'Max number of verses per slide' is **reversed by Quelea (not by the user)**.

Example:

- Initial the Bible option 'Max number of verses per slide' is true.

![S1](https://user-images.githubusercontent.com/39883796/96771057-78315380-13e1-11eb-9db4-33ca76990f7f.JPG)

![S2](https://user-images.githubusercontent.com/39883796/96771079-7d8e9e00-13e1-11eb-9cbb-e01e9dec88fc.JPG)

- Starting Quelea, entering the Options, leaving this window (**without doing any changes**) and leaving Quelea does reverse of this switch:

![S3](https://user-images.githubusercontent.com/39883796/96771327-ca727480-13e1-11eb-8d63-b476d004473d.jpg)

![S4](https://user-images.githubusercontent.com/39883796/96771338-ccd4ce80-13e1-11eb-9189-605c1cf527b5.jpg)

- Doing the above step again the options is switched to true again. (this is repeated behaviour)

**Comment by berry120** [comment]
@ArvidNy Is this likely to be related to the new options dialog?

**Comment by ArvidNy** [comment]
Yup, my bad. Sorry about that! It should now be fixed in the latest commit.

**Comment by DeeTigIT** [comment]
It is indeed fixed, thanks.

During the test I encountered:

Bible option 'Max number of verses per slide' <> use.max.bible.chars in quelea.properties file #303

And during an earlier test the similar:

Option 'Notice position' <> notice.position in quelea.properties file #296
