### ISSUE TITLE
Bible option 'Max number of verses per slide' <> use.max.bible.chars in quelea.properties file

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#303]
The bible option 'Max number of verses per slide' seems to be opposite to the 'use.max.bible.chars' value in the quelea.properties file.

Should this be reversed?

![S1](https://user-images.githubusercontent.com/39883796/96920233-3077fe00-14ad-11eb-9f4d-16cbad66e368.JPG)

![S2](https://user-images.githubusercontent.com/39883796/96920257-353cb200-14ad-11eb-8cc2-8870842dc08d.JPG)

**Comment by ArvidNy** [comment]
Thanks for identifying that, I forgot to double-check that before pushing the fix. The problem with updating the options dialog has been that some labels are the opposite to the preference value which has meant the some of the values have had to be reversed (like `Copy song to schedule by default` vs. `default.song.db.update`). I just figured this was one of those.

It should now both work properly and store the right value again.

**Comment by DeeTigIT** [comment]
Nice improvement, thanks!
