### ISSUE TITLE
After changing server settings when trying to start using remote control from iphone Quelea does not start at all

### ISSUE THREAD

**Issue by KaisaL777** [quelea-projection/Quelea#312]
Dec 06, 2020 9:18:44 AM org.quelea.services.languages.LabelGrabber <init>
INFO: Using languages file C:\Program Files\Quelea\languages\gb.lang

Dec 06, 2020 9:18:44 AM org.quelea.services.languages.LabelGrabber <init>
INFO: Setting en-uk locale

Dec 06, 2020 9:18:44 AM org.quelea.windows.main.Main start
INFO: Started, version 2019.0

Dec 06, 2020 9:18:44 AM org.quelea.windows.main.Main start
INFO: OS name: Windows 10

Dec 06, 2020 9:18:44 AM org.quelea.windows.main.Main start
INFO: Using JAVA version 1.8.0_111

Dec 06, 2020 9:18:44 AM org.quelea.windows.main.Main start
INFO: 64-bit: true

Dec 06, 2020 9:18:45 AM org.quelea.windows.multimedia.VLCWindowEmbed lambda$new$2
INFO: Video initialised ok

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\LiberationSans-Bold.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\LiberationSans-BoldItalic.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\LiberationSans-Italic.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\LiberationSans-Regular.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\NotoSans-Bold.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\NotoSans-BoldItalic.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\NotoSans-Italic.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\NotoSans-Regular.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Oxygen-Bold.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Oxygen-BoldItalic.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Oxygen-Italic.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Oxygen.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Roboto-Bold.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Roboto-BoldItalic.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Roboto-Regular.ttf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Vegur-Bold.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font C:\Program Files\Quelea\icons\bundledfonts\Vegur-Regular.otf

Dec 06, 2020 9:18:45 AM org.quelea.services.utils.UserFileChecker checkUserFiles
INFO: Checking user files

Dec 06, 2020 9:18:45 AM org.quelea.windows.main.Main$1 run
INFO: Number of displays: 1

Dec 06, 2020 9:18:45 AM org.quelea.windows.main.Main$1 run
INFO: Mobile lyrics disabled

Dec 06, 2020 9:18:45 AM org.quelea.windows.main.Main$1 run
SEVERE: Uncaught exception during application start-up
java.lang.NumberFormatException: For input string: "192......"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.quelea.services.utils.QueleaProperties.getRemoteControlPort(QueleaProperties.java:1790)
	at org.quelea.windows.main.Main$1.run(Main.java:155)

**Comment by KaisaL777** [comment]
For input string: "192......"   (edited the numbers here = does not show all for security reasons) Was not sure if it was safe

**Comment by ArvidNy** [comment]
It should be safe since it's only used internally on your network. That also seems to be where the issue lies. Does it follow the pattern 192.168.0.1 or does it contain any other characters? You could also take a look at [the preference file](https://quelea-projection.github.io/docs/Moving_copying_settings) and see what port number you've set. There you should also be able to set the remote server to false if you just want Quelea to load again.

**Comment by KaisaL777** [comment]
"192.168.0.1:1112" thats the numbers so there lies the problem. How to fix it?

**Comment by KaisaL777** [comment]
where to pu remote server to false? cant find

**Comment by ArvidNy** [comment]
Did you enter that full number in the port text box? The port number should only be the last part (i.e 1112). Don't remember exactly what the setting is called by heart, but it should be called something like 'use.mobile.rc.server'. You could also change the port number in there in case you've added anything else than '1112'.

**Comment by KaisaL777** [comment]
Awesome! I did it. Thanx. And happy Finnish indempendent day!! Love you all.

**Comment by ArvidNy** [comment]
No worries, glad I could help!
