### ISSUE TITLE
Projection

### ISSUE THREAD

**Issue by Aldo0201** [quelea-projection/Quelea#314]
Once I updated my computer now I cant display from my computer to TV as before. How do i get this to work again?

**Comment by ArvidNy** [comment]
Do you see anything from you computer on your TV? `win + p` is a keyboard shortcut in Windows to select projection mode. For the TV to appear in Quelea as an option, make sure that the screen is extended and not mirrored/cloned on your TV.

**Comment by berry120** [comment]
FYI the Quelea forum (https://quelea.discourse.group/) is probably the best place for technical troubleshooting like this - we usually reserve the git issues for reproducible errors that require development in order to fix.
