### ISSUE TITLE
Touchbar suppor on Mac

### ISSUE THREAD

**Issue by norotaro** [quelea-projection/Quelea#315]
I would like to have options in the touchbar and I am willing to develop that functionality if you are interested.

**Comment by matejkobza** [comment]
+ interested

**Comment by ArvidNy** [comment]
I agree, it would be a nice addition. And if you would be interested in developing it, that would be great! Just create a PR here when you're done and I'll have a look at it. 

Perhaps you'll want to take a look at this library: https://github.com/Thizzer/JTouchBar

**Comment by berry120** [comment]
Sure, this would be a really nice touch! Only thing I'd say is that we should probably decide on what the buttons should be here in advance before you actually start development - what sort of layout were you thinking of?

**Comment by norotaro** [comment]
Initially I want to implement these options:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1774870/102665795-3cf29d00-4164-11eb-8438-29eaef7c2534.png">

I was thinking of copying the functions from this file:
https://github.com/quelea-projection/Quelea/blob/8cb07de3e2df3b29927b01f86babd8c968444cdd/Quelea/src/main/java/org/quelea/windows/main/LivePanel.java

And I was also thinking of using that library https://github.com/Thizzer/JTouchBar

**Comment by berry120** [comment]
Yes, I think that'd be sensible - maybe along with the "Go live" button?

**Comment by berry120** [comment]
Closing this one off now as the newer Macs won't ship with touchbars, so I'm not sure this is something that's worth supporting any longer.
