### ISSUE TITLE
Save function not working within Quick Edit feature (for Songs in the Preview and in the Live mode)

### ISSUE THREAD

**Issue by PRBC-sys** [quelea-projection/Quelea#317]
The Quick Edit feature for Songs in the Preview and in the Live mode won't save the change(s) made. Neither the OK button at the bottom of the pop-up screen nor pressing shift+enter makes any difference. We've tried this on both a Windows 10 PC and a laptop running Windows 7, both are 64 bit versions running Quelea 2020.0. 

![Quick Edit illustration](https://user-images.githubusercontent.com/76144189/102446636-207b2700-3fe3-11eb-8693-aedc9b3a21d8.jpg)

Identification of the "bug" and replacing it with reliable Save functionality is needed.

**Comment by berry120** [comment]
Thanks - we'll take a look and aim to fix this for 2021.0.

**Comment by DeeTigIT** [comment]
Maybe it's an underlaying refresh issue of the preview/live panes?
After doing the Quick Edit, the result is indeed not visible in the preview pane.
BUT: it is visible when editing the song afterwards. (so, there's some saving going on)
See the attached video.

https://user-images.githubusercontent.com/39883796/102898157-631c8380-4469-11eb-9e73-9369fb963c27.mp4

**Comment by PRBC-sys** [comment]
I really appreciate the effort going into this and the related video. I can replicate what is shown on my computer. Hopefully it will not be difficult to go the next step and get the Quick Edit feature to automatically refresh the preview/live panes with the updated saved version.

**Comment by PRBC-sys** [comment]
Sorry, I had no intention of closing this. My error which is related to being new to github and learning how to respond to comments.

**Comment by berry120** [comment]
This should now be fixed in the latest CI release - if you could test and let me know, that'd be fab!
