### ISSUE TITLE
VLC preferences probably not (correctly) used by Quelea

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#319]
I have the suspicion that the embedded VLC, started from within Quelea, doesn't use the VLC preferences. 
Or doesn't use them correctly in some cases.

I've encountered 2 settings where VLC preferences seem to be ignored:

- **Preferred Subtitle Language** 

We've set the VLC preference for this to: Dutch
VLC standalone automatically shows these Dutch subtitles. (for a movie that has a selectable Dutch subtitle)
But running the movie from Quelea (embedded VLC): no Dutch subtitles are shown.
So, this VLC preference is ignored.

- **Video output OpenGL**

For our recent new AMD graphics card, I've set the VLC output preference to : OpenGL video-output
In this way, movie sound on the HDMI connection to the television is stable without drop-outs when using standalone VLC.
But running a movie from Quelea (embedded VLC): sound drop-outs do occur.
So, this VLC preference is probably ignored.

In the VLCWindowEmbed.java source, I noticed some specific VLC switches being used to turn some things 'off':
mediaPlayerFactory = new MediaPlayerFactory("--no-video-title-show", "--mouse-hide-timeout=0", "--no-xlib"); 

Is it possible to extend this to more VLC preferences?
Perhaps add a Quelea property in the quelea.properties file where one can specify one or more "--" VLC settings (concatenated in one string) that Quelea, on-startup, then passes through to VLC?
Or can the above call from Quelea to VLC be modifies such that all the VLC preferences are considered (by the VLC library)?

**Comment by berry120** [comment]
Closing this one off as we're using GStreamer in future.
