### ISSUE TITLE
Add script a option in quelea?

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#320]
https://github.com/kendall1997/BibleConverter

**Comment by berry120** [comment]
Afraid arbitrary scripting isn't something we'll incorporate into Quelea - if someone wants to run a script and has the knowledge to do so safely, then they should have the knowledge to do so outside of Quelea. While it'd be a nice to have in some cases, it's very niche, and could cause more problems with usability than it solves.
