### ISSUE TITLE
Ability to hide the clock on the stage view

### ISSUE THREAD

**Issue by PaulD987** [quelea-projection/Quelea#329]
As mentioned here: [https://quelea.discourse.group/t/stage-view-to-livestream-overlay/490](https://quelea.discourse.group/t/stage-view-to-livestream-overlay/490) it appears that some people are trying to use the stage view as a clean feed to send to OBS etc. It seems like a useful addition to be able to hide the clock on this screen.

This seems like an easy addition to increase flexibility with Quelea.

I was thinking something like this for the config:
![image](https://user-images.githubusercontent.com/73899671/107077764-3dfb8e80-67e5-11eb-970d-febfcec7aca0.png)

The "Show Clock" option would default to true, so anyone migrating wouldn't see anything change, and could then be optionally turned off.

I have the code pretty much ready to go if this would be worth putting in.

**Comment by PaulD987** [comment]
Oops, should have looked first... this is a dup of #237. But will leave open for now as it has more detail about what I was thinking!

**Comment by berry120** [comment]
Sure, this would definitely be a worthwhile addition - happy to review that if you raise the PR 👍

**Comment by PaulD987** [comment]
I presume, based on the translation guide, that I just add the labels to the gb and us language files!

My plan was just to pick up the property in the KeyFrame function in Clock.java and set the visibility of the clock there, rather than adding/removing the clock from the screen. Maybe slightly less efficient as the KeyFrame will still tick every second even when the clock is not visible, but far easier to implement I think. Does that sound reasonable?

**Comment by PaulD987** [comment]
Just seen the README.md in languages folder, so will just update the gb file as indicated there. Please just confirm you are happy with my approach above and I will put a PR in

**Comment by berry120** [comment]
Definitely. That'll be easier and nicer from a code perspective, so I'd
vote for that option.

No need to add to the us file - just GB. US is generated automatically, and
other translations are handled by our army of translators (I'll send around
a plea for missing labels before each release.)
