### ISSUE TITLE
Lyrics on stage display are very small

### ISSUE THREAD

**Issue by PaulD987** [quelea-projection/Quelea#334]
Not sure if this is something I have wrong on my setup, but I can't spot it!

![image](https://user-images.githubusercontent.com/73899671/107483678-50751f80-6b79-11eb-8e0b-c757b1a5e808.png)

Text appears very small on stage display. Fine on the other outputs. Doing this on my development code, but also on 2020.0, so nothing I have changed!

INFO: Started, version 2020.0
INFO: OS name: Mac OS X
INFO: Using JAVA version 1.8.0_192

Doesn't make any difference if I have just a small custom window (640x360) on desktop 1 or a full screen on a different monitor. I am running a Mac with a Retina display on desktop 1 so not sure if that makes any difference.

I'll investigate more when I have a chance!

**Comment by PaulD987** [comment]
I think this is an issue with getUniformFontSize in StageDrawer.java. If it is a BiblePassage that is being shown it does
```                newText = new ArrayList<>();
                for (String str : section.getText(false, false)) {
                    for (String line : str.split("\n")) {
                        newText.add(new LyricLine(line));
                    }
                }
```
Which I don't think is doing what is desired. As far as I can tell, the verses are coming in with no new line characters in them, so it is basically getting a single line in the newText array... I think it is then trying to pick a font size to fit this whole line on the screen in a single line (not quite sure but I think that is what is happening). Later on it is actually getting line wrapped, but only after a very small font size has been chosen. Songs don't do the line wrapping in the same way.

In LyricDrawer (which is used on the main projection screen) it does it as follows...
```
                WrapTextResult result = normalWrapText(font, textArr[0], width, height);
                if (result.getFontSize() < fontSize) {
                    fontSize = result.getFontSize();
                }
```
So, why is it done differently there?

@berry120 do you have any insight into this, why it is calculated differently on the two different displays? Should we just be applying the same logic in LyricDrawer to StageDrawer?

**Comment by berry120** [comment]
It should now be fixed - let me know if it's still a problem. It needs to be calculated differently as the bible passage text has different wrapping rules (it wraps at any word boundary to try to keep the line size consistent where possible, whereas songs try to preserve line boundaries where possible to preserve the song flow.) But you were definitely correct in that the code that was in that block was to blame - it should have been using the same logic that's used for bible passages on the main display :-)
