### ISSUE TITLE
Allow option to add cors headers to lyrics server

### ISSUE THREAD

**Issue by kavishdahekar** [quelea-projection/Quelea#346]
Hi all,

I am currently working on an obs dock that would allow direct access to quelea's projected content.

I am doing this via the http://127.0.0.1:1111/lyrics endpoint.

However, due to cors issues, I need a local proxy to inject appropriate headers.

Can we have an option in the "Server Settings" section that would allow users to set the `Access-Control-Allow-Origin` header value sent by the lyrics server?

**Comment by berry120** [comment]
I'm always a wary of adding CORS headers even as an option, as very few people understand the security implications. That being said, the lyrics server doesn't offer any remote control functionality or expose anything that could really be considered "secret", so it may well be ok in this instance to just do a blanket enable.

Let me consider it; I'll have a think and then report back.

**Comment by kavishdahekar** [comment]
Thanks @berry120. Let me know. I can help with the code as well.

**Comment by berry120** [comment]
Sorry about the long wait! Had a think about it and decided that we'll put this option in the release after 2021.0, which will likely be 2022.0.

Originally I was thinking we could perhaps just open it up to the world by default, but *just in case* anyone puts anything confidential on those slides, we wouldn't really want any old website to be able to launch a client side attack to grab the content. So I think an option is the best way forward, which should be pretty low risk as the chances of someone mis-setting that option *and* someone carrying out an attack on the same client on a niche piece of software are basically zero.

We'll put it in the "server settings" options category, and it'll be in the `quelea.properties` file along with everything else, so your program should be able to read as well as set the option programmatically if that's a route you want to go down to save users setting it in the software themselves.

**Comment by kavishdahekar** [comment]
Wonderful!!! Thanks for considering this 😇 This should hopefully make integrating quelea with other workflows easier.
I'm trying to write a layer that would make controlling quelea from obs possible directly via an obs dock. Currently doing this by sort of scraping the remote lyrics endpoints.
However, the most ideal solution would be quelea exposing an api (protected or open?) that allows other applications to fetch current live slide, read song/bible db and the likes.

**Comment by berry120** [comment]
I don't think we'd go as far as a full API as that'd be a lot of work to spin up and maintain for a reasonably niche use case (if lots of similar apps started coming out the woodwork then we might consider it, but in reality that's probably unlikely.)

However, I have been considering this option which might help? https://github.com/quelea-projection/Quelea/issues/313

**Comment by kavishdahekar** [comment]
Thanks! I added some more thoughts to the live text idea in the other issue.

**Comment by berry120** [comment]
Adding the hacktoberfest labels as this could be a good candidate for anyone looking to pick up a hacktoberfest task.

The option we're looking to add should be in the options panel, under the "Server settings" category, in the "Mobile Lyrics" section, and called "CORS header". It should just take a standard textfield (the user will supply a string here.)

When the field is blank (the default), the current behaviour should be preserved. When a value is set in it, then the corresponding header value should be added to all responses from the mobile lyrics server.

**Comment by avikkundu** [comment]
want to work on it.

**Comment by berry120** [comment]
All yours!

**Comment by berry120** [comment]
I think I must have been in paranoid mode when looking at adding this as an option before - I really don't see any security implications with enabling it, so we'll just enable it across the board from 2022.0 (and in the current CI.)
