### ISSUE TITLE
Make PowerPoint presenter view available on mobile remote

### ISSUE THREAD

**Issue by perfectsoundandvideo** [quelea-projection/Quelea#350]
Make the PowerPoint presenter view available for use on the mobile remote

**Comment by ArvidNy** [comment]
Could you perhaps tell us a bit more about how you want it to work differently from now? You can view the different slides already, but I suppose you're looking for something else?

**Comment by perfectsoundandvideo** [comment]
![image](https://user-images.githubusercontent.com/81268965/112847294-ed7e1000-9074-11eb-91f5-83ed2051754b.png)
This way he can see his notes, next animation, etc. I don't know if that's even possible, but I thought I'd ask
