### ISSUE TITLE
Second Screen doesn't show up correctly

### ISSUE THREAD

**Issue by philbeauchamp** [quelea-projection/Quelea#352]
using 2019 version and all versions prior have no issues having my second monitor as the projection window.  Just installed 2020 and 2021 versions and both have the same behavior of not having the window display properly.  It either places the windows down too far or on the primary monitor.  It also doesn't do it consistently.  Trying to move the window with the custom properties does not work as expected either.  Adding a -Y option to bring the screen up vertically moved the window greatly to the left, not up!

Reinstalling 2019 version restored normal function.

**Comment by berry120** [comment]
Hey, sorry for the delay in replying! This isn't something we've been able to reproduce our end. It'd be good to work out if this is to do with some kind of custom setting, or is more to do with your particular setup. Could you temporarily rename the `C:\users\USERNAME\.quelea` folder to something else, which should reset all the settings / database, then let us know if you still have the issue? (You can restore that folder when you're done to get all your settings, songs etc. back.)

Thanks!
