### ISSUE TITLE
Give option to customize panels

### ISSUE THREAD

**Issue by jcarrots7** [quelea-projection/Quelea#353]
Can you please give the option to close panels such as the song library in order to give more space for the order of service, or the live display in the bottom right hand corner. Also the ability to reorder them i.e. put the order of service below the song library, and finally the option to "pop out" panels into there own separate window. Maybe give the option to customize the toolbars, too.

**Comment by PaulD987** [comment]
Not to answer the full request here, but there is code in now to give the option to be able to resize the preview and live panels independantly. It isn't in an official release, but you can try it out by downloading a [CI release](https://github.com/quelea-projection/Quelea/releases/tag/CI-RELEASE). Not recommended for production use, but you can try it out. That will enable you to resize the live panel to "almost" nothing. There is an option under "Interface Options", "Link preview and live panel dividers" which you will need to turn off to unlink the resize bars

**Comment by berry120** [comment]
The panels don't close, but they can now be resized to nothing (both the library panel and the preview windows) which should help free up space. Beyond that afraid we're not planning to support anything further - popping panels out for instance would be a lot of effort (the JavaFX window manager doesn't support it so it would have to be completely custom) and at the moment at least, it doesn't seem worth the engineering effort.

Happy to reconsider if others would find this useful as well, but will close this for now.
