### ISSUE TITLE
2021 Beta doesn't execute on Mac

### ISSUE THREAD

**Issue by PaulD987** [quelea-projection/Quelea#358]
Hi @berry120 I think something may have gone wrong with the Mac build for the 2021 Beta... it doesn't execute when downloaded... it is missing the execute bit on the app!

```
cd Quelea.app/Contents/MacOS
chmod +x Quelea
```
Is what I had to do to get it to actually execute!

**Comment by berry120** [comment]
Whoops, my bad - should now be fixed. Perils of building everything on a
Windows box...
