### ISSUE TITLE
Error in Matriz Video

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#360]
Quelea 2021 beta

when modifying video colors and casting live
there are no changes

![image](https://user-images.githubusercontent.com/35184132/119281246-99b62000-bbfa-11eb-997b-f23d37b99409.png)

**Comment by berry120** [comment]
We may take a look at this later, but it's very low priority so afraid it won't be for 2021.0.

**Comment by Dazmed707** [comment]
okay, although I use that a lot, it was fine in previous versions, I don't know what happened in 2021.0

**Comment by Dazmed707** [comment]
I'm going to check the beta 2 to see if the problem is solved

**Comment by Dazmed707** [comment]
I have vlc 3.0.16 x64 bits ..
windows 21H1 updated

follow the issue in 2021.0 beta2

**Comment by Dazmed707** [comment]
Add this error for 2022.0 ?

**Comment by berry120** [comment]
Afraid this still isn't something we're able to reproduce - it seems to work ok here.

**Comment by berry120** [comment]
Closing old VLC related issues off as we've switched to GStreamer.
