### ISSUE TITLE
Big Sur icon

### ISSUE THREAD

**Issue by micahlt** [quelea-projection/Quelea#361]
Now that MacOS has updated to Big Sur, there is a need (well, at least a desire) for app icons to match the rounded-square aesthetic.  How difficult would it be to implement a different icon that matches the Mac design guidelines?  
| concept | current |
|----------|------------------|
|<img src="https://user-images.githubusercontent.com/28816297/119591740-cace5600-bd9c-11eb-9b57-95569c15a221.png" width="100" height="100"> | <img src="https://github.com/quelea-projection/Quelea/blob/master/Quelea/icons/logo64.png?raw=true" width="64" height="64">

**Comment by ArvidNy** [comment]
The concept icon looks good to me! What do you think, @berry120? I'd say that it shouldn't be that difficult to add either once we have it in the right format. Would you like to create an `.icns` file for it and create a pull request for it (for instance using [this method](https://stackoverflow.com/a/20703594)) if Michael also thinks it looks good?

**Comment by micahlt** [comment]
I'd be glad to generate some `icns` versions.  I'll do so when I get the chance and then make the PR.  In which directory should they be stored?

**Comment by berry120** [comment]
Sure, looks good to me - I'd be fine with that!

**Comment by ArvidNy** [comment]
Great! It should be placed in the `/icons` folder. My suggestion would be to replace the `mac-logo.icns` file with this, rather than trying to find a solution to identify which MacOS version Quelea is run on when the icon currently is set in Packr when creating the installer and not on runtime.

**Comment by micahlt** [comment]
All right!  I'll make a pull request for this.
