### ISSUE TITLE
Support Beblia bibles

### ISSUE THREAD

**Issue by Barry-Bean** [quelea-projection/Quelea#363]
I have downloaded Afrikaans Bibles from https://www.beblia.com
(https://www.beblia.com/pages/bibleXML.aspx?Language=Ewe&DLang=Ewe&Book=40&Chapter=1)

None of the Bibles however imported correctly to Quelea. The appear as blanc since I cant choose a Bible Book. I tried to edit the files to correspond to the default Bible but then I get an error message "There seems to be a problem with your bible file (ABC.xml), Quelea can't load it."

How can I ad these Bibles to Quelea?

[DB Bible - xml Version.docx](https://github.com/quelea-projection/Quelea/files/6649140/DB.Bible.-.xml.Version.docx)

**Comment by thomasvergouwe** [comment]
I have the same issue with a XML file of a dutch bible.

**Comment by berry120** [comment]
There's two issues here:

 - Not all XML formats are the same - Quelea primarily supports the *Zefania XML* format. The format of the bibles on https://www.beblia.com/pages/bibleXML.aspx?Language=Ewe&DLang=Ewe&Book=40&Chapter=1 doesn't appear to be the Zefania XML format, but the Beblia format.
 - The XML must be well formed. The docx file you've attached is in Zefania format, but is broken - specifically, the closing `biblebook` tag just before the book of Matthew opens is missing a `>` character. If you add that, it imports into Quelea without an issue.

I'll retarget this ticket to support the Beblia format.

I've just added a fix to the CI release to support Beblia formats, so you can give that a try now - it should be working. (If not, please upload the file you're having an issue with here and I'll take a look.) I'm afraid there's nothing we can do about broken XML files - they will just need to be fixed before they work with Quelea. If you upload them here though we may be able to tell you how / why they're broken.

@thomasvergouwe You'll need to link or upload the bible you're having difficulty with here so we can take a look at it - then we should be able to say if it's broken, in an unsupported format, or there's an issue with Quelea. I'd recommend creating a new issue so we can keep track of it separately.

**Comment by Dazmed707** [comment]
fix display error when selecting the complete chapter
cannot display individual verses in xmm versions of bibles and in xml versions of belial

![image](https://user-images.githubusercontent.com/35184132/130065207-0dc65fd7-f187-42e6-a7d5-a3fef4321cd6.png)

**Comment by berry120** [comment]
@Dazmed707 Could you explain a bit about the display error you're seeing there? It all looks ok to me from that screenshot...

**Comment by Dazmed707** [comment]
in options I put that only 1 verse appears at a time

but in the capture there are more

**Comment by berry120** [comment]
@Dazmed707 should now be fixed.

**Comment by Dazmed707** [comment]
all good thanks

Please solve the background video color change thing when creating in theme as the problem photo shows #360

**Comment by Dazmed707** [comment]
Add #360 for 2022.0
