### ISSUE TITLE
Feature Request: Translation activated by default in songs

### ISSUE THREAD

**Issue by DuebelWalter** [quelea-projection/Quelea#366]
It would be great if there was the possibility to activate the translation in songs by default. 
We usually sing bilingual songs and it is very practical if the translation is activated by default.

**Comment by berry120** [comment]
Out of curiosity what would be better for your use case - a global switch for this, or a per-song switch?

**Comment by thomasvergouwe** [comment]
I'm following this thread because I think we have the same situation like DuebelWalter. In our case a global switch would be great. something like: "if there is this translation available, activate by default".

**Comment by DuebelWalter** [comment]
It would be great to have a global switch for translations, because we sing all english songs with translations.

**Comment by berry120** [comment]
Cool, 2021.0 is locked for new features (bugfixes only) but this is implemented in a branch and we should be able to merge for the 2022.0 release.
