### ISSUE TITLE
Playing a video live should uncheck the black / clear / logo buttons

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#374]
When playing a video live, you almost never want "audio only" with the black / clear / logo buttons selected, so we'll plan to uncheck these automatically when the video starts playing. At present you sometimes find yourself having to press these buttons as quickly as you can after the video starts playing, which is annoying & cumbersome.

If this behaviour is *not* desirable for anyone, comment here, and we'll look at putting in an option to disable this behaviour if it could really be an issue for some people.

**Comment by berry120** [comment]
This should also be a pretty good hacktoberfest candidate. No options to change, we're just updating the default behaviour to something much more sane.

**Comment by JatinKumarMahaldar** [comment]
hello @berry120  sir , im very new to open source and have some basic knowledge of java and c++ want to start contribute
sir i follow all these steps but got an error( **NO JDK for module Quelea.Quelea.main**) at last step even dough i have JDK version 16 

**Right-click on that class in the sidebar and click Debug 'Main.main()'**

**Comment by berry120** [comment]
@JatinKumarMahaldar Hey, what IDE are you using? I'll assign this to you for now just to prevent anyone else grabbing it - if you decide not to do it then please let us know so we can unassign it from you and allow someone else to take over.

You should be able to use IntelliJ (you don't need the full edition, community edition is fine) and then run the `org.quelea.windows.main.MainStub` class by clicking this button here:

![Untitled](https://user-images.githubusercontent.com/7595149/135719419-4ee97c2f-e0ca-44b0-a6b8-87c909610f87.png)

Note that Quelea uses Gradle, so you will need the IntelliJ Gradle plugin installed first.

**Comment by JatinKumarMahaldar** [comment]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1a745ce1

Caused by: java.lang.NullPointerException: Cannot read the array length because "<local1>" is null

![image](https://user-images.githubusercontent.com/91683536/135725191-67d83cd0-371f-49ab-8a40-c4f1e4036152.png)

**Comment by JatinKumarMahaldar** [comment]
Sir i installed IntelliJ Gradle plugin 7.2 and Java SE Development Kit 8   , sir after debugging my desktop screen goes totally black only taskbar was visible. what to do .

**Comment by berry120** [comment]
Hey, could you try adding the following VM options to your MainStub configuration?

`--add-exports=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED --add-exports=javafx.base/com.sun.javafx.runtime=ALL-UNNAMED --add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens javafx.controls/javafx.scene.control=ALL-UNNAMED -Dfile.encoding=UTF-8 -Dprism.dirtyopts=false`

**Comment by JatinKumarMahaldar** [comment]
sir if you don't mind can we discuss this issue in some other platform since i m new to this and quite hard for me to understand quelea, i dont want make this page fill with my question .. at the end it will be helpfull for me .

**Comment by berry120** [comment]
@JatinKumarMahaldar Afraid I don't have any other suitable platforms we can discuss in, but more than happy for you to fill this page with questions 👍

**Comment by JatinKumarMahaldar** [comment]
![image](https://user-images.githubusercontent.com/91683536/135746149-3e1404ab-c17d-4f48-be05-35f76ac95cd0.png)
![image](https://user-images.githubusercontent.com/91683536/135746162-290fad7f-36f2-425b-b67b-0b2acbde061c.png)


sir , is there anything wrong please let me know 

![image](https://user-images.githubusercontent.com/91683536/135746237-9f65d0a2-b7f5-4f89-bd1f-31fb93477bab.png)

**Comment by berry120** [comment]
Try selecting `Quelea.main` as the module, rather than just `Quelea`?

**Comment by JatinKumarMahaldar** [comment]
sir i tried  Quelea.main even all the other mode shows same error..

**Comment by berry120** [comment]
Hmm, that's an odd one then. Has Gradle definitely synced & run ok? The fact it can't find the `MainStub` class is a bit odd, as it's definitely there! Can you definitely see the file ok in the source directory after you open the project? And are you definitely opening the inner "Quelea" folder as the gradle project, not the top level folder?

(At the moment we're running with Java 11, not 16, so that's also something you could try - but it shouldn't make too much of a difference.)

**Comment by JatinKumarMahaldar** [comment]
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Oracle Corporation 16.0.1+9-24)
OS:           Windows 10 10.0 amd64

Source diractory ok

Warning: No JDK specified for module 'Quelea.Quelea.main
this is what it says when i choose quelea.main

**Comment by JatinKumarMahaldar** [comment]
At the moment we're running with Java 11, not 16, so that's also something you could try - but it shouldn't make too much of a difference.
sir as per these concern then i have to downlode JDK 11 as well 

sir is that  issue may arrise because of java fx
