### ISSUE TITLE
The Mac installer does not work

### ISSUE THREAD

**Issue by ArvidNy** [quelea-projection/Quelea#380]
I just tried to download the Mac installer but it says that the file is damaged. I've tried the most recent beta and all the releases before that, and I had to go back to 2019.1 to find a working build. Have we changed anything in the Mac build since then that could have broken it?

**Comment by berry120** [comment]
Hmm that's weird - the CI release runs just fine for me on the Mac, but the beta2 one was broken due to a bad executable flag (I've now changed that and it seems to work ok.) Could you try 2021.0 beta 2 again and let me know if you still have an issue?

**Comment by ArvidNy** [comment]
Just gave it another try and neither the beta nor the CI runs on my computer unfortunately. This is what the warning looks like in English:
![](https://cdn.osxdaily.com/wp-content/uploads/2019/02/app-is-damaged-cant-be-opened-trash-mac-error.jpg)

I can't set it to run anyways, unless I manually remove the `com.apple.quarantine` attribute first using `xattr -cr Quelea.app` ([source](https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/)).

I'm still on Catalina, however. Not sure if that matters.

**Comment by berry120** [comment]
Hmm, that's a pain. Could it be related to it being unsigned?

I'm tempted to release 2021 as is, as I would've thought we'd have lots of
people flag this if it were a wider issue, especially since this is the
case since 2019. I'd like to get to the bottom of it however.

**Comment by PaulD987** [comment]
@ArvidNy what do you mean by Mac Installer? Isn't it just a zip file containing the App, that can then be run. I just tried https://github.com/quelea-projection/Quelea/releases/download/CI-RELEASE/quelea-CI-UNSTABLE-mac.zip and it worked fine for me on my Mac with Catalina. You have to go into Settings | Security & Privacy and then General tab to enable it to open the first time, but after that, it seems fine.

**Comment by ArvidNy** [comment]
@PaulD987 good to hear it's working for you, then it's probably not a general issue. I wrote 'installer' in lack of a better word at the moment. Your steps works for me with 2019.1, but not for any of the more recent releases which is what seems strange to me.

@berry120 sure, if it was a common issue more users would have let us know, so we could probably release it anyways. It feels very likely it's an issue related to it being unsigned. From what I understand, the attribute I removed tells the system to ask for permission to run a downloaded file – not sure however if that's still there if it's a signed application.

**Comment by berry120** [comment]
@ArvidNy Are you ok if we close this one, or do you think we should keep it open in case there's anything we can do to track the unsigned issue?

**Comment by ArvidNy** [comment]
Sure, we can close this. I just tried the CI release and that worked as expected (though the 2021.0 release still doesn't work without the previously mentioned workaround). Just noticed though that we have two Mac files in the CI where only one worked for me. Perhaps we should remove the file `quelea-2022.0-mac.zip`?
