### ISSUE TITLE
(CI 2022.0 cross-platform) : default translation not set on song drag-and-drop

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#390]
There are three ways to add a song to the Order of Service: 
- by dragging the song and dropping it in the Order of Service
- by pressing enter on your keyboard
- right-clicking and selecting “Add to schedule”

**If you drag-and-drop the song : the default translation of the song is not set.**
The default translation is : NL
The song in the clip has a NL translation.

![S1](https://user-images.githubusercontent.com/39883796/134963621-9e4c221c-9c77-4645-91d7-b62989a35d87.JPG)

https://user-images.githubusercontent.com/39883796/134964090-de997367-6e51-4fb0-a492-dbdfd54fa485.mp4

I'm using:
- Quelea CI-RELEASE 2022.0 cross-platform
- OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi (Adoptium Eclipse Temurin)

**Comment by berry120** [comment]
Thanks for spotting - hopefully this should now be fixed :-)

**Comment by DeeTigIT** [comment]
Confirmed: on drag-and-drop to the schedule the default translation of the song is set now.
Thanks!
