### ISSUE TITLE
Update PreferencesFX?

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#391]
You can update the improvements and FX preference code to read 2022.0 with FX preference versions 11.8 or higher.
https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/releases

**Comment by berry120** [comment]
Sorry, not sure what you're asking here? We've already updated our preferencesfx version to 11.8...

**Comment by Dazmed707** [comment]
ok
