### ISSUE TITLE
Remove redundant import statements

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#393]
Redundant import statements need to be removed in the following files:

PreferencesDialog.java
QuickEditDialog.java
Schedule.java
SongEntryWindow.java

**Comment by Qiwen-Yu** [comment]
Hi, Can I take this issue? This is my first contribution to a real open source project.

**Comment by berry120** [comment]
All yours! Just comment if you need a hand.

**Comment by berry120** [comment]
Fyi - we don't expect all of these fixed in a single pr, just a few will do if multiple people want to take this on 👍

**Comment by iamHrithikRaj** [comment]
> Fyi - we don't expect all of these fixed in a single pr, just a few will do if multiple people want to take this on 👍

Can i work on this as well?

**Comment by berry120** [comment]
@iamHrithikRaj Sure, I don't see why not. Just pick 10 or so files and comment here saying what ones you're working on so we don't get conflicts 👍

**Comment by berry120** [comment]
@Qiwen-Yu If you could similarly pick 10 or so classes then comment which ones you're planning to take, that'd be fantastic 👍

**Comment by iamHrithikRaj** [comment]
@berry120 I'll be working on following files

SwitchBibleVersionDialog.java
TestPaneDialog.java
Theme.java
ThemePreviewPanel.java
TranslationChoiceDialog.java
TransposeDialog.java
VideoButton.java
VolumeSlider.java
WebDisplayable.java
WebDrawer.java

**Comment by berry120** [comment]
@iamHrithikRaj Thanks!

**Comment by Qiwen-Yu** [comment]
@berry120 I will be working on the following files then:
Clock.java
ColourBackground.java
CreateTimerPanel.java
DesktopApi.java
Dialog.java
EditThemeDialog.java
EditThemeScheduleActionHandler.java
ExitActionHandler.java
ExportMenu.java
FileMenu.java
FontSelectionDialog.java

**Comment by berry120** [comment]
@Qiwen-Yu That's great, thanks!

**Comment by saketmundra** [comment]
Can I work on this for rest of the files...?

**Comment by berry120** [comment]
@saketmundra Not all of them I'm afraid just to give others the chance too, pick around 10 or so and list them here 👍

**Comment by neog5** [comment]
Can I work on the following files?
PPTPresentation.java
PreferencesDialog.java
QuickEditDialog.java
Schedule.java
SchedulePanel.java
ScheduleThemeNode.java
SelectSongsDialog.java
SlideThumbnail.java
SongEntryWindow.java
SpellingDialog.java

**Comment by berry120** [comment]
@saketmundra There's 9 of these left now - so you (or anyone else!) can take all that are left in a single PR  👍

**Comment by Bahukhandi93** [comment]
Hey! Please assign this issue to me if there are still some files left. Thank you!

**Comment by berry120** [comment]
@prakhar-198 thanks!

**Comment by Reghill** [comment]
@berry120 Is there any additional files left to be worked on? I would like to take them if there are any left..

**Comment by Reghill** [comment]
I would like to pick up the following files: 
SlideThumbnail.java
SpellingDialog.java
SelectSongsDialog.java
SchedulePanel.java
ScheduleThemeNode.java

**Comment by Guannan-Shen** [comment]
Can I work on the following files: 

PreferencesDialog.java
QuickEditDialog.java
Schedule.java
SongEntryWindow.java

Thank you!

**Comment by berry120** [comment]
@Guannan-Shen All yours!
