### ISSUE TITLE
Replace anonymous classes with method references

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#394]
The following classes at the following locations all use full anonymous classes that can be changed to use Java 8 style method references.

As an example, the relevant code in `BibleSearchTreeView` currently reads:

    this.setOnMouseClicked(new EventHandler<MouseEvent>() {
        @Override
        public void handle(MouseEvent t) {
            trigger(t);
        }
    });

...and it should simply read:

    this.setOnMouseClicked(this::trigger);

A PR should be raised that covers the 4 cases below:

`BibleSearchTreeView` lines 73-79
`ElevantoImportDialog` lines 87-96
`PlanningCenterOnlineImportDialog` lines 92-99
`Utils` lines 475-480

**Comment by ayushggr** [comment]
Hi! I am participating in Hacktoberfest 2021! I would like to contribute by closing this issue.

**Comment by berry120** [comment]
All yours!
