### ISSUE TITLE
FreeWorshipParser - convert if/else blocks into switch

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#396]
FreeWorshipParser, lines 66-75 has a big chunk of if/else statements. This should be converted into a switch statement instead.

**Comment by vancassa** [comment]
Hi, I can help with this. Would you assign it to me?

**Comment by berry120** [comment]
All yours!

**Comment by gajeet11000** [comment]
Greetings, @berry120
May I take over this issue?

**Comment by berry120** [comment]
@gajeet11000 Not yet I'm afraid - we like to give new contributors at least a week to submit a PR, or confirm they're working on the issue, as it can take some people a while to get to grips with the process if open source contributions are new to them. So in this case, if we haven't heard anything by Thursday then we'll put it back up for grabs again. I'll likely publish a few more "easy" issues a bit later today though so keep your eyes peeled 👍 

@vancassa In the meantime if you could confirm you're still planning to work on this, or ask any questions that you may have that'd be great!

**Comment by gajeet11000** [comment]
My apologies I didn't know that. Even I took a long time on my first contribution, so till then, I'll keep my eyes wide open for those upcoming issues 0_O 

Cheers! :)

**Comment by Lakshay-Pruthi** [comment]
Can you open the issues to everyone so that anyone can work on it.

**Comment by berry120** [comment]
@Lakshay-Pruthi As above, this one is already assigned and in the interest of fairness, we'll provide at least a week for someone to confirm they're working on it or submit a PR before re-assigning it.

**Comment by vancassa** [comment]
Hi @berry120, yes I'm currently working on the issue :)

**Comment by berry120** [comment]
@vancassa thanks very much for confirming!
