### ISSUE TITLE
Fix redundant array creation

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#397]
There's a couple of places in the code where we use redundant array creation - that is using `Arrays.asList(new String[]{"1", "2",`, etc. rather than just `Arrays.asList("1", "1"`, etc.

Those places are:

ChordTransposer, line 57
ElevantoParser, line 141

**Comment by Raunak49** [comment]
hey, i can help you to fix this issue

**Comment by berry120** [comment]
All yours!

**Comment by Raunak49** [comment]
Hey @berry120 , It's my first time contributing to open source so I am facing some problems. If you have some time , can you help me fix them. pls

**Comment by berry120** [comment]
@Raunak49 sure, what questions do you have?

**Comment by Raunak49** [comment]
I think it will be better if we discuss this on a call because there are many small small problems

**Comment by berry120** [comment]
@Raunak49 Sorry, we can't offer calls to help on Hacktoberfest issues - these are designed to be small & clear enough that most developers can pick them up pretty quickly. Very happy to answer any questions here if you still want to list them, otherwise another simpler / smaller project may be easier for you to start contributing 👍

**Comment by tulikavijay** [comment]
Hey @Raunak49 I would like to work on this

**Comment by berry120** [comment]
@tulikavijay Thanks - for future reference, we'd ask that you don't take tasks that are assigned to someone else as they may still be planning to work on them (and this may take a while, especially if they're new to open source development!) Generally if we don't hear anything or there's no progress within a week, we'll clear the assignee and allow others to take it.

@Raunak49 If you still want to work on another "good for beginners" type issue, then let me know and I'll create another one to assign to you.

**Comment by tulikavijay** [comment]
@berry120 thanks for informing I will keep this in mind.
