### ISSUE TITLE
RFC: add song CCLI numbers to order of service PDF

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#4]
We use the CCLI facility 'Online Reporting' to report our songs to CCLI. (Online Reporting has replaced the CCLI CopyReport PC Application in the past) To search a song in Online Reporting, we use the unique CCLI number.
**Request**: add the Quelea song CCLI number to the order of service PDF
In this way the tedious, manual reporting process can be greatly simplified: each order of service PDF can be quickly entered in Online Reporting using the song CCLI numbers in the PDF.

**Comment by berry120** [comment]
Don't see why we wouldn't do this - seems reasonable.

**Comment by berry120** [comment]
Fixed by https://github.com/quelea-projection/Quelea/commit/5ed341ef44bc039eb9974af6107079efd76e2c1b
