### ISSUE TITLE
Remove bible upload code

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#404]
We no longer support uploading bibles for analysis, as we're now pretty confident Quelea supports all the main XML bible types (and this is another piece of infraustructure that we no longer want to maintain.)

As a result, the legacy code & labels should be removed.

This involves:

 - Deleting the `BibleUploader` class
 - Removing the call to the bible uploader class, and associated dialog (lines 149-161 in Bible.java)
 - Removing the labels "bible.load.error.title" and "bible.load.error.question" from all language files (those contained within the "lang" folder.)

**Comment by raernon** [comment]
Please, assign it to me. Thank you!

**Comment by dazzlerkumar** [comment]
You can assign it to me. Thank You

**Comment by berry120** [comment]
@raernon All yours!

@dazzlerkumar Sorry, looks like you were just beaten to this one - there should be enough other issues around for you to take another one though 👍

**Comment by dazzlerkumar** [comment]
@berry120 , it's fine. let me see the issues log.

**Comment by raernon** [comment]
Please check the pull request #407 for solution.
