### ISSUE TITLE
Simplify regex

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#408]
LibraryBiblePanel - line 272 has a regex: `(;|,)`

This should be simplified to `([;,])`. Character groups are easier to read IMHO.

**Comment by gajeet11000** [comment]
May I take this issue?

**Comment by Alireza-Sampour** [comment]
This pattern is also repeated in line 312, you may want to take care of this too.

**Comment by berry120** [comment]
@Alireza-Sampour Well spotted, thanks - lines 312 and 314 should also be simplified as part of this PR in the same way 👍
