### ISSUE TITLE
Replace anonymous types with lambdas

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#409]
There's a bunch of anonymous types in the code (eg. `AddDVDActionHandler.java`, lines 60-65) that could be simplified to lambda expressions instead.

We'll accept multiple PRs against this issue as there's so many possible candidates.

I'll do my best to keep this list updated as people work on this issue - work needs to be done here in the following classes:

```
LineTypeChecker
LivePanel
MainWindow
MultimediaControls
NewTranslationDialog
NoticeDialog
NoticeDrawer
NoticeEntryDialog
NumberSpinner
NumberTextField
OOPresentation
PDFExporter
PdfPanel
PdfPreview
PresentationPanel
PresentationPreview
PreviewPanel
QuickEditDialog
RemoveSongDBActionHandler
ScheduleList
SchedulePanel
ScheduleThemeNode
SelectExportedSongsDialog
SelectImportedSongsDialog
SelectSongsDialog
SongEntryWindow
SpellingDialog
SpellTextArea
StatusPanel
TestPaneDialog
ThemePanel
ThemePreviewPanel
ThemeToolbar
TranslatePanel
TranslateTab
TranslationChoiceDialog
Utils
VLCWindowDirect
VLCWindowEmbed
```

**Comment by a-rokay** [comment]
I'll get started on some

**Comment by berry120** [comment]
@a-rokay If you could note the ones you're doing here so no-one else conflicts, that'd be great.

**Comment by berry120** [comment]
(Just to re-iterate, we can assign multiple people to this issue.)

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120, I want to work on this issue. Can u assign it to me

**Comment by berry120** [comment]
@Devansh-gaur-1611  Sure, just list the classes you want to create a PR for so we can keep track of it if others want to work on this too. (Somewhere between 10-15 classes would be a good number I think.)

**Comment by Devansh-gaur-1611** [comment]
@berry120 ,Thanks for assigning me. I will list the classes in a while and will post it here in half an hour

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120 ,I have made changes in following classes
AddImageActionHandler
AddPdfActionHandler
AddPowerpointActionHandler
AddSongPromptOverlay
BasicSongPanel
BigDecimalSpinner
BigDecimalTextField
BooleanCell
ClearingEventHandler
DisplayPositionSelector
DisplayStage
EditSongDBActionHandler
EditThemeDialog
ExitActionHandler

**Comment by berry120** [comment]
@Devansh-gaur-1611 Thanks! I've removed those from the list, and added a few comments on your PR 👍

**Comment by Devansh-gaur-1611** [comment]
Can I also replace anonymous with lambda in other files too

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120, Can I also replace anonymous with lambda in other files too

**Comment by berry120** [comment]
@Devansh-gaur-1611 Not for the moment I'm afraid, just to give everyone the best chance of taking some of these issues for the first time. If there's still a bunch of stuff to do at the end of October then you're welcome to it then 👍

**Comment by adrian-kong** [comment]
can i do 

ContextMenuListCell
DisplayableListCell
DisplayCanvas
DisplayPreview
ExportPDFScheduleSongsActionHandler
ExportPDFSongActionHandler
FontOptionsDialog
FontSelectionDialog
ImageButton
ImageGroupPanel

**Comment by berry120** [comment]
@adrian-kong All yours!

**Comment by ramisha-anwer** [comment]
Hello @berry120 I would like to make changes to the following 

LibraryImagePanel
LibraryPopupMenu
LibrarySongList
LibrarySongPanel
LibrarySongPreviewCanvas

**Comment by berry120** [comment]
@ramisha-anwer Thanks, please go ahead!

**Comment by ramisha-anwer** [comment]
@berry120 I have made the changes kindly check my PR #466

**Comment by douglaskorgut** [comment]
if any left, I'll be happy to do it :)

**Comment by Reghill** [comment]
Could you please assign this to me? I would like to take up some of the remaining files.

**Comment by berry120** [comment]
@Reghill Sure, post the ones you want to take 🙂

**Comment by Reghill** [comment]
I would like to take 

ImageGroupPreview
ImageListPanel
IntegerTextField
LineTypeChecker
LivePanel

Thanks!
