### ISSUE TITLE
Replace unnecessary Integer.valueOf() with Integer.parseInt()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#411]
LibraryBiblePanel.java (line 267) uses `Integer.valueOf()` to parse a string to a boxed integer. We should instead use `Integer.parseInt()` to convert to a primitive integer which is marginally more efficient (there's no need for boxing here.)

**Comment by Sheep-Hunter** [comment]
Hi Sheep-Hunter here i'll grab that

**Comment by berry120** [comment]
@Sheep-Hunter All yours!

**Comment by Sheep-Hunter** [comment]
Thanks
