### ISSUE TITLE
Remove unnecessary boolean unboxing

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#412]
There's 4 places in the code we're unnecessarily unboxing boolean values (by using `.booleanValue()`) - this has been unnecessary since Java 5, so the `.booleanValue()` method calls can simply be deleted.

The places where this needs sorting are:

 - VLCWindowDirect, line 110
 - NumberTextField, line 85
 - BigDecimalTextField, line 86
 - BibleSearchDialog, line 151

**Comment by iamHrithikRaj** [comment]
is anyone working on this? if not then please assign me i would like to contribute

**Comment by berry120** [comment]
All yours!
