### ISSUE TITLE
Replace manual loop with Collections.removeIf()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#414]
There's two places in the code where we remove all nodes that are instances of `Group` from a canvas:

 - LyricDrawer, lines 230-235
 - StageDrawer, lines 141-146

In both cases we can use Collections.removeIf() to do this in one line instead of removing this group. Figuring out the single line required is left as an exercise to whoever wants to take on this task, but it's exactly the same in both places.

**Comment by subhamgcon** [comment]
Please assign this issue to me @berry120 . Please explain what to add and how to add because I am a complete beginner. Thank you

**Comment by berry120** [comment]
@subhamgcon This is a one liner, but one I'd like the contributor to figure out on their own so may not be best if you're completely new to coding. Do you still want to give it a go, or wait for one that might be a bit easier?

**Comment by subhamgcon** [comment]
I want to give it a go. But please tell me what loop to replace? I know it might sound silly but I am complete beginner. Please tell what loop to replace and assign this issue to me. Thank you

**Comment by berry120** [comment]
All yours! The loops you need to replace are in the issue description - the names of the files and line numbers are what you need.
