### ISSUE TITLE
Use Integer.compare & lambda instead of comparing manually

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#415]
LineTypeChecker, lines 142-154 defines a `TreeMap` with a custom comparator that uses manual integer comparison in its `compare()` method.

This can be replaced with a one liner by using `Integer.compare()` instead, and using a lambda rather than an anonymous type.

**Comment by nmarulo** [comment]
hello, can I try to do it?

**Comment by berry120** [comment]
All yours!
