### ISSUE TITLE
Remove redundant "new File()" creation

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#420]
There's two places in code where we're creating a new `File` object, from a `String`, to pass to a `FileInputStream` - when we should just pass the String instead. They are:

 - PPTPresentation, line 45
 - PPTXPresentation, line 44

**Comment by joannaz** [comment]
Thanks @berry120!!

**Comment by berry120** [comment]
@ashaheed00 - please don't take issues assigned to others - we won't accept PRs unless you've been assigned a specific issue.
