### ISSUE TITLE
Replace manual max calculations with Math.max()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#423]
The following snippets have manual code (using an if statement) to calculate the maximum of two values. They should instead be replaced by calls to `Math.max()`.

 - RCHandler, lines 119-123
 - PresentationPanel, lines 303-307
 - PdfPanel, lines 198-202
 - ImageGroupPanel, lines 197-201

**Comment by nmarulo** [comment]
Hi, I'd like to try it, too.

**Comment by berry120** [comment]
Hey, afraid that we're limiting the "good first issues" to one per contributor, just to share them round a bit - they're very popular! 

You've done great work on this one (https://github.com/quelea-projection/Quelea/issues/415) which is fantastic, but we're trying to keep it fair by sharing the easier issues around.

**Comment by nmarulo** [comment]
ok, sorry, no problem.

**Comment by berry120** [comment]
No worries at all, thanks for the understanding!

**Comment by Astro0mar** [comment]
Did my pull request work out?

**Comment by mihirterna** [comment]
Hi @berry120, I would like to work on this one, can you please assign this one to me?

**Comment by varnaa** [comment]
@berry120  Hey, I would like to work on this issue. Can you assign it to me ? :)

**Comment by berry120** [comment]
@mihirterna was first, so all yours!

**Comment by mihirterna** [comment]
@berry120 Created PR #440 for this issue. Please review. Thanks for opportunity.

**Comment by hackgone** [comment]
Can i work on this issue?

**Comment by berry120** [comment]
@hackgone Afraid this one is already done - keep an eye out as we'll likely paste some more of these good first issues shortly.
