### ISSUE TITLE
Remove "C style" array declarations

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#425]
"C style" array declarations are where the brackets form part of the variable name, not the type. For example:

    char arr[]

...is a C style array declaration, which we don't want. The brackets should instead be on the type, like:

    char[] arr

The following classes contain C style array declarations, and all such instances should be fixed:

AparapiLevenshteinDistance
ElevantoLoginDialog
IntegerTextField
LivePanel
PlanningCenterOnlineParser
RemoteControlServer
Schedule
UnicodeReader
Utils

**Comment by ansavanix** [comment]
Fixed in #429
