### ISSUE TITLE
Remove unnecessary semicolons

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#426]
We have a bunch of unnecessary semicolons in the following classes (each class contains a single instance of an unnecessary semicolon):

ElevantoImportDialog, line 217
ElevantoPlanDialog, line 278
ImageDisplayable, line 89
LivePanel, line 636
OOPresentation, line 428
PlanningCenterOnlineImportDialog, line 219
PlanningCenterOnlinePlanDialog, line 390
VideoButton, line 137

For example, in VideoButton, we have:

        try (FileChannel fin = new FileInputStream(in).getChannel();
                FileChannel fout = new FileOutputStream(out).getChannel();) {

...and that last semi-colon there is unnecessary and should be removed. Please make sure the project still compiles & runs ok after making these changes to ensure you've removed the right ones!

(All in one PR please, we won't assign multiple people to this one.)

**Comment by iamHrithikRaj** [comment]
I'd love to be assigned on this one. :)

**Comment by iamHrithikRaj** [comment]
I'd love to be assigned on this one. :)

**Comment by berry120** [comment]
@iamHrithikRaj Afraid we're trying to limit the "good first issues" to one per person at the moment since they're so popular and to give everyone the fairest chance of contributing - hope you understand!

**Comment by sann3** [comment]
I like to try this one, can you assign it to me ?

**Comment by berry120** [comment]
All yours!
