### ISSUE TITLE
Use String.repeat()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#428]
Since we've now moved to Java 11 as a base, there's two places where we can remove loops by using `String.repeat()`:

LineTypeChecker, lines 148-150
Clock, lines 99-101

In both these cases, the use of `String.repeat()` also means we no longer need the `StringBuilder`. Similarly  to other issues, finding the correct call to `String.repeat()` is left as an exercise for the contributor.

**Comment by iamHrithikRaj** [comment]
I'd love to be assigned on this one. :)

**Comment by rustyxlol** [comment]
Hi! Can I do this?

**Comment by rushikeshadhav** [comment]
Hey can i take this up ?

**Comment by varnaa** [comment]
@berry120 Hi, I'd like to work on this issue.

**Comment by berry120** [comment]
@rustyxlol was first, so all yours 👍

**Comment by PrabhuRaamDev** [comment]
hi I'm good at java. I can solve this issue. Can you assign me this issue?

**Comment by berry120** [comment]
@PrabhuRaamDev Afraid this one is already assigned, there should be some other issues up for grabs at the moment though!
