### ISSUE TITLE
Issue with new theme improvements

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#43]
**Here's a testcase on the default global song/bible themes.**

Settings:
- Allow custom item themes to override global theme : OFF
- Global theme: default song theme : DEFAULT THEME, default bible theme: DEFAULT THEME

Schedule (1 song item has custom theme, 1 bible item with custom theme):

![s1](https://user-images.githubusercontent.com/39883796/45584130-d3bdb880-b8ce-11e8-8a1f-629c2befd065.JPG)

I changed the default song theme : BLUE IMAGE.
(I didn't make a change in the default bible theme)

![s2](https://user-images.githubusercontent.com/39883796/45584188-a1f92180-b8cf-11e8-99d2-bedb3f1ba204.JPG)

After this change in the default song theme all schedule items, not only the song items **but also the bible item,** are projected with the new default song theme:

![s3](https://user-images.githubusercontent.com/39883796/45584202-d66cdd80-b8cf-11e8-9d76-8431acc537f9.JPG)

For the bible item I didn't expect that, as the default bible theme is still on: DEFAULT THEME
Is this intended behaviour?

_Originally posted by @DeeTigIT in https://github.com/quelea-projection/Quelea/issues/6#issuecomment-421540836_

**Comment by berry120** [comment]
@DeeTigIT - I've moved this out into a separate issue so I don't lose track of it (I hadn't actually seen it before now!) Will take a look.

**Comment by DeeTigIT** [comment]
Thanks. I wasn’t sure then if I should open a new issue or not.

Van: Michael Berry [mailto:notifications@github.com]
Verzonden: zondag 23 september 2018 17:40
Aan: quelea-projection/Quelea
CC: DeeTigIT; Mention
Onderwerp: Re: [quelea-projection/Quelea] Issue with new theme improvements (#43)


@DeeTigIT<https://github.com/DeeTigIT> - I've moved this out into a separate issue so I don't lose track of it (I hadn't actually seen it before now!) Will take a look.

**Comment by berry120** [comment]
Good spot - should now be fixed.

**Comment by DeeTigIT** [comment]
Confirmed, it is fixed. Thanks!

[theme improvements (#43) - test results.docx](https://github.com/quelea-projection/Quelea/files/2422528/theme.improvements.43.-.test.results.docx)
