### ISSUE TITLE
Remove generic arguments that can be inferred

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#436]
The following locations contain generic arguments that can be explicitly inferred by the compiler, and thus can be removed:

 - DisplayGroup, line 153
 - LibrarySongList, line 180
 - ProPresenterPanel, line 74
 - ScheduleList, line 221

**Comment by radiantly** [comment]
Hi, could I take a go at this issue?

**Comment by berry120** [comment]
All yours!

**Comment by berry120** [comment]
@ashaheed00 Once again, please **do not** open pull requests for issues you haven't been assigned, *especially* those labelled as good first issues. If you want to take one of these on, please comment on an unassigned or available issue and say so, and then wait to be assigned.

I realise not everyone may be familiar with the process or etiquette, but this is now the second time we've had to ask after you did the same thing here (https://github.com/quelea-projection/Quelea/issues/420).

Final warning here I'm afraid - we're already swamped dealing with tickets as it is, we don't have the time to pick through who is or isn't meant to be making PRs.

**Comment by ashaheed00** [comment]
@berry120  I apologize for the inconvenience. I was not aware of the process. Thanks.
