### ISSUE TITLE
Replace deprecated Json method usage

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#438]
VideoPsalmParser, line 59 contains deprecated use of `JsonParser`. We should use the static (non-deprecated) equivalent instead, which is `JsonParser.parseString`.

**Comment by jmakhack** [comment]
I can pick this one up @berry120

**Comment by berry120** [comment]
@jmakhack afraid we're limiting the good first issues to one per contributor for hacktoberfest, just to ensure as many people as possible can contribute. Thanks for the offer though!

**Comment by jmakhack** [comment]
ok sounds good

**Comment by mslowiak** [comment]
@berry120 Can I pick this up?

**Comment by lukehayes** [comment]
I would love to help out with this, let me know if you need help.

**Comment by berry120** [comment]
@mslowiak All yours!

@lukehayes Sorry, just pipped to the post on this one I'm afraid - I'll sort some other issues out a bit later on though 👍

**Comment by lukehayes** [comment]
@berry120 Not to worry, I'll keep an eye out :+1:
