### ISSUE TITLE
Remove unnecessary parameters from substring calls

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#443]
`substring()` calls in Java take 1 or 2 parameters - if it takes 1 parameter it just cuts off the given number of characters from the start of the string, if it takes two parameters then it also gives an (exclusive) end position of the string. There's some cases where we're just supplying `str.length()` as the second parameter, which is useless - we should just use the initial one parameter version.

These cases are:

 - ChordTransposer, lines 113, 117
 - PlainTextParser, line 118
 - SoFParser, lines 94, 109
 - WordDrawer, line 251

**Comment by Harshgupta5901** [comment]
hey @berry120 pls assign me this issue 
I will fix it asap

**Comment by berry120** [comment]
All yours!

**Comment by Harshgupta5901** [comment]
pls check #448 thank you
