### ISSUE TITLE
Use equalsIgnoreCase() instead of toLowerCase().equals()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#444]
There's some places where we're using `toLowerCase().equals()` to check for a case insensitive equality, whereas we could (and should) be using `equalsIgnoreCase()` instead.

These are:

 - LyricDrawer, lines 202, 202, 208, 215, 216, 222
 - Utils, line 324

**Comment by a-developer-named-mark** [comment]
Hi can I take this?

**Comment by berry120** [comment]
All yours!
