### ISSUE TITLE
Remove redundant empty string parameter

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#445]
LibraryBiblePanel, line 266 has an empty string passed to the constructor of `StringBuilder`. This empty string is useless and should be removed.

**Comment by thevibhu** [comment]
Can I take up this issue?

**Comment by berry120** [comment]
All yours!

**Comment by thevibhu** [comment]
@berry120 could you please review this PR https://github.com/quelea-projection/Quelea/pull/455 ?
