### ISSUE TITLE
Enable desktop open file handler in Main

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#457]
In Main.java, we left some code in place to register the open file handler - but this is commented out as it was Java 9+ only, and we were using Java 8 at the time. Now we're using Java 11 it should be uncommented and left in place (the relevant lines are 287-302.)

As well as uncommenting this code:
 - The "Only supported in Java 9+" comment should be removed
 - The relevant imports should be added
 - The anonymous `OpenFilesHandler()` call should be replaced with a lambda
 - Since this is technically a new feature, an entry should be added to `changelogs/changelog-2022.0.txt` saying "Register global open file handler" or similar.

**Comment by gajeet11000** [comment]
May I work on this one?

**Comment by berry120** [comment]
@gajeet11000 Sorry, we're limiting the good first issues to one per contributor at present.

**Comment by ashaheed00** [comment]
Hi, can I take this one up?

**Comment by berry120** [comment]
@ashaheed00 all yours!
