### ISSUE TITLE
Remove redundant private modifier for enum constructors

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#458]
The `private` visibility is implicit for enum constructors, so we don't need to specify it. It should be removed from the following places:

 - NoticeDrawer, line 53
 - DisplayCanvas, line 82
 - VersionType, line 16

**Comment by Caresle** [comment]
Hi, I think i can do this, can i take this issue?

**Comment by berry120** [comment]
All good this time as no-one else grabbed it, but in general best to wait until we've confirmed you're assigned to the issue before raising the PR 👍
