### ISSUE TITLE
Remove redundant public modifier for interface members

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#459]
All members (inner classes, methods) of an interface are implicitly public, there's no need for us to specify the `public` visibility modifier. It should thus be removed from:

 - SearchIndex, line 33
 - ScheduleThemeNode, line 62

**Comment by izzy-el** [comment]
Hey! I'd like to contribute! Can I take this issue?

**Comment by berry120** [comment]
@izzy-el all yours!
