### ISSUE TITLE
Use `Map.of()` in ProPresenterParser constructor

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#462]
At present, in the `ProPresenterParser` constructor (lines 64-69) we're creating a map manually, putting the required key value pairs in it, and then assigning the field to be an unmodifiable version of that map.

In Java 9+, this can all be collapsed into a single statement using `Map.of()`, which is what we should do here. (In terms of formatting, can each map entry please be on a separate line for ease of reading - thanks!)

**Comment by Monica-Chhabria** [comment]
can you please assign this to me

**Comment by berry120** [comment]
All yours!

**Comment by Monica-Chhabria** [comment]
Working on it .Will submit PR tomorrow

**Comment by Monica-Chhabria** [comment]
submitted pr
