### ISSUE TITLE
Replace magic constant on CreateTimerPanel

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#479]
CreateTimerPanel, line 318 uses `0` as a magic constant instead of referencing `Calendar.AM`, which is much less readable and more error prone. Should change to using `Calendar.AM` instead.

**Comment by saurabh042** [comment]
Sure, no problem.

Cheers

**Comment by jthuynh** [comment]
Can I work on this?

**Comment by berry120** [comment]
@jthuynh Sure!
