### ISSUE TITLE
Content display update issue

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#492]
Preview pane doesn't refresh after previewing some database songs and returning tot order of service song.

Reference : https://quelea.discourse.group/t/content-display-update-issue/710

I have version 2021.0 installed on Windows 10 pro.
I don’t quit know what to call this so I will attempt to describe it.
Here is the problem.
-     Load something(Item 1) in order of service.
-     click on one of the items to display it in Preview and send it to Live.
-     select a song - it displays in preview - send it to Live.
-     click again on the item you selected in 1 above - nothing happens - no displayed in preview.

You must then select something else in Order of service and then come back to the item1.

Thanks
John

Using the option:
![S3](https://user-images.githubusercontent.com/39883796/136696976-e638bc92-7312-4255-8f55-d53af1f81bde.jpg)
When returning to the schedule song (by clicking on it), after previewing some database songs, the preview pane doen’t refresh:
![S2](https://user-images.githubusercontent.com/39883796/136696991-3fb77930-b427-4b64-a866-254b14936c86.JPG)

But using (as a work-around):
![S4](https://user-images.githubusercontent.com/39883796/136697085-37234358-cf44-4b8d-b9f9-9af717356612.JPG)
The preview pane still displays the schedule song:
![S1](https://user-images.githubusercontent.com/39883796/136697106-33da11bd-2439-461f-ad55-3b2a72a2c385.JPG)

**Comment by berry120** [comment]
Should now be fixed 👍
