### ISSUE TITLE
Updated splash screens for 2022.0?

### ISSUE THREAD

**Issue by micahlt** [quelea-projection/Quelea#500]
The current splash screens for Quelea [(default)](https://github.com/quelea-projection/Quelea/blob/master/Quelea/icons/splash-bare.png?raw=true) are a little bit outdated and could at very least be polished up to look more modern and fit Quelea's interface better.  @berry120 and @ArvidNy, would you guys be interested if I submitted a new (but similar) concept for the splash screens?

**Comment by micahlt** [comment]
All right, here are those more radical concepts I was talking about.  I'm honestly not a giant fan of all of them, but I think some are pretty decent.  Any positive or negative feedback is appreciated 😊

![Quelea-concept-1](https://user-images.githubusercontent.com/28816297/139940076-d11c0ca8-28d7-4050-95ea-f019826fc712.png)
![Quelea-concept-3](https://user-images.githubusercontent.com/28816297/139940507-04343c2c-6f7f-4eb5-9504-4fae1f51c367.png)
![Quelea-concept-2](https://user-images.githubusercontent.com/28816297/139940509-6977e37c-a74d-45b4-9bee-8c9a7de9e253.png)
![Quelea-concept-4](https://user-images.githubusercontent.com/28816297/139940757-a4ed81c3-abca-45fb-903e-0eb86852b14a.png)
![Quelea-concept-5](https://user-images.githubusercontent.com/28816297/139942271-2ceeefc3-9b49-4f44-96af-fe0aabe6d7cd.png)
![Quelea-concept-6](https://user-images.githubusercontent.com/28816297/139942270-33ac53de-91eb-4406-b4b0-f61d2fc66b37.png)

**Comment by berry120** [comment]
Very nice! I think either the first or third one is my favourite - not sure if that lines up with your opinions or not?

**Comment by micahlt** [comment]
> Very nice! I think either the first or third one is my favourite - not sure if that lines up with your opinions or not?

The first one is definitely my favorite - it maintains the Quelea identity with the feather but is a lot more modern.  The third is also high on my list, but it's a little too generic in my opinion.

**Comment by berry120** [comment]
Yup, I think that's my reaction too. Nice to have the feather there as a bit of a Quelea-esque touch :)

**Comment by micahlt** [comment]
> Yup, I think that's my reaction too. Nice to have the feather there as a bit of a Quelea-esque touch :) 

Sure!  Always good to have that brand differentiation, even in a FOSS project 🙂  So do you think it's worth me making a PR at this point?

**Comment by berry120** [comment]
> > Yup, I think that's my reaction too. Nice to have the feather there as a bit of a Quelea-esque touch :)
> 
> Sure! Always good to have that brand differentiation, even in a FOSS project 🙂 So do you think it's worth me making a PR at this point?

Sure, sounds good - could you produce similar beta / nightly splash screens as well based on that first design so we have them all in sync?

**Comment by micahlt** [comment]
> Sure, sounds good - could you produce similar beta / nightly splash screens as well based on that first design so we have them all in sync?

Definitely!  I'm currently at a cabin where I have no WiFi, but I'll have a PR ready by next week.

**Comment by Dazmed707** [comment]
interesting, it would be good a new presentation and support for macOS monterrey and the new windows 11 with icons that adapt to the new systems to read 2022.0

**Comment by berry120** [comment]
@micahlt Hey, just checking you're still ok to get these splash screens to us at some point? No rush, but I'm planning on hopefully rolling out a beta release of 2022.0 reasonably soon, so if we could get them in there for that it'd be fantastic!

**Comment by micahlt** [comment]
> @micahlt Hey, just checking you're still ok to get these splash screens to us at some point? No rush, but I'm planning on hopefully rolling out a beta release of 2022.0 reasonably soon, so if we could get them in there for that it'd be fantastic!

Yes!  The reason for the delay is that the source file is on my work PC and I keep forgetting to transfer it to my personal PC.  I should be able to do so on Tuesday and have a PR in very soon!

**Comment by berry120** [comment]
@micahlt No worries, thanks very much for the heads up! 👍

**Comment by micahlt** [comment]
@berry120 The PR has been made (#518) 🎉
