### ISSUE TITLE
Support for windows 11? 

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#516]
quelea 2022 works fine on windows 11?

**Comment by berry120** [comment]
Should do, but not something we've tested. Are you having an issue with Windows 11?

**Comment by Dazmed707** [comment]
In options, the ok button does not appear to save changes

the menu must be maximized to full screen for the button to appear

sometime i will try 2022.0

That problem is in 2021.0

**Comment by berry120** [comment]
Can you attach the debug log? That may help us to work out what's failing.
