### ISSUE TITLE
Schedule with Revelations won't reopen

### ISSUE THREAD

**Issue by Youngwily** [quelea-projection/Quelea#517]
If a schedule is created and saved, and it contains any verses from Revelation, then the Schedule wont reopen. Does not seem to affect any other Bible books
using version 2021.0

**Comment by DeeTigIT** [comment]
Here's a sample schedule (packed in  a zip) with a song followed by a revelation verse.
Upon opening the schedule nothing is shown in Quelea.

![schedule content](https://user-images.githubusercontent.com/39883796/142771541-0be65d88-4bcc-49df-b0ff-8d491449a2b5.JPG)

[NIV test.zip](https://github.com/quelea-projection/Quelea/files/7576674/NIV.test.zip)

**Comment by berry120** [comment]
Sorry, mixed the messages up but should now be fixed in https://github.com/quelea-projection/Quelea/commit/ce2003fc88171fb6f79a01a56a64bebc6a85c1ff
