### ISSUE TITLE
Resize presetations .pptx and .pdf

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#523]
Quelea Could you improve the presentation part?
that power point slides can be previewed in a larger size... please and thank

**Comment by HeyITGuyFixIt** [comment]
Have you tried adjusting the thumbnail size in Options?

**Comment by Dazmed707** [comment]
I'm going to try that, do you have a screenshot of the specific option that needs to be moved?

**Comment by HeyITGuyFixIt** [comment]
I don't at the moment. Here's the link to the documentation: https://quelea-projection.github.io/docs/General_tab

It's under "Thumbnail size"

**Comment by Dazmed707** [comment]
"Thumbnail size" found.
Thanks.
