### ISSUE TITLE
Disable preview pane?

### ISSUE THREAD

**Issue by dtpartridge** [quelea-projection/Quelea#528]
Is it possible to disable the preview pane and just have the order of service/database pane, and the live pane?

This is possible in some other systems (e.g. OpenLP) and makes things simple for basic users.  By using the preview pane there is an extra step required to make something live - select the song in the order of service, press Go Live in the preview pane, then change the screen from black etc. to live.  If there was no preview pane it would be possible to select the song in the order of service and then simply change the screen from black etc. to live without needing to press Go Live.

In situations where you need to quickly go live with a new song this can save a couple of seconds, and also makes the user interface less cluttered.

We're currently a church that uses OpenLP but Quelea looks really good and I'm just trying to ensure the transition will be simple and smooth for our users.  Thanks for all you do!

**Comment by berry120** [comment]
Afraid this isn't something that's possible at the moment - we might consider it in the future but afraid it's not likely to be a high priority. The space key can be used as a shortcut to go live if that's any help - saves a couple of seconds, but it obviously won't remove the preview pane entirely.

**Comment by dtpartridge** [comment]
Ok, thanks for letting me know!

**Comment by JessyJP** [comment]
> Afraid this isn't something that's possible at the moment - we might consider it in the future but afraid it's not likely to be a high priority. The space key can be used as a shortcut to go live if that's any help - saves a couple of seconds, but it obviously won't remove the preview pane entirely.

I haven't look at the relevant parts of the code but could we have a simple binary switch in the properties file that will effectively unidirectionally sync the live panel to the previewpanel effectively calling go live upon after every callback to the preview. 
I assume that would be quite easy.
Then later we could add a hide visibility switch for the preview pannel. Effectively operates as normal but is not visible. (It sure is not efficient but I propose to just do it as a quick bypass).
If the preview window for any reason acquired focus then bypass will immediately send it to live view on every update/iteration/callback of the preview window.
