### ISSUE TITLE
Option to black only main display

### ISSUE THREAD

**Issue by ricardomvalverde** [quelea-projection/Quelea#532]
I couldn't find an option to black main display without affecting stage display.
It is important aon several situations where you would like to display information about the liturgy to worship members that aren't relevant to others members in the church.
I suggest to create an option at general -> user options to make independant the black function. On my scenario, stage display can never be blacked, as it is not visible to the church.

**Comment by HeyITGuyFixIt** [comment]
It would be useful to have separate controls for each screen, similar to ProPresenter. ProPresenter doesn't have the option to black out the stage screen, but it does have separate buttons for toggling the visibility of the stage screen and of the audience screen. The black out button in ProPresenter only affects the audience screen, if I remember correctly.

**Comment by jbubik** [comment]
@ricardomvalverde: maybe in Quelea 2022.0 you can already achieve the desired action. Configure Options in `Stage View` the setting `Clear Stage View with Main Display` to OFF. Use `Black screen (F6)` to black all displays, use `Clear screen (F7)` to clear all but the Stage screen. It works in our setup where the main Theme is basically a black screen without any texts or graphics. In our setup F6 and F7 has the same result on Main screen.

@berry120: please consider adding a new setting in `Stage View` named `Black Stage View with Main Display` defaulting to ON (not to break the current behavior).

**Comment by berry120** [comment]
@jbubik Done 👍
