### ISSUE TITLE
Web page display doesn't allow any no "file" urls

### ISSUE THREAD

**Issue by chris-j-major** [quelea-projection/Quelea#537]
Most web browsers accept local content using the [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme), which
can be useful for showing local content as if it were web content.

In a church content this could be used to create a local HTML file for a welcome screen, that uses javascript to reflect the current date (and avoids the need of setting up and maintain a local web server. Furthermore it will remove confusion for urls that work in a web browser, but don't in Quelea.

However the code in quelea checks to see if a url begins with "http" and appends it if not, resulting in corruption of the url.

I've test a 'quick' implementation by removing these checks and everything appears to work, so I don't think it's technically a problem - the main challenge will be ensuring user safety. To support this I suggest moving the three current checks for `.startsWith("http")` to a common helper function, and introducing a more robust URL validation and sanitisation approach.

**Comment by berry120** [comment]
Yup, definitely happy with this in principle, the current limitation was likely just a quick approach without considering file URIs 👍

**Comment by chris-j-major** [comment]
I've opened a PR - lmk what you think
