### ISSUE TITLE
Slow database update

### ISSUE THREAD

**Issue by tallbacksmannen** [quelea-projection/Quelea#545]
I have a quick computer but when i try to edit multiple songs in a quick pase this happens.

![Untitled drawing (6)](https://user-images.githubusercontent.com/89482190/162610951-9441cf87-58ca-40ed-9cb3-60c969cfc464.png)

I waited for more than 30 minutes without any of the updates to finnish. 

Here is the debug log:
[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/8458628/quelea-debuglog.txt)

**Comment by berry120** [comment]
Hmm nothing jumping out in that debug log I'm afraid, but it should update in seconds not minutes so something definitely must have hung there.

Are the songs actually updated? Wondering if it's a database issue or just a display issue with those panes at the bottom.

**Comment by berry120** [comment]
Feel free to reopen with more details if this is still an issue. (Support is generally better handled on https://quelea.discourse.group/ though.)
