### ISSUE TITLE
Database import from EasySlides

### ISSUE THREAD

**Issue by mr-aleks** [quelea-projection/Quelea#546]
Doesn't import our databases from EasySlides. I see an error in the debug file.

> Apr 26, 2022 9:21:44 PM org.quelea.services.importexport.EasySlidesParser getSongs
WARNING: Something went wrong importing easyslides songs
org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 20; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.quelea.services.importexport.EasySlidesParser.getSongs(EasySlidesParser.java:57)
	at org.quelea.services.importexport.ImportDialog$1.run(ImportDialog.java:201)

I would really like to try to use this program, but without our songs it is impossible. Help me please. I will leave the links below for the song base files. 
Song database with Easislides 4.0.5 https://drive.google.com/file/d/1gUEFSFKwYUmTj3BefgG3Eskudq6d2yyM/view?usp=sharing
Song database with Easyslides 5.0.1 https://drive.google.com/file/d/1Srct5dnztoZxkng3vKsSsLuBLwa6WtDB/view?usp=sharing

**Comment by DeeTigIT** [comment]
Is your xml-export ok? If I open Export_2022-04-23_Наши-Песни.xml in Notepad++ v7.8.7 (with XMLTools 3.1.1.13 plugin) and perform a xml syntax check an error is given.

Importing this Export_2022-04-23_Наши-Песни.xml in an empty Quelea database with the just released Quelea 2022.0 cross-paltform fails.

After brute-force manually editing this file (until it's error free in Notepad) it can be imported in Quelea:

**Original file**
![S1](https://user-images.githubusercontent.com/39883796/166110462-a17bd214-5543-4c29-b4d9-c3b9dd77f921.JPG)

![S2](https://user-images.githubusercontent.com/39883796/166110472-e614339d-83dd-4a65-9742-b9739fd2b0cd.JPG)

[Fatal Error] :8:20: Character reference "&#x0" is an invalid XML character.
2022-04-30T16:27:13.584+0200  WARNING  Something went wrong importing easyslides songs
org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 20; Character reference "&#x0" is an invalid XML character.

**Edited file**
![S3](https://user-images.githubusercontent.com/39883796/166110475-8eb16ebd-699d-421d-a8f3-ac4748d2488b.jpg)

![S4](https://user-images.githubusercontent.com/39883796/166110479-05f77426-4876-45ba-bd81-7268d848cdfc.JPG)

![S5](https://user-images.githubusercontent.com/39883796/166110486-f981a71e-85a0-46f1-83a1-94eab5860642.jpg)

![S6](https://user-images.githubusercontent.com/39883796/166110493-8183a1ae-0171-4724-8e0f-67fdcd6d6c19.JPG)

**Comment by mr-aleks** [comment]
Thank you very much for the information, I deleted the first 11 songs with incorrect characters, but the plugin still shows that the xml needs to be corrected, I don’t understand the meaning of the rest of the errors that it shows me. I have no experience with this plugin. Perhaps you could share the edited xml file?
![image](https://user-images.githubusercontent.com/23143866/166113461-29260c25-49e1-413d-a541-c74ae4ade446.png)
![image](https://user-images.githubusercontent.com/23143866/166113473-f820638c-2ac8-4694-88d6-cff62d1fa87b.png)

**Comment by mr-aleks** [comment]
I got it. In another program, I realized what the problem was. There were strange characters in the entire database. Something like "&#x1F;" and other.
Once again, thank you very much!!
![image](https://user-images.githubusercontent.com/23143866/166118814-9e4b7dd1-8c6a-4e30-ad4c-e68c3310f469.png)

**Comment by DeeTigIT** [comment]
I'm glad to hear you can move on.
And thanks for the XML Notepad screenshot.
I'll add that program to my utils.
