### ISSUE TITLE
Video support in logo option

### ISSUE THREAD

**Issue by damarals** [quelea-projection/Quelea#548]
![image](https://user-images.githubusercontent.com/29554893/169736497-35122255-0ece-4565-8868-67b0cdbec184.png)
I would love to put videos in the logo option, but so far it's only possible with images, and a gif doesn't look good.

**Comment by JessyJP** [comment]
While it would be great, a workaround would be to use video in the schedule list and switch to it, or pass the Quelea output through OBS and then display the OBS output, thus you can layer things in OBS (something I have done and works really good.) Personally, I would put presentations in Quelea, but I wouldn't really use play videos if it's more than a one-off for example or a video list where someone needs to switch it with the stage control.

**Comment by berry120** [comment]
Previously this wasn't really feasible, but now we've switched to GStreamer it should be, and would be a worthwhile addition.
