### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by garryluis73** [quelea-projection/Quelea#551]
I cannot install in windows 11 
![image](https://user-images.githubusercontent.com/109635800/179887157-2d160418-4efa-427c-94f8-bbb3a00841ad.png)

**Comment by DeeTigIT** [comment]
You could use the website virustotal (https://www.virustotal.com/gui/home/upload) to check your downloaded Quelea app against several anti-virus apps. If confident then try to install Quelea again and choose 'More info' in the above screen followed by 'still execute' (or a similar button).

**Comment by berry120** [comment]
Afraid we can't really do much about this - you can click the "Run anyway" button to still open / install Quelea, but there's no way we can get rid of it without purchasing quite an expensive certificate and signing our installers (which as an open source project isn't something we'd do.)

Realise it's a pain, but this isn't one we're likely to be able to do much about.
