### ISSUE TITLE
Image Group Name

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#558]
Can we have the ability to name an image group? When we import an image group, it's name becomes the combination of all of the images imported, resulting in a very long string. In the desktop program, the overflow simply causes that section to scroll. Not a big deal. But in the mobile app, an image group's name is wrapped, and can take up a sizable portion of the screen. See the image below for an example. 

![Screenshot_20220827-171117.png](https://user-images.githubusercontent.com/34974905/187048289-c62200f1-620d-4961-b7e8-20c0ccd2c73e.png)

I could alternatively change the names of each to save space, but it would be better to simply name the image group. 

In my example above, the image names were automatically generated.

**Comment by berry120** [comment]
Yup, good point! Think this is a good idea 👍

**Comment by berry120** [comment]
This should be a reasonably straightforward task if someone wants to pick it up for Hacktoberfest.

**Comment by harshxtanwar** [comment]
Hello @berry120 I am experienced machine learning and backend development in multiple languages, but am very new to open-source. I had like to get assigned to this issue and would love to work on it with some guidance.

**Comment by berry120** [comment]
Take #562 first and see how you get on with that one, then feel free to grab this one as well if you want to work on it after.

**Comment by odifek** [comment]
Hello @berry120, I am an Android developer and would like to start contributing to open source (via hacktoberfest). I have used Quelea for presentation in our church in my former location also. I will love to take on this issue.

**Comment by berry120** [comment]
@harshxtanwar You're taking #562 so @odifek all yours 👍

**Comment by odifek** [comment]
I encountered this error when trying to run the project on my laptop.

```
> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.unsupported.desktop not found, required by javafx.swing
```
I think it's because of M1 macbook. 

I, however, solved it using the recommendation in this StackOverflow answer. https://stackoverflow.com/a/71622655/3884184
I basically downloaded the Azul JDK with Javafx prepackaged

**Comment by berry120** [comment]
Has been done with the above PR.
