### ISSUE TITLE
Theme improvements: show previously set song theme properties in a re-opened schedule

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#56]
(Quelea release : 2018.1)
For a song item in a schedule custom theme properties can be set. But, after saving the schedule and re-opening the schedule, these properties aren't show when opening the theme editor on that song.
As long as the schedule isn't closed and re-opened the adapted song theme properties are shown.
It's only after closing and re-opening the default theme properties for a song with adapted properties are shown. Could this be corrected? Or is it by design?

Song example:

![s1](https://user-images.githubusercontent.com/39883796/46793774-c3222600-cd46-11e8-90e9-52b14cbbb531.JPG)

This in contrary to previously set bible theme properties:

![s2](https://user-images.githubusercontent.com/39883796/46793817-db924080-cd46-11e8-983a-5ca819516517.JPG)

And also previously set timer theme properties:

![s3](https://user-images.githubusercontent.com/39883796/46793846-eb118980-cd46-11e8-8f2d-fea793f0e9be.JPG)

User options:

![s4](https://user-images.githubusercontent.com/39883796/46794088-65daa480-cd47-11e8-8477-ce20a960de92.JPG)

Schedule:

[test_2018.1_custom_themes.qsch.zip](https://github.com/quelea-projection/Quelea/files/2468233/test_2018.1_custom_themes.qsch.zip)

**Comment by DeeTigIT** [comment]
This behaviour (not showing the previously set song theme properties in a re-opened schedule) is present in both releases: Q 2018.1 stable and Q 2019.0 CI.

**Comment by berry120** [comment]
Yup, this shouldn't be happening - thanks for the report. I'll take a look.

**Comment by berry120** [comment]
Should now be fixed in the CI release.

**Comment by DeeTigIT** [comment]
Fix is OK.
