### ISSUE TITLE
Tidy up EpicWorshipParser.format()

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#560]
The above method has a needless assignment on a variable as the first line - that can go.

**Comment by suman-somu** [comment]
I'm taking this issue

**Comment by ParthasarathiMahana** [comment]
Hi, @berry120 I would love to contribute to this issue.

**Comment by ParthasarathiMahana** [comment]
hi @berry120 can you help me with finding the method?

**Comment by berry120** [comment]
The file is called `EpicWorshipParser`, and the method is called `format()` (it's the last method in that file.)
