### ISSUE TITLE
Clean up PresentationPanel lambdas

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#562]
There's a couple of places in PresentationPanel where we're using lambdas in a longer form than we need to - either creating a Runnable directly rather than using a lambda, or using a block based lambda instead of an expression lambda. These are minor bits of syntactic sugar that can be cleaned up.

**Comment by harshxtanwar** [comment]
Hello @berry120 I am experienced machine learning and backend development in multiple languages, but am very new to open-source. I had like to get assigned to this issue and would love to work on it with some guidance.

**Comment by berry120** [comment]
All yours! Take a look at the `docs/SETUP.md` guide for getting started - it's a bit out of date but should cover most of the basics. First thing is to get the project compiled as-is, then you can make the (very minor) changes required by this issue and submit the PR 👍

**Comment by harshxtanwar** [comment]
hello @berry120 I was following the steps in docs/SETUP.md. I am unable to follow the last steps which says 
"Navigate to the src/main/java/org/quelea/windows/main/Main class.
Right-click on that class in the sidebar and click Debug 'Main.main()'"

**Comment by berry120** [comment]
@harshxtanwar What happens when you try to follow that step?

**Comment by harshxtanwar** [comment]
When I navigate to the Main Class and do a right-click, I don't see any option saying " Debug Main.main() "

**Comment by berry120** [comment]
Could you post a screenshot of what you do see? It might be that your project hasn't been recognised as a Java project in IntelliJ somehow.
