### ISSUE TITLE
Needless variable in CreateTimerPanel.parsable

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#564]
`CreateTimerPanel.parsable()` (line 252 ish) declares a needless variable. Instead of this, the variable can just be returned.

**Comment by island-coder** [comment]
Can I work on this? How do I locate the problem file?

**Comment by berry120** [comment]
`CreateTimerPanel.java` is the problem file - you should be able to find that in the repository :-) Sure, assigned to you!

**Comment by island-coder** [comment]
I submitted a  pull request
