### ISSUE TITLE
Add documentation for building Quelea in IntelliJ

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#565]
Update documentation for building & running Quelea using a fresh install of IntelliJ community edition. This should start from the point where the repository is checked out and IntelliJ is installed, and guide the user through to the point Quelea can be compiled & run without an issue. We currently have this for an older version of Quelea that was built on Java 8, but we've since updated to use Java 11.

This should be a relatively easy task as there's no specific configuration Quelea requires to run, so ideal for Hacktoberfest.

**Comment by SachXD** [comment]
I would like to do this! Please assign the issue to me.

**Comment by marcoebbinghaus** [comment]
Isn't that already existing at docs/SETUP.md ?

**Comment by berry120** [comment]
@marcoebbinghaus Sorry, I actually forgot we had that in place. I'll amend this issue to update that documentation, as we've changed to Java 11 since that point (and there may be some other things that need updating too, I haven't checked it in a while.)

**Comment by marcoebbinghaus** [comment]
oh I see, so it is just about updating the existing docs like mentioned in the ticket description. I would like to give it a try. Feel free to assign me to this ticket then.

**Comment by berry120** [comment]
All yours!
