### ISSUE TITLE
PreviewPanel.java - turn anonymous inner classes into lambdas

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#575]
PreviewPanel.java has 3 anonymous inner classes used, these are all `EventHandler`:

 - `liveButton.setOnAction()`, line 64
 - `setOnKeyTyped()`, line 78
 - `setOnKeyPressed()`, line 86

These should all be replaced with lambdas to remove excess boilerplate code.

**Comment by whyang0808** [comment]
Hi, could you assign this to me?

**Comment by Dhi13man** [comment]
Have raised PR #576 to fix this. Please check and merge if alright.

**Comment by Dhi13man** [comment]
@berry120 can you review my PR?
