### ISSUE TITLE
Cannot close options when using French translation

### ISSUE THREAD

**Issue by PhilippeM1970** [quelea-projection/Quelea#580]
It is almost impossible to use the software in French (français) because OK and close button of the option dialog does not works.

We are able to select French langage and restart Quelea as mentionned but then if we open options dialog, it is impossible to apply changes.

We have to manually delete the language line from the quelea.properties file to be able to use the option dialog again (but then it would be in English).

NHot sure why changing the language should affect the language.

**Comment by DeeTigIT** [comment]
https://quelea.discourse.group/t/bug-en-mode-option/976

**Comment by berry120** [comment]
Apologies, this is a critical one that should have been fixed much sooner. On it now.

**Comment by berry120** [comment]
Should now be sorted in the latest CI release - if it's not then feel free to reopen!
