### ISSUE TITLE
Please provide better shortcut to add a song live.

### ISSUE THREAD

**Issue by PhilippeM1970** [quelea-projection/Quelea#581]
When song leader start an unplanned song, it is very long to project that song as there are no keyboard shorthcut or a long sequence of them.

Assuming that the output is blank, you have to do the following :

- Type song title or number
- Double-clic to add it to the schedule
- Go to the schedule and select it for preview
- Goto preview and select appropriate verse
- Click the Go live button
- Show text on screen

All that take about 2 sentences for most songs (that is half of a typical 4 line verses). 

I know that some of those operations have shorthcuts or can be bypassed but it is really not made for live use. We obviously want to be able to display song in half that time.

I think that the ideal way would be that **Enter** would add a song to the schedule, select it there, put in the preview. At that point, focus should be in the preview and pressing **Enter** would **Go live**. However if we don't start on first verse, we can use arrow key to navigate.

By the way, there should be shortcuts for most commands. Presently, it seems from the documentation that you have provide shortcuts for about half of the useful command. We want the equivalent of **Add and go live** from the remove available on the PC. Also shortcut to start a search (F3 or Ctrl + F are popular shortcut for that).

Improving search would also be nice. 

Our previous program was much better in that area but was lacking the wireless remote and stage view. So that's the main reason we switch.

**Comment by DeeTigIT** [comment]
If time is critical you might consider:
- Search and click the sound (it appears in the preview pane when using that option for the database song preview setting).
- Click the desired verse in the preview pane
- Click Go Live button
- Add the song to the schedule afterwards

Blessings,

Dirk / Quelea user

![S1](https://user-images.githubusercontent.com/39883796/197677152-13bdf3de-787e-4111-ae14-e7c04cdb99ff.JPG)

![S2](https://user-images.githubusercontent.com/39883796/197677170-68dedf25-e2d4-4089-97f3-3d25ca17398c.JPG)

**Comment by berry120** [comment]
Ctrl+Alt+L is now the default shortcut (from 2024.0) to add the selected item in the search dialog to the schedule, and put it live. (We already have a Ctrl+L shortcut for selecting the song library search field.)

Note that while we don't yet have an interface for it, these shortcuts can be changed if you edit quelea.properties directly. If you want to change the search shortcut to F3 for instance, just add:

    search.keys=F3

..as a property. `add.and.go.live.keys` is the key for the new shortcut, if you want to change that.

**Comment by berry120** [comment]
(Also to add - if there's anything more specific than the above that I may have missed in that message, feel free to create other issues - easiest to have one issue per problem / request so they're easier to track.)
