### ISSUE TITLE
Future-proofing assets for 2023.0 and beyond

### ISSUE THREAD

**Issue by micahlt** [quelea-projection/Quelea#591]
The new splash screen assets (incorporated in #518) include the version number.  At the moment, there are no source files.  In order to future-proof these assets, we'll need one of two options:

- Easily editable source files (SVG)
- A new design with no version number
- Automatic display of the version number based on Quelea's version

Do y'all have a preference here?  I can easily provide source files of course, but the other options might be more effective.

**Comment by berry120** [comment]
Hey, thanks for flagging this up - very good point! I think the best course of action would be automatic display based on the version number - would you be able to provide the design without version numbers so we can add that over the top?

**Comment by micahlt** [comment]
@berry120 attached are the splash screens with no version numbers on them!
![splash-beta](https://user-images.githubusercontent.com/28816297/222923842-f0b45207-241e-4cfd-bff6-dccf17b3a9c3.png)
![splash-bare](https://user-images.githubusercontent.com/28816297/222923843-929d8592-2083-4975-96a5-acd6f576b3b0.png)
![splash-bare-nightly](https://user-images.githubusercontent.com/28816297/222923844-c775dc9f-c0a7-4cd4-99d3-e230bc27ecd5.png)

**Comment by berry120** [comment]
Sorry for taking an age to get back here - thank you very much, those are now incorporated 👍
