### ISSUE TITLE
Video Layer Missing in Windows 11

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [quelea-projection/Quelea#598]
We just upgraded our computer to Windows 11 and tested Quelea. It looks like everything works fine except for the video layer. When Quelea starts up, what appears to be the video layer appears behind the control window on the main screen, but filling only a quarter of the screen. 

This first picture shows how it appears. The PC's background is the same as the configured logo in Quelea. Quelea is showing the Logo on the right screen, and the left screen is the main screen used to control everything. You can see what I am assuming is the video layer in the top right corner of the left screen.
![Screenshot_20221112_055350](https://user-images.githubusercontent.com/34974905/201497708-ef6ecd28-66bd-4a6c-83f6-453654b29f26.png)

This second picture was a window capture, I selected the window and the snipping tool took a screenshot of the whole window. If accurate, it appears that the video layer is centered between the two screens, but sized in a weird way.
![Screenshot_20221112_055322](https://user-images.githubusercontent.com/34974905/201497782-77137eac-27f6-46fe-a82a-12e798c9cbfb.png)

Whenever I play any song with a video background or when I play a video or press the Hide display output button, this window disappears.

I'm also attaching the logs. I deleted it after closing Quelea, then opened it again. I didn't see anything relevant, but I could have missed it.

[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/9996098/quelea-debuglog.txt)

**Comment by berry120** [comment]
Could you try with the latest CI release (using GStreamer) and post back if it's still an issue?

**Comment by berry120** [comment]
Closing this as should be fixed - feel free to recreate if it's still a problem.
