### ISSUE TITLE
problem bible .xml file does not open in Quelia

### ISSUE THREAD

**Issue by Eck2** [quelea-projection/Quelea#613]
Hi, I am trying to open three bible files in quelia downloaded from the https://sourceforge.net/projects/zefania-sharp/files/Bibles
however the following files cannot be open in Quelia, could you identify the problem?
[SF_2009-01-20_FRE_FREN_(FRENCH LOUIS SEGOND)(1).zip](https://github.com/quelea-projection/Quelea/files/11079160/SF_2009-01-20_FRE_FREN_.FRENCH.LOUIS.SEGOND.1.zip)
[SF_2009-01-22_GER_ELB1905STR_(ELBERFELDER 1905).zip](https://github.com/quelea-projection/Quelea/files/11079163/SF_2009-01-22_GER_ELB1905STR_.ELBERFELDER.1905.zip)
[SF_2009-06-06_FRE_JND_(FRENCH DARBY 2006).zip](https://github.com/quelea-projection/Quelea/files/11079164/SF_2009-06-06_FRE_JND_.FRENCH.DARBY.2006.zip)

**Comment by DeeTigIT** [comment]
Your SF_2009-01-20_FRE_FREN_.FRENCH.LOUIS.SEGOND.1.zip seems to be empty and needs a new download attempt.

Using Quelea 2022.0 version I can add the following 3 unzipped bibles:
- SF_2009-01-20_FRE_FREN_(FRENCH LOUIS SEGOND).xml
- SF_2009-01-22_GER_ELB1905STR_(ELBERFELDER 1905).xml
- SF_2009-06-06_FRE_JND_(FRENCH DARBY 2006).xml

![FRE (2)](https://user-images.githubusercontent.com/39883796/228939309-33db6061-9fe6-4463-87e3-bc260257d45c.JPG)

![GER](https://user-images.githubusercontent.com/39883796/228939365-4082ba65-1535-4629-819d-42bb698dfeb8.JPG)

![FRE](https://user-images.githubusercontent.com/39883796/228939241-01938bbc-9a51-41f6-9c2e-836e08a1cb59.JPG)

[SF_2009-01-20_FRE_FREN_(FRENCH LOUIS SEGOND).zip](https://github.com/quelea-projection/Quelea/files/11115183/SF_2009-01-20_FRE_FREN_.FRENCH.LOUIS.SEGOND.zip)
