### ISSUE TITLE
Revert to previous version in snap

### ISSUE THREAD

**Issue by daddins** [quelea-projection/Quelea#614]
Hi Team, 

While investigating the VLC 'missing' issue in quelea 2022 (Linux snap), the advice has been to revert to the 2021 version which worked. Unfortunately, I never had the 2021 snap version running locally  (sudo snap revert ‘package’ --revision ###), so I can't revert back to it. Is there any way to install the 2021 snap version? I tried to run the 2021 cross-platform java  version but I couldn't get that up and running - Java issues.

Kind regards

**Comment by daddins** [comment]
Hi Michael,

when I try to install an older version sudo snap revert quelea --revision
788 i receive error: cannot revert "quelea": cannot find revision 788 for
snap "quelea"

I don't have the previous versions installed, am I able to install the
older versions straight from the snap repository?

Blessings

Phil.

**Comment by berry120** [comment]
Afraid I'm not sure if this is possible after all now (sorry for the massive delay in replying) - but would appreciate any feedback on the latest CI release which uses GStreamer.

In terms of the snap older version issue - might be worth asking on https://forum.snapcraft.io/ if you'd still like an answer, they'll be much better at answering snap related questions (I use it, but I'm far from an expert.)
