### ISSUE TITLE
Adding songs with app 

### ISSUE THREAD

**Issue by thomasvergouwe** [quelea-projection/Quelea#619]
Hi, we often add songs on the fly during our church services. We also use the app to control Quelea.
We have it set in the settings that quelea would always use the translation when adding a song. However, when we add a song through the app to the service, quelea doesn’t automatically use the translation.

Can this be added?

**Comment by berry120** [comment]
Hey, afraid the app is maintained separately from the main source (it was written by another member of the team who I'm not sure is actively making changes at the moment.)

Worth asking on this repo just in case: https://github.com/ArvidNy/quelea-flutter-remote
