### ISSUE TITLE
Quelea doesn't open on Zorin OS 16.3.

### ISSUE THREAD

**Issue by brunomint** [quelea-projection/Quelea#623]
I clicked on the Quelea icon in Zorin OS, but the program didn't open. So, I went to the terminal, typed "Quelea," and received the following message: "Java: error while loading shared libraries: libz.so.1: cannot open shared object file: no such file or directory." I then entered the command "sudo apt-get install zlib1g," and the terminal message indicated: "zlib1g is already the newest version (1:1.2.11.dfsg-2ubuntuq.5)."

**Comment by berry120** [comment]
Hey, is this the 2024.0 beta? Which installer are you using?

**Comment by brunomint** [comment]
Hello, Berry! First, I'd like to say that your program is wonderful! I use it in my church. Currently, I'm using version 2022. Unfortunately, the video doesn't work on Linux with this version. So, I decided to download the 2024 beta to experiment and check the video issue. However, the 2024 beta doesn't open.

**Comment by berry120** [comment]
Sure, thanks! And is this the cross platform installer?

**Comment by brunomint** [comment]
I tryied the snap version and the cross platform. Unfortunately the two versions didn't open.

**Comment by berry120** [comment]
Just as a hunch, could you try installing zlib1g-dev and see if that helps
the cross platform version work?

**Comment by berry120** [comment]
Now fixed in the snap release for 2024.0.

For the cross-platform release, please ensure that you're using the 64 bit version of Java, and you have both zlib1g and zlib1g-dev installed.
