### ISSUE TITLE
Investigate WMV support in GStreamer

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#626]
GStreamer doesn't seem to play WMV files at the moment.

**Comment by berry120** [comment]
Related thread: https://lists.freedesktop.org/archives/gstreamer-devel/2023-December/081944.html

**Comment by berry120** [comment]
@DeeTigIT Could you give the latest CI a try? WMV support should now be fixed.

**Comment by DeeTigIT** [comment]
I can confirm this fix. Thanks!
