### ISSUE TITLE
Add "unsupported" overlay to unsupported videos in video panel preview

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#627]
Currently unsupported videos just show as a standard video preview image in the videos tab. Should explicitly add "unsupported" as an overlay to make it clear these videos won't play.

**Comment by berry120** [comment]
Decided to use a clearer graphic overlay instead to avoid the need for an additional text implementation / translation. This should be clear enough.

**Comment by DeeTigIT** [comment]
It is! 👍 

![afbeelding](https://github.com/quelea-projection/Quelea/assets/39883796/826f12d5-3038-4ab1-bccd-0d4c31ed7519)
