### ISSUE TITLE
2024.0 CI - drag and drop multiple song selection from library to schedule

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#629]
When selecting multiple songs in the library: 'drag and drop' to the schedule only adds the first song from the selection to the schedule.

**Comment by berry120** [comment]
@DeeTigIT Hopefully this one is fixed by the above 👍

**Comment by DeeTigIT** [comment]
It is fixed indeed in the latest CI. This issue can be closed.

**Comment by berry120** [comment]
@DeeTigIT Lovely, thanks!
