### ISSUE TITLE
Resizing the main window causes videos to stop playing

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#631]
As above, in the current 2024.0 beta. Resizing the window should have no effect on what's playing.

**Comment by DeeTigIT** [comment]
Observed as well here. Just a note: when I put a video behind the most left Quelea button then resizing the main window does NOT stop the video from playing.

![afbeelding](https://github.com/quelea-projection/Quelea/assets/39883796/139c2a08-4510-4a2d-aa77-88fc18c2ae9b)

**Comment by DeeTigIT** [comment]
Fix confirmed!
