### ISSUE TITLE
Quelea on Zorin OS 16

### ISSUE THREAD

**Issue by brunomint** [quelea-projection/Quelea#633]
Hi Mr. Berry. Thanks a lot for fix Quelea. Now it's open on Zorin OS 16.3 x86_64 and I now can play videos. I'll keep triyng...

![inbound3790016985368543664](https://github.com/quelea-projection/Quelea/assets/123033587/469ac566-d3b1-4648-adc9-114b978a0f8c)

**Comment by brunomint** [comment]
I tried 2024.0 beta 2

**Comment by berry120** [comment]
@brunomint what's the issue here - it all looks to be working ok, so can this be closed?

**Comment by brunomint** [comment]
I could see a issue: sometimes Quelea freeze The computar and I have to reboot the system. 
![inbound1755322929381383772](https://github.com/quelea-projection/Quelea/assets/123033587/28d28f26-2648-4879-bf72-092ecc94b3ae)
As you can see on image. I was saving a new song and the computer stopped to respond.

**Comment by brunomint** [comment]
> I tried 2024.0 beta 2

Snap version

**Comment by berry120** [comment]
Does the whole pc freeze or just Quelea? Do you have any steps that can
reliably reproduce the issue?

**Comment by brunomint** [comment]
The whole PC freezer. In this case, he froze when I went to save a song. Another case happened when I went to put an animated background

**Comment by berry120** [comment]
Just to check - is this *every* time you save a song?

**Comment by brunomint** [comment]
The PC completely freezes when it needs to handle slightly heavier processing in Quelea

**Comment by berry120** [comment]
What are the specs of the PC?

**Comment by brunomint** [comment]
![inbound6059289173433623883](https://github.com/quelea-projection/Quelea/assets/123033587/e5254e20-2fbe-4df9-b32d-b39a02a6ae8a)

I try to use Quelea 2024 now and I could see PC completely freezes when I try to set a background video on lyrics

**Comment by berry120** [comment]
4GB is going to be on the tight side for Quelea - not sure if that's why you're getting the issue, but it definitely won't be helping.

Can you attach the debug log in case that helps work out what's going on?

https://quelea-projection.github.io/docs/Debug_log.html

**Comment by berry120** [comment]
Closing for now, can reopen if we have more details that'll allow us to see what's going on. If you're trying again please try with the 2024.1 release in case any changes there have solved the issue.
