### ISSUE TITLE
Videos tab: allow 'drag-and-drop' video to schedule

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#636]
Currently, the Videos tab does allow 'left-double-click' to add a video to the schedule.
But 'drag-and-drop' a video to schedule is not present yet.

Compare:

- For the Images tab: both 'left-double-click' and  'drag-and-drop' are possible.
- On the Songs tab both 'left-double-click' and  'drag-and-drop' are also possible.

(note: this is NOT a 2024.0 regression, but a new RFC)

**Comment by berry120** [comment]
@DeeTigIT This should hopefully now be operational, the same as images.

**Comment by DeeTigIT** [comment]
Video 'drag-and-drop' to schedule works now. RFC issue can be closed. Thanks!
