### ISSUE TITLE
Allow user-defined size for thumbnail previews of Powerpoint slides

### ISSUE THREAD

**Issue by berry120** [quelea-projection/Quelea#64]
_Originally posted by @kanglinyao in https://github.com/quelea-projection/Quelea/issues/61#issuecomment-434134509_

**Comment by ArvidNy** [comment]
We actually already allow user-defined size for thumbnail previews, so this is an issue that easily could be solved. @kanglinyao requested an increase of the maximum limit from 500 and it's really just a matter of changing "500" in this line: 
https://github.com/quelea-projection/Quelea/blob/bb43b1c47cf08fb1cb7f38dae59bf2dd8f60ce45/Quelea/src/main/java/org/quelea/windows/options/OptionsGeneralPanel.java#L118

This is a perfect [Hacktoberfest](https://hacktoberfest.digitalocean.com/) issue if someone wants to make a PR. Just remember to also add a line about it in the change log.
https://github.com/quelea-projection/Quelea/blob/bb43b1c47cf08fb1cb7f38dae59bf2dd8f60ce45/Quelea/changelogs/changelog-2020.0.txt#L1

**Comment by berry120** [comment]
Thanks for this @ArvidNy. What would you say it should be increased to - 1000 maybe?

**Comment by ArvidNy** [comment]
I was thinking that around 800-900 should be enough, but 1000 sounds like a good value to (hopefully) avoid having to open this issue again.

**Comment by berry120** [comment]
Fixed by #208
