### ISSUE TITLE
Quelea fails to open or save file if path contains unicode characters

### ISSUE THREAD

**Issue by kukymbr** [quelea-projection/Quelea#646]
Quelea fails to save files with Unicode non-latin characters in the path: if file name contains these characters, the file is saved with `?` symbols instead of them; if the directory name contains unicode characters, operation is failing at all.

Also, it fails when opening paths with unicode.

Ubuntu 22.04, Quelea 2024.0
[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/14156405/quelea-debuglog.txt)

**Comment by berry120** [comment]
Hmm, is this on Mac? It works for me fine on Windows:

![image](https://github.com/quelea-projection/Quelea/assets/7595149/cfff3bd8-2578-43a4-afbb-799606a4336d)

If so, there's nothing we're explicitly doing to manage file locations that I can think of that would cause this issue, so I'm tempted to say this is another reason to expedite https://github.com/quelea-projection/Quelea/issues/641.

**Comment by kukymbr** [comment]
Nope, this is Ubuntu 22.04 machine

**Comment by berry120** [comment]
Cool, I'll try on the VM and let you know

**Comment by berry120** [comment]
@kukymbr This should now be fixed in the CI release - as part of the Java 21 / OpenJFX 21 upgrade work we now use GTK3 which supports & uses UTF-8 by default.

**Comment by kukymbr** [comment]
Checked this, works fine.
