### ISSUE TITLE
Problems using Quelea on Linux

### ISSUE THREAD

**Issue by juniornff** [quelea-projection/Quelea#659]
I'm using:
OS: Debian GNU/Linux 12 (bookworm) x86_64
DE: GNOME 43.9
java -version:
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Debian-2deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Debian-2deb12u1, mixed mode, sharing)

I will leave the log from the bash Here: [Quelea bash log.txt](https://github.com/user-attachments/files/16923474/Quelea.bash.log.txt)

Before talking about the log itself i would like to mention the command i use to open Quelea `cd /usr/local/Quelea && java -jar Quelea.jar ` because if i use the same command but i do this `java -jar /usr/local/Quelea/Quelea.jar` the process stops at `org.quelea.services.utils.UpdateChecker checkUpdate INFO: Checked updates, current version is 2024.0 and latest version is 2022.0`

Now, about the log, there are some messages that worry me (there are a few more in the log file):
```
sep. 08, 2024 9:04:47 A. M. com.sun.javafx.application.PlatformImpl startup
ADVERTENCIA: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @26ee6b5e'
```
```
Sep 08, 2024 9:04:49 AM org.quelea.windows.main.Main start
INFO: Couldnt set icon, probably an unsupported platform and nothing to worry about: {0}
```
`(java:6258): Gdk-WARNING **: 09:04:49.744: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`
```
Sep 08, 2024 9:04:53 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
```
`ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`

**This one appears when quelea is already open and keeps appearing every few minutes:**
`(java:6258): GStreamer-CRITICAL **: 09:05:23.715: gst_sample_set_caps: assertion 'gst_sample_is_writable (sample)' failed`

--------------------------------------------------------------------

Now, i was trying to fix the first message, i don't know almost anything Java, so i ask ChatGPT what could be a solution [Here](https://chatgpt.com/share/b6a244e7-40c6-444c-92c9-3319807f7ce6). When i use the command that it propose `java --module-path /usr/share/openjfx/lib --add-modules=javafx.controls,javafx.fxml -jar Quelea.jar` Quelea don't open and keeps consuming more and more RAM (normally uses 3-4 GB): 
![Capture](https://github.com/user-attachments/assets/ecfd585e-0a3f-49b5-9c2f-92901274e5ff)

--------------------------------------------------------------------

About the other ones i didn't even try because Quelea works even with those error and i don't want to mess things even more

**Comment by berry120** [comment]
> Before talking about the log itself i would like to mention the command i use to open Quelea cd /usr/local/Quelea && java -jar Quelea.jar  because if i use the same command but i do this java -jar /usr/local/Quelea/Quelea.jar the process stops

...because it's not the same command. In the first you're launching within its own directory (which it needs to find its resources), in the second you're launching it from a different directory (which means it won't start, as it won't find any of its resources.)

The `GStreamer-CRITICAL` error sounds like there's been an issue loading GStreamer, which may mean you can't play videos or use video backgrounds. (That's difficult to diagnose though.) The others are all warnings that can be safely ignored, and definitely shouldn't try to be addressed by asking ChatGPT for solutions :)

**Comment by juniornff** [comment]
> > Before talking about the log itself i would like to mention the command i use to open Quelea cd /usr/local/Quelea && java -jar Quelea.jar  because if i use the same command but i do this java -jar /usr/local/Quelea/Quelea.jar the process stops
> 
> ...because it's not the same command. In the first you're launching within its own directory (which it needs to find its resources), in the second you're launching it from a different directory (which means it won't start, as it won't find any of its resources.)

Yes, I can understand that. I just mention it in case it was something you weren't aware of. In my case I made an alias command to open Quelea properly.

> The `GStreamer-CRITICAL` error sounds like there's been an issue loading GStreamer, which may mean you can't play videos or use video backgrounds. (That's difficult to diagnose though.) 

I haven't tried video backgrounds but it is able to play videos without problems. I was thinking about going back to version 2023, since it uses VLC as a video player. But that would be a test for another time.

> The others are all warnings that can be safely ignored, and definitely shouldn't try to be addressed by asking ChatGPT for solutions :)

I understand. Using ChatGPT was more of a way to experiment with possible solutions before/while doing this report. At the end of the day I use Quelea without those added commands.

I wanted to document and report everything just to let you know or to be informed if I was doing something wrong.

**Comment by berry120** [comment]
> I wanted to document and report everything just to let you know or to be informed if I was doing something wrong.

Thanks very much for the heads up! Nothing too wrong or unusual here as everything works, so I'll close this one - but if you notice anything broken, please let us know 👍
