### ISSUE TITLE
RFC: database plain text import - fill song information tags using keywords

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#7]
When importing a song using a plain text file, the first line in the file is used to generate the song title.
(and this first line is also added to the song details, although it is not a song line) The other basic and detailed song information are left empty during import. 
**Is it possible to use optional keywords, to be placed at the beginning of the plain text file, for filling the basic information and detailed song information tags during the plain text import?** 
We're in the process of importing thousands of plain text song files. A title keyword would prevent that the first line also becomes a song line. For most songs we also have the CCLI numbers. It would be great if these CCLI numbers could also be imported at the same time, using a CCLI keyword.

_$Title=
_$Author=
_$CCLI_number=
_$Copyright=
_$Year=
_$Publisher=
_$Key=
_$Capo=
_$Notes=

**Comment by berry120** [comment]
We'll implement this for 2019, but with the tags as more human readable format (I don't see a particular advantage in starting them with _$.) So a line will be parsed as a title so long as the tag starts with "Title:", it'll be parsed as an author if it starts with "Author:" etc.

**Comment by DeeTigIT** [comment]
Great! I am looking forward to testing.

Van: Michael Berry [mailto:notifications@github.com]
Verzonden: zaterdag 28 juli 2018 00:01
Aan: quelea-projection/Quelea
CC: DeeTigIT; Author
Onderwerp: Re: [quelea-projection/Quelea] RFC: database plain text import - fill song information tags using keywords (#7)


We'll implement this for 2019, but with the tags as more human readable format (I don't see a particular advantage in starting them with _$.) So a line will be parsed as a title so long as the tag starts with "Title:", it'll be parsed as an author if it starts with "Author:" etc.

**Comment by DeeTigIT** [comment]
In the CI-release:
- Plain text import of a song, with song information tags, works great!
- Without tags the first line is only used for the title, no longer a song line.

[Plain test song - without keywords - At Calvary.txt](https://github.com/quelea-projection/Quelea/files/2312846/Plain.test.song.-.without.keywords.-.At.Calvary.txt)
[Plain text song - with keywords - At Calvary.txt](https://github.com/quelea-projection/Quelea/files/2312847/Plain.text.song.-.with.keywords.-.At.Calvary.txt)
![keywordfilled](https://user-images.githubusercontent.com/39883796/44504131-5bcaec80-a69a-11e8-8783-c8c4964787d5.JPG)
