### ISSUE TITLE
Quick inserted song is added unexpectedly to the db (when editing an existing schedule)

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#70]
When the Quick Insert button is used, the resulting item is added to the schedule and not to the song db. Once in the schedule this quick inserted item can be edited, and again without any consequences for the db (as the song isn't in the db). This seems all correct to me.

However, when the schedule is saved and re-opened (the re-opening can be in the same Q session or a later Q session in time) editing the quick inserted item has an unexpected effect: the song is now also added to the song db. In the CommandBox is displayed : INFO: Updating song that doesn't exist, adding instead ** Is this correct behaviour?**

**Comment by berry120** [comment]
Good spot, this isn't intended behaviour.

**Comment by DeeTigIT** [comment]
Here's the correct property : updateInDB

![s1](https://user-images.githubusercontent.com/39883796/49780300-42fc4a80-fd0e-11e8-9056-eaa5d3056117.JPG)

**Comment by berry120** [comment]
That should have sorted it - could you check? Thanks!

**Comment by DeeTigIT** [comment]
Hello Michael,
The latest change is a bit too rigorous, I'm afraid.
I started testing with a regression test: 
- change the title of an existing db song
(note: at the bottom of the Q screen there is no db update progress bar shown)
- during the Q session the changed title is visible
- but after a Q stop-start the the change in title has disappeared
**So**: a change in a db song is no longer permanently stored in the db.
Regards,
Dirk

**Comment by berry120** [comment]
Oops, that'll teach me to do things in a rush - a single if statement the wrong way around! That should have fixed it now...

**Comment by berry120** [comment]
Just given it another try. (Sorry changes are sporadic and untested at the moment - not finding much in the way of time...!)

**Comment by DeeTigIT** [comment]
Thanks Michael, this one works. You can close the issue.
I will not request any more changes for the the coming 2019.0 releases.  :-)

**Comment by berry120** [comment]
No, thank you very much for the testing and bug reports - they're very useful!
