### ISSUE TITLE
OpenLyrics import ignores verseOrder

### ISSUE THREAD

**Issue by danbaechtold** [quelea-projection/Quelea#72]
Hi,

When importing a song in the [OpenLyrics format](http://openlyrics.org/dataformat.htm), the verse lines are simply imported line by line, without making the verse (titles), and also without keeping the verse order intact (Brigdes will not be repeated).

Here is an example:
[10,000 Reasons.zip](https://github.com/quelea-projection/Quelea/files/2552292/10.000.Reasons.zip)

Thanks,
Dan

**Comment by berry120** [comment]
Yup, that's correct - when we add support for custom song orders natively in Quelea, we'll look to fix this then. (Not much point before that.)

**Comment by danbaechtold** [comment]
Ah, I was not even aware of that. Yes, then of course it can only be done after this feature is ready.

I was able to convert the XML to contain the (repeated) slides, so for me, it doesn't matter anymore, you can keep or close the issue.

Thanks for your awesome work,
Dan
