### ISSUE TITLE
Quelea 2019 cl launch error

### ISSUE THREAD

**Issue by kanglinyao** [quelea-projection/Quelea#77]
Environment Mojave Java 8 (build 1.8.0_191-b12)
![screen shot 2018-11-13 at 12 24 36 pm](https://user-images.githubusercontent.com/21337733/48455849-a4b9b980-e821-11e8-82e1-ecbc5f5f7f58.png)

**Comment by berry120** [comment]
Change of plan - we've reverted to Java 8 for a number of reasons. This should now work as expected, so long as you have both Java 8 and OpenJFX (if using OpenJDK) installed.

**Comment by berry120** [comment]
Closing this one off, but feel free to reopen if things still don't work and you can provide some more info.
