### ISSUE TITLE
Error al cargar video de fondo

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#82]
Siempre se queda en "Espere que se copie el video", tarda demasiado y hay que cancelar, este error es en 2019.0 la última nightly

**Comment by Cyb3rG0D7** [comment]
![bug1](https://user-images.githubusercontent.com/35184132/50371561-608da780-058b-11e9-8cf4-40075841a0c0.png)
siempre se queda ahí, cancelo y no aparece el video, no carga nada
[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/2704877/quelea-debuglog.txt)

**Comment by berry120** [comment]
Afraid I can't seem to reproduce this. Does it happen with all video files or just some? It could be that you're trying to use a particularly large video file that's taking a long time to copy over?

**Comment by Cyb3rG0D7** [comment]
Me pasa en mi laptop y en la pc de la iglesia, tuve que volver a 2018.1 para el servicio ahi el video todo bien.
este es el link de uno de los videos que trato de usar en la última noche, en 2018.1 carga normalmente.
https://drive.google.com/open?id=1MtBiBq_KZjhwxoLmHgHsX28_sroLYZyf
-------------------------------------------------------------------------------------
Al cargar el vídeo de acá, no se puede previsualizar el vídeo, nosé si sea por el formato. si reproduce en el 2 monitor pero en quelea no se puede previsualizar.
https://drive.google.com/open?id=130ZirS8J6x3ZJ0HYSptdBPQV3M_G3LR0
![bugpre1](https://user-images.githubusercontent.com/35184132/50380150-5374c500-062c-11e9-80f5-afe60f212c4d.png)
![bugpre22](https://user-images.githubusercontent.com/35184132/50380151-553e8880-062c-11e9-9bfe-93087cf47995.png)
![bug pre2](https://user-images.githubusercontent.com/35184132/50380152-566fb580-062c-11e9-95ea-79898e5458ac.png)

**Comment by Cyb3rG0D7** [comment]
Porque no pedir al usuario si desea copiar el video o desea reproducir de la ruta original, así se ahorraría incluso espacio en disco.

**Comment by ArvidNy** [comment]
Just tried to reproduce this and I got the following error:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.quelea.windows.newsong.VideoButton.copyFile(VideoButton.java:143)
	at org.quelea.windows.newsong.VideoButton.access$300(VideoButton.java:50)
	at org.quelea.windows.newsong.VideoButton$1$1.run(VideoButton.java:87)
```
Just changing the copyFile method to something like the code below resolved it. Any reasons why the approach with the .flip() method is better, @berry120?
```
try (InputStream is = new FileInputStream(new File(in)); OutputStream os = new FileOutputStream(new File(out))) {
            byte[] buffer = new byte[4096];
            int length;
            while ((length = is.read(buffer)) > 0) {
                os.write(buffer, 0, length);
            }
        }
```

**Comment by ArvidNy** [comment]
That seems to have resolved it, but feel free to open it again @Cyb3rG0D7 if you still experience issues.

**Comment by berry120** [comment]
@ArvidNy To elaborate on why we're using buffers / the nio library in general - it (on all major systems) makes direct calls to the OS to copy / manipulate files. This makes it a lot faster than the old io approach, where bytes were read from a file into the VM, then back out to another file chunk by chunk.

It's just a performance increase. There's no functional difference apart from that, but I'd like to avoid slowing things down if possible 👍

**Comment by Cyb3rG0D7** [comment]
Gracias amigos, en la noche actualizo y lo usaré con la corrección del error.
