### ISSUE TITLE
Falsa información enviando al segundo monitor

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#83]
![bug1](https://user-images.githubusercontent.com/35184132/50371616-4b654880-058c-11e9-80ab-b453c788d42b.png)
![bug 2](https://user-images.githubusercontent.com/35184132/50371617-4e603900-058c-11e9-8299-ab54cc7547ee.png)
![bug3](https://user-images.githubusercontent.com/35184132/50371618-528c5680-058c-11e9-825f-25139d21e82b.png)
Está en el máximo el tamaño de letra, en la previsualización de quelea esta todo bien, pero en el segundo monitor sale la letra con el mínimo de tamaño enviando falsa información,
[quelea-debuglog.txt](https://github.com/quelea-projection/Quelea/files/2704883/quelea-debuglog.txt)
Quelea 2019.0 la última noche
y windows 10 october update

**Comment by berry120** [comment]
Thanks for the report! Should now be fixed.
