### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#84]
Nose si para 2019.0 o 2019.1 se puede agregrar un tema global para quelea aparte de blanco, tema gris y negro.

**Comment by berry120** [comment]
Afraid I'm not sure what you're asking here - you can already add any new global theme you like?

**Comment by Cyb3rG0D7** [comment]
Yes, I like a skin dark/grey for quelea

**Comment by berry120** [comment]
Afraid this isn't something we're likely to add, as it's a huge amount of styling work and testing (and time is a bit of an issue at present!)

Certainly no objection to adding this in if anyone else wants to work on the stylesheet, so I'll leave it open in case someone wants to pick this up.

**Comment by ArvidNy** [comment]
I gave this an attempt and the result looks something like this. The changes are in a branch so that we could look at this closer for a future release.

![dark-theme](https://user-images.githubusercontent.com/14236185/50832655-28d67c00-134f-11e9-8221-33a308506910.png)

**Comment by berry120** [comment]
Thanks Arvid! We'll take a more detailed look when 2019.0 is out.

**Comment by berry120** [comment]
Fixed in 2019.1.
