### ISSUE TITLE
special character import issue

### ISSUE THREAD

**Issue by aniMattor** [quelea-projection/Quelea#85]
Greetings. I'm working with a Croatian church and have an Easy Worship database of Croatian language songs to import. I have already tested it and it works fine, except that some special characters are importing wrong. 
Croatian "Č" comes as"È" and "Ć" comes in as "Æ". I have encountered this before in other situations and it is related to the character set being used. I can manually edit the songs after import, but I just wanted to check if there is a way to globally search/replace either in the easyworship .mb file, or the quelea database after import. 

 Thanks so much for making Quelea available!

**Comment by berry120** [comment]
Hi! Afraid I'm going to have to put this down as a wontfix (more like cantfix) - we re-wrote the Easyworship importer pretty extensively a while back, but this was the one thing we weren't able to sort out. Our best guess is that the character encoding is stored elsewhere and is system dependent, as it doesn't seem to be part of the database (certainly none of the tools we had that were able to read the database could pick the correct character encoding, and we couldn't find anything stored that would let us pick it either.)

So with that in mind I'm afraid the only thing I can really suggest is to change them manually - sorry about that.

**Comment by aniMattor** [comment]
Thank you for the response. A definite "no" is helpful--no need to waste time trying to find a "better" solution. Now I just have to use a little elbow grease and fix it up by hand. Thanks again.
