### ISSUE TITLE
Make import from Elvanto use configurable client_id

### ISSUE THREAD

**Issue by jakobmatt** [quelea-projection/Quelea#86]
I am very interested in the new import functionality for Elvanto that was added some months ago. I tested it towards our church's Elvanto domain, but it failed at first. After providing the correct client_id in a URL it was successful.

The problem relates to line 183 in file Quelea/Quelea/src/main/java/org/quelea/services/importexport/ElevantoLoginDialog.java. The parameter client_id should be made configurable in some way. 

Documentation page from Elvanto (the product has also changed name recently to Tithe.ly ChMS). https://help.tithe.ly/tithe-ly-chms-how-to-s/integrations/worship-how-to-set-up-the-proclaim-integration - the Proclaim integration should be very similar to this Quelea integration.

**Comment by berry120** [comment]
Haven't yet added this to the options dialog, but when this latest CI release builds (I've literally just pushed it) then you should be able to override this by adding a custom "elevanto.client.id" to your quelea.properties file (in C:\users\USERNAME\.quelea).

Any issues just let me know!

**Comment by jakobmatt** [comment]
I tested with the Beta release, and it works fine to add the client id in the properties file. Thanks for a quick fix!

**Comment by berry120** [comment]
Reopening as we should put this in the options dialog at some point, especially now it's been reorganised to cope with a better number of options.

@ArvidNy is this something you'd be able to look at at some point? No rush at all.

**Comment by ArvidNy** [comment]
Does this look OK to you, @berry120, or would you prefer a different categorization?

<img width="1002" alt="Skärmavbild 2020-10-23 kl  16 20 06" src="https://user-images.githubusercontent.com/14236185/97015372-ca8e8380-154b-11eb-98df-cdfe1fcab035.png">

**Comment by berry120** [comment]
I think that's fine. There's likely a bunch of other properties we'll need to add at some point for import/export to other services, so happy for it to be in its own category for now.

**Comment by ArvidNy** [comment]
That's what I figured as well. I've now uploaded the changes.
