### ISSUE TITLE
Error al jugar con la matriz

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#87]
![b-matriz](https://user-images.githubusercontent.com/35184132/50739206-e5dba380-11aa-11e9-97a6-191c7098765f.png)
Al jugar con la matriz quelea muestracorrectamente pero en la segunda pantalla no hay ningún cambio.
Windows 10 1809
Quelea 2019.0 beta1 x64
VLC 3.0.4 x64

**Comment by berry120** [comment]
I think this might be a duplicate of this issue? https://github.com/quelea-projection/Quelea/issues/8

**Comment by berry120** [comment]
Duplicate of #8
