### ISSUE TITLE
Images in embedded Image Group not shown after re-opening schedule

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#92]
Release: 2019.0 CI
Option: Embed media in schedule file = yes
Test: add Image Group to sched, save sched, re-open sched

Re-opening a previous built schedule with an embedded Image Group doesn't show the images in the Preview and Live, only numbers:

![s1](https://user-images.githubusercontent.com/39883796/51784654-82f77f80-214c-11e9-9e32-765222dd015b.JPG)

Here's the schedule (please remove the .zip after download):

[schedule_test_yes-embed_imagegroup.qsch.zip](https://github.com/quelea-projection/Quelea/files/2798780/schedule_test_yes-embed_imagegroup.qsch.zip)

**Comment by ArvidNy** [comment]
Thanks for finding this! I just took a look at it and found the issue. Within a few minutes you should be able to try the CI release again and see if it works for you.

**Comment by ArvidNy** [comment]
Great, thanks for confirming! Regarding the EXIF orientation we haven't gotten around to it yet, but hopefully there's a library that would be easy to use so that we won't have to do all the coding ourselves.
