### ISSUE TITLE
Small preview in database suggestion/request

### ISSUE THREAD

**Issue by dmcharpentier** [quelea-projection/Quelea#94]
This is for 2019.0 b1. At least in my case I find this little window in the way. I suggested to another dev that I was in contact with that the preview pane be used to display that preview. I can see a few times when that single slide might be helpful but they are far and in-between. However I believe a better alternative would be to add a three way toggle in the settings somewhere to change that behavior and make it more flexible for everyone. I was thinking of something like "Display Preview: None/In Database/Preview Pane". I know I can CTRL Click to show it in preview but really then I just feel like that small preview is in the way. I get its point but if possible I would at least like the option to turn it off.
![screenshot_1](https://user-images.githubusercontent.com/1699914/51804401-76e3ee80-222e-11e9-96f6-06f961340180.png)

Thanks,
Dylan

**Comment by berry120** [comment]
Yup, I think this is a fair request - not everyone will want the preview there and (despite my personal preference!) we have had other requests to display database items in the preview panel. I'll look into adding this option in.

**Comment by DeeTigIT** [comment]
Here some contributing thoughts on this:
- New checkbox option 'Database sneak preview'.
- If checked: show the preview whenever the cursor hoovers (a long enough time) over a song in the db pane.
- Show the preview near the cursor (position the lower-left corner of the preview to the right of the cursor).
