### ISSUE TITLE
Issues adding songs to the schedule

### ISSUE THREAD

**Issue by dmcharpentier** [quelea-projection/Quelea#95]
This is for 2019.0 b1 . Occasionally I cannot drag songs from the database to the schedule and a few times I couldn't even double click to add them. The only way I could get them to add at this point was to right click and click "Add to Schedule". Not sure the issue and due to the nature I couldn't get a video or picture of it unfortunately.

Thanks,
Dylan

**Comment by berry120** [comment]
I've had a good play but afraid I can't reproduce this at all. Unless one of the other devs (@ArvidNy ) is able to reproduce this, we may have to close for now (we can't really fix it if we can't reproduce it.)

If you can reproduce it and then attach the [debug log](https://quelea-projection.github.io/docs/Debug_log) in case that happens to offer any clues, that'd be helpful.

**Comment by ArvidNy** [comment]
Sorry, I also just tried to reproduce it and was unable to. If you could send the debug log, like Michael said, that would help a lot. Otherwise it would help knowing if it always happens or just sometimes when you run Quelea and in that case if you could notice any consistency in when this happens.

**Comment by dmcharpentier** [comment]
I've been running 2019.0 at my church so I'll try and replicate it and attach a debug log on Sunday (2/3).

Thanks,
Dylan

**Comment by dmcharpentier** [comment]
So I can't replicate this. I'll close it for now and reopen an issue if it reappears magically.
