### ISSUE TITLE
2019.0 projection output not always on top

### ISSUE THREAD

**Issue by dmcharpentier** [quelea-projection/Quelea#96]
I'm not sure if this was changed on purpose but I was just at church for a rehearsal and I noticed that I could drag my mouse and various windows ON TOP of the projection window. Previously the projection window always stayed on top and nothing from the other screens could intrude. This I believe is the correct behavior.

For times when the software needs to remain open and something else needs to be displayed there is the button to disable output, though admittedly it is disabled in settings by default, it does exist

**Comment by dmcharpentier** [comment]
In this case I'm not talking about power point because of how that displays it typically forces itself on-top.

In this case I could grab, say a normal chrome window, and drag it over. Now previously those would move over but behind the quelea output. Now when I do that same thing it "overlays" (moves in front of) the quelea output. In that same vein the mouse used to be behind but is now visible when it wanders onto the second screen and is displayed on-top of the quelea output.

**Comment by berry120** [comment]
I have a vague recollection we may have had to change a few things around window display order to get VLC to display the video correctly on some platforms, so it *may* be related to that. If so then there's probably not a lot we can do to restore the old behaviour unless we move away from VLC (which I have considered, but it's not something we'd be doing in the short to medium term).

That being said, aside from when a video is playing the mouse cursor definitely hides for me when moved over the projection window (which is the correct behaviour) - what OS are you using?

**Comment by dmcharpentier** [comment]
Oh the irony... So I just opened Quelea and it seems to be working like yours now, though last sunday I opened and closed it 4-5 times in a row without success. The computer has not been rebooted (or shut off all week) and no software has been updated. The mouse DOES hide now though I can still drag windows on top of the output but I can put up with that. It's more of an issue for new members at my church or when I'm at other church's training new members.

Out of curiosity what prompted this change in display order?

**Comment by berry120** [comment]
If the mouse appears on top again (video backgrounds aside) then let us know!

I'm pretty sure it was to do with getting VLC to display properly on all operating systems, or may have been something to do with scaling... afraid I can't remember the specifics though.
