### ISSUE TITLE
Add suport for bibles .xmm (openlp)

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#97]
Necesito la versión NTV y solo la eh encontrado en .xmm que se usa para openlp, nosé si se pueda añadir soporte para quelea 2019.1 para que se muestre correctamente ?  
Links download..
Mediafire:
https://www.mediafire.com/folder/gm9cmtj482mc8/OpenLP_Biblias_(xmm)
Mega:
https://mega.nz/#F!Shlg3ZxT!7yhz05bD2Sw86oFgqMApJQ
-------------------------------------------------------------------------------------
Dejo una captura de como se muestra la traducción..
![bug xmm](https://user-images.githubusercontent.com/35184132/52158626-258d9200-2668-11e9-9425-3703ec04a0d9.png)

**Comment by berry120** [comment]
Good catch - thanks for the report! Should now be fixed.

**Comment by DeeTigIT** [comment]
I also examined the set of xmm-files that Cyb3rG0D7 posted.
There's one that deserves attention : Nueva Biblia de Jerusalén.xmm

![s1](https://user-images.githubusercontent.com/39883796/52165795-85864600-2705-11e9-8d87-ca71c2e761ae.JPG)

[Nueva Biblia de Jerusalén.xmm.zip](https://github.com/quelea-projection/Quelea/files/2824539/Nueva.Biblia.de.Jerusalen.xmm.zip)

(please remove the .zip extension after download).

**Comment by berry120** [comment]
Ok - attempt number 2. Should be good to go now...
