### ISSUE TITLE
Add hash values to the Quelea site for the downloads

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#99]
Is it possible to add the hash value of each download on the Q site? After download, one can then re-calculate the file hash and compare it to the site- value: they must be the same.

**Comment by berry120** [comment]
Sure. This is now added to the CI release, and we'll aim to publish the hashes of final releases as well from now on. If I forget, just ping me...!

**Comment by DeeTigIT** [comment]
Thanks!

![s1](https://user-images.githubusercontent.com/39883796/52165543-8b2e5c80-2702-11e9-9205-b4f4251958f8.JPG)
